#---------------------------------------------------------------------------------------
#                                       FUNCTIONS                                       
#---------------------------------------------------------------------------------------

ww_ahk()
{
if ! ww_exists "$WW_TEMP/AutoHotkey.exe"
then
    ww_unzip "$WW_TEMP" "$WW_CACHE/ahk.zip" AutoHotkey.exe AU3_Spy.exe
    chmod +x "$WW_TEMP/AutoHotkey.exe"
fi
WW_CR=`printf \\\\r`
cat <<_EOF_ | sed "s/\$/$WW_CR/" > "$WW_TEMP"/tmp.ahk
$@
_EOF_
ww_wine "$WW_TEMP_WIN\\AutoHotkey.exe" "$WW_TEMP_WIN\\tmp.ahk"
unset WW_CR
}

#---------------------------------------------------------------------------------------

ww_cabextract()
{
if test ! -x "`which cabextract 2>/dev/null`"
then
    ww_die "Cannot find cabextract. Please install it (e.g. 'sudo apt-get install cabextract' or 'sudo yum install cabextract')."
fi
ww_try cabextract -q "$@"
}

#---------------------------------------------------------------------------------------

ww_cd()
{
ww_try cd "$@"
}

#---------------------------------------------------------------------------------------

ww_cd_repo()
{
ww_cd "$WW_CACHE"
}

#---------------------------------------------------------------------------------------

ww_cd_repo_wine()
{
ww_cd_repo
ww_wine "$@"
}

#---------------------------------------------------------------------------------------

ww_clear_temp()
{
test -d "$WW_WINDOWS"/Temp && rm -rf "$WW_WINDOWS"/Temp
test -d "$WW_TEMP" && rm -rf "$WW_TEMP"
mkdir -p "$WW_TEMP"
}

#---------------------------------------------------------------------------------------

ww_cp()
{
ww_try cp -f "$@"
}

#---------------------------------------------------------------------------------------

ww_create_prefix()
{
ww_download 76dd113ccf85803542c8c2fac421ea5a593e7404 'winemenubuilder.exe' 'https://github.com/LLIAKAJL/WineWizard-Utils/blob/master/winemenubuilder/winemenubuilder.exe?raw=true' ''
wineboot -u
wineserver -w
cd "$WINEPREFIX"
mkdir ".documents"
cd "dosdevices/c:/users/$USER"
for f in *
do
    if [ -h "$f" ]
    then
        mkdir "$WINEPREFIX/.documents/$f"
        rm "$f"
        ln -s "../../../.documents/$f" "$f"
    fi
done
rm "$WW_SYSTEM32"/winemenubuilder.exe
ww_cp "$WW_CACHE"/winemenubuilder.exe "$WW_SYSTEM32"
}

#---------------------------------------------------------------------------------------

ww_d3dx_helper()
{
dllname=$1
ww_cabextract -d "$WW_TEMP" -L -F "*$dllname*x86*" "$WW_DX_FEB_PATH"
for x in "$WW_TEMP"/*.cab
do
    ww_cabextract -d "$WW_SYSTEM32" -L -F "$dllname.dll" "$x"
done
ww_override native $dllname
}

#---------------------------------------------------------------------------------------

ww_die()
{
ww_warn "$@"
exit 1
}

#---------------------------------------------------------------------------------------

ww_done()
{
ww_clear_temp
}

#---------------------------------------------------------------------------------------

ww_download()
{
local WW_SUM=$1
shift
local WW_OUT="$WW_CACHE/$1"
shift
if test -f "$WW_OUT"
then
    local WW_GOTSUM=$(ww_sha1sum "$WW_OUT" | sed 's/ .*//')
    test "$WW_SUM" = "$WW_GOTSUM" && return 0
fi
while test "$1" != ""
do
    WW_URL=$1
    shift
    WW_RE=$1
    shift
    wget --no-check-certificate "$WW_URL" -O "$WW_OUT" 2>&1
    WW_URL=''
    test -z "$WW_RE" || WW_URL=$(cat "$WW_OUT" | sed -n "s/$WW_RE/\1/p")
    test -z "$WW_URL" || wget -O "$WW_OUT" --no-check-certificate "$WW_URL" 2>&1
    if test -f "$WW_OUT"
    then
        local WW_GOTSUM=$(ww_sha1sum "$WW_OUT" | sed 's/ .*//')
        if [ "$WW_SUM" = "$WW_GOTSUM" ]
        then
            return 0
        fi
    fi
done
ww_die "Download error!"
}

#---------------------------------------------------------------------------------------

ww_droid_helper()
{
ww_cp "$WW_CACHE"/$1 "$WW_FONTS"
ww_register_font $1 "$2"
}

#---------------------------------------------------------------------------------------

ww_dx_feb2010_download()
{
ww_download a97c820915dc20929e84b49646ec275760012a42 'directx9.feb2010.exe' 'http://download.microsoft.com/download/E/E/1/EE17FF74-6C45-4575-9CF4-7FC2597ACD18/directx_feb2010_redist.exe' ''
}

#---------------------------------------------------------------------------------------

ww_dx_jun2010_download()
{
ww_download f8f1217f666bf2f6863631a7d5e5fb3a8d1542df 'directx9.jun2010.exe' 'http://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe' ''
}

#---------------------------------------------------------------------------------------

ww_early_wine()
{
WINEDEBUG=-all wine "$@" 2> /dev/null | ( sed 's/.*1h.=//' | tr -d '\r' | grep -v "Module not found" || true)
}

#---------------------------------------------------------------------------------------

ww_exists()
{
test -f "$1"
}

#---------------------------------------------------------------------------------------

ww_fontfix()
{
if ww_exists /usr/share/fonts/truetype/arphic/ukai.ttf
then
    local gotsum=$(ww_sha1sum /usr/share/fonts/truetype/arphic/ukai.ttf)
    if [ "$gotsum"x = "96e1121f89953e5169d3e2e7811569148f573985"x ]
    then
        ww_die "Your installed ukai.ttf is known to be broken. Upgrade your ttf-arphic font package!"
    fi
fi
if ww_exists /usr/share/fonts/truetype/arphic/uming.ttf
then
    local gotsum=$(ww_sha1sum /usr/share/fonts/truetype/arphic/uming.ttf)
    if [ "$gotsum"x = "2a4f4a69e343c21c24d044b2cb19fd4f0decc82c"x ]
    then
        ww_die "Your installed uming.ttf is known to be broken. Upgrade your ttf-uming font package!"
    fi
fi
if xlsfonts 2>/dev/null | egrep -i "samyak.*oriya"
then
    ww_die "Please uninstall the Samyak/Oriya font, e.g. 'sudo dpkg -r ttf-oriya-fonts', then log out and log in again.  That font causes strange crashes in .net programs."
fi
}

#---------------------------------------------------------------------------------------

ww_info()
{
echo "------------------------------------------------------"
echo "$@"
echo "------------------------------------------------------"
}

#---------------------------------------------------------------------------------------

ww_init()
{
if [ -z "$WW_SCREEN_RES" ]
then
    WW_SCREEN_RES=$(xrandr -q | awk -F'current' -F',' 'NR==1 {gsub("( |current)","");print $2}')
fi
if [ -z "$WW_VMEMORY_SIZE" ]
then
    WW_VMEMORY_SIZE="default"
fi

XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
WW_CACHE="$XDG_CACHE_HOME/winewizard"
WW_C="$WINEPREFIX/dosdevices/c:"
WW_WINDOWS="$WW_C/windows"

WW_SYSTEM32="$WW_WINDOWS/system32"
WW_SYSTEM32_WIN="C:\\windows\\system32"

WW_PROGRAM_FILES="$WW_C/Program Files"

WW_FONTS="$WW_WINDOWS/Fonts"
WW_TEMP="$WW_WINDOWS/temp"
WW_TEMP_WIN="C:\\windows\\temp"
WW_COMMON_FILES="$WW_PROGRAM_FILES/Common Files"

WW_UNATTENDED_DASH_Q="-q"
WW_UNATTENDED_SLASH_Q="/q"
WW_UNATTENDED_SLASH_QB="/qb"
WW_UNATTENDED_SLASH_QN="/qn"
WW_UNATTENDED_SLASH_QNT="/qnt"
WW_UNATTENDED_SLASH_QT="/qt"
WW_UNATTENDED_SLASH_QUIET="/quiet"
WW_UNATTENDED_SLASH_S="/S"
WW_UNATTENDED_DASH_SILENT="-silent"
WW_UNATTENDED_SLASH_SILENT="/silent"

case "$WW_WINE_VERSION" in
    1.4-*)     WW_WINE_VERSION="1.4.40"; export WW_WINE_VERSION;;
    1.4)       WW_WINE_VERSION="1.4.0";  export WW_WINE_VERSION;;
    1.6-*)     WW_WINE_VERSION="1.6.0";  export WW_WINE_VERSION;;
    1.6)       WW_WINE_VERSION="1.6.0";  export WW_WINE_VERSION;;
    1.8-*)     WW_WINE_VERSION="1.8.0";  export WW_WINE_VERSION;;
    1.8)       WW_WINE_VERSION="1.8.0";  export WW_WINE_VERSION;;
esac
WW_WINE_MINOR=`echo $WW_WINE_VERSION | sed 's/1\.\([0-9]*\)\..*/\1/'`
WW_WINE_MICRO=`echo $WW_WINE_VERSION | sed 's/1.[0-9][0-9]*\.\([0-9]*\).*/\1/'`

WW_DX_FEB_PATH="$WW_CACHE"/directx9.feb2010.exe
WW_DX_JUN_PATH="$WW_CACHE"/directx9.jun2010.exe
}

#---------------------------------------------------------------------------------------

ww_install()
{
package=$1
ww_download_$package
ww_check_$package && return
ww_clear_temp
ww_info "Package installation: $package ..."
ww_install_$package
}

#---------------------------------------------------------------------------------------

ww_install_wine()
{
test -f "$WW_CACHE"/wslin32 && rm "$WW_CACHE"/wslin32
wget 'https://www.playonlinux.com/wine/binaries/linux-x86.lst' -O "$WW_CACHE"/wslin32 2>&1
csum=$(ww_wine_checksum "$WW_WINE_VERSION")
rm "$WW_CACHE"/wslin32
ww_download $csum "$WW_WINE_VERSION.pol" "https://www.playonlinux.com/wine/binaries/linux-x86/PlayOnLinux-wine-$WW_WINE_VERSION-linux-x86.pol" ''
test -d "$WINEPREFIX" || mkdir "$WINEPREFIX"
ww_cd "$WINEPREFIX"
test -d "$WINEPREFIX"/.wine && rm -rf "$WINEPREFIX/.wine"
tar xvjf "$WW_CACHE/$WW_WINE_VERSION.pol"
mv wineversion/* "$WINEPREFIX/.wine"
rm -rf files
rm -rf playonlinux
rm -rf wineversion
}

#---------------------------------------------------------------------------------------

ww_killall()
{
kill -s KILL `pgrep $1`
}

#---------------------------------------------------------------------------------------

ww_mv()
{
ww_try mv "$@"
}

#---------------------------------------------------------------------------------------

ww_native()
{
ww_exists "$1" && ! grep -q "Wine placeholder DLL" "$1"
}

#---------------------------------------------------------------------------------------

ww_override()
{
mode=$1
shift
echo Using $mode override for following DLLs: $@
cat > "$WW_TEMP"/override-dll.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\DllOverrides]
_EOF_
ww_override_helper "$@"
unset mode
}

#---------------------------------------------------------------------------------------

ww_override_app()
{
app=$1
shift
mode=$1
shift
echo Using $mode override for following DLLs when running $app: $@
(
    echo REGEDIT4
    echo ""
    echo "[HKEY_CURRENT_USER\\Software\\Wine\\AppDefaults\\$app\\DllOverrides]"
) > "$WW_TEMP"/override-dll.reg
ww_override_helper "$@"
unset app mode
}

#---------------------------------------------------------------------------------------

ww_override_helper()
{
case $mode in
    native,builtin) mode='"native,builtin"' ;;
    native)         mode='"native"' ;;
    builtin)        mode='"builtin"' ;;
    default)        mode=- ;;
    disabled)       mode='""' ;;
    *) ww_die "Bug: unknown override $mode. (want native, builtin, default, or disabled)." ;;
esac
while test "$1" != ""
do
    [ "$1" = comctl32 ] && rm -rf "$WW_WINDOWS"/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
    echo "\"*$1\"=$mode" >> "$WW_TEMP"/override-dll.reg
    shift
done
ww_regedit "$WW_TEMP_WIN"\\override-dll.reg
rm "$WW_TEMP"/override-dll.reg
}

#---------------------------------------------------------------------------------------

ww_regedit()
{
ww_try ww_early_wine regedit $WW_UNATTENDED_SLASH_S "$@"
}

#---------------------------------------------------------------------------------------

ww_register_font()
{
file=$1
shift
font=$1

case "$file" in
    *.TTF|*.ttf) font="$font (TrueType)";;
esac

cat > "$WW_TEMP"/_register-font.reg <<_EOF_
REGEDIT4

[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts]
"$font"="$file"
_EOF_

ww_regedit "$WW_TEMP_WIN"\\_register-font.reg

cat > "$WW_TEMP"/_register-font.reg <<_EOF_
REGEDIT4

[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Fonts]
"$font"="$file"
_EOF_

ww_regedit "$WW_TEMP_WIN"\\_register-font.reg
}

#---------------------------------------------------------------------------------------

ww_register_font_replacement()
{
_ww_alias=$1
shift
_ww_font=$1
cat > "$WW_TEMP"/_register-font-replacements.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\Fonts\Replacements]
"$_ww_alias"="$_ww_font"
_EOF_
ww_regedit "$WW_TEMP_WIN"\\_register-font-replacements.reg
unset _ww_alias _ww_font
}

#---------------------------------------------------------------------------------------

ww_regsvr()
{
ww_wine regsvr32 $WW_UNATTENDED_SLASH_S "$@"
}

#---------------------------------------------------------------------------------------

ww_remove_mono()
{
mono_uuid="`wine uninstaller --list | grep Mono | cut -f1 -d\|`"
if test "$mono_uuid"
then
     wine uninstaller --remove $mono_uuid
else
    ww_warn "Mono does not appear to be installed."
fi
}

#---------------------------------------------------------------------------------------

ww_setup()
{
if [ -d "$WW_WORK_DIR" ]
then
    cd "$WW_WORK_DIR"
fi
echo "$WW_ARGS" | xargs wine start /Unix "$WW_EXE"
wineserver -w
}

#---------------------------------------------------------------------------------------

ww_set_fontsmooth()
{
case $1 in
    disable)   FontSmoothing=0; FontSmoothingOrientation=1; FontSmoothingType=0;;
    gray|grey) FontSmoothing=2; FontSmoothingOrientation=1; FontSmoothingType=1;;
    bgr)       FontSmoothing=2; FontSmoothingOrientation=0; FontSmoothingType=2;;
    rgb)       FontSmoothing=2; FontSmoothingOrientation=1; FontSmoothingType=2;;
    *) ww_die "unknown font smoothing type $1";;
esac

echo "Setting font smoothing to $1"

cat > "$WW_TEMP"/fontsmooth.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Control Panel\Desktop]
"FontSmoothing"="$FontSmoothing"
"FontSmoothingGamma"=dword:00000578
"FontSmoothingOrientation"=dword:0000000$FontSmoothingOrientation
"FontSmoothingType"=dword:0000000$FontSmoothingType

_EOF_
ww_regedit "$WW_TEMP_WIN"\\fontsmooth.reg
}

#---------------------------------------------------------------------------------------

ww_set_grabfullscreen()
{
case $1 in
    y|n) arg=$1;;
    *) ww_die "illegal value $1 for GrabFullscreen";;
esac

echo "Setting GrabFullscreen to $arg"
cat > "$WW_TEMP"/set-gfs.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\X11 Driver]
"GrabFullscreen"="$arg"

_EOF_
ww_regedit "$WW_TEMP_WIN"\\set-gfs.reg
}

#---------------------------------------------------------------------------------------

ww_set_hidewineexports()
{
case $1 in
    enable) local registry_value="\"Y\"" ;;
    disable) local registry_value="-" ;;
    *) ww_die "Unexpected argument, $arg";;
esac

cat > "$WW_TEMP"/set-wineexports.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine]
"HideWineExports"=$registry_value

_EOF_
ww_regedit "$WW_TEMP_WIN"\\set-wineexports.reg
}

#---------------------------------------------------------------------------------------

ww_set_mwo()
{
case $1 in
    enable*) arg=enabled;;
    disable*) arg=disable;;
    force) arg=force;;
    *) ww_die "illegal value $1 for MouseWarpOverride";;
esac

echo "Setting MouseWarpOverride to $arg"
cat > "$WW_TEMP"/set-mwo.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\DirectInput]
"MouseWarpOverride"="$arg"

_EOF_
ww_regedit "$WW_TEMP_WIN"\\set-mwo.reg
}

#---------------------------------------------------------------------------------------

ww_set_sound()
{
echo "Setting sound driver to $1"
cat > "$WW_TEMP"/set-sound.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\Drivers]
"Audio"="$1"

_EOF_
ww_regedit "$WW_TEMP_WIN"\\set-sound.reg
}

#---------------------------------------------------------------------------------------

ww_set_videomemorysize()
{
size=$1
echo "Setting video memory size to $size"

case $size in
    default)
        cat > "$WW_TEMP"/set-video.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\Direct3D]
"VideoMemorySize"=-

_EOF_
    ;;
    *)
	    cat > "$WW_TEMP"/set-video.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\Direct3D]
"VideoMemorySize"="$size"

_EOF_
esac
ww_regedit "$WW_TEMP_WIN"\\set-video.reg
}

#---------------------------------------------------------------------------------------

ww_set_virtual_desktop()
{
desktop=$1
case $desktop in
    off)
        cat > "$WW_TEMP"/vd.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\Explorer]
"Desktop"=-
[HKEY_CURRENT_USER\Software\Wine\Explorer\Desktops]
"Default"=-

_EOF_
        ;;
    on)
        cat > "$WW_TEMP"/vd.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\Explorer]
"Desktop"="Default"
[HKEY_CURRENT_USER\Software\Wine\Explorer\Desktops]
"Default"="$2"

_EOF_
        ;;
esac
ww_regedit "$WW_TEMP_WIN"\\vd.reg
}

#---------------------------------------------------------------------------------------

ww_set_windowmanagerdecorated()
{
case $1 in
    y|n) arg=$1;;
    *) ww_die "illegal value $1 for Decorated";;
esac

echo "Setting Decorated to $arg"
cat > "$WW_TEMP"/set-wmd.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\X11 Driver]
"Decorated"="$arg"

_EOF_
ww_regedit "$WW_TEMP_WIN"\\set-wmd.reg
}

#---------------------------------------------------------------------------------------

ww_set_windowmanagermanaged()
{
case $1 in
    y|n) arg=$1;;
    *) ww_die "illegal value $1 for Managed";;
esac

echo "Setting Managed to $arg"
cat > "$WW_TEMP"/set-wmm.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\X11 Driver]
"Managed"="$arg"

_EOF_
ww_regedit "$WW_TEMP_WIN\\set-wmm.reg"
}

#---------------------------------------------------------------------------------------

ww_set_wined3d_var()
{
case $2 in
    disable*) arg=disabled;;
    enable*)  arg=enabled;;
    hard*)    arg=hardware;;
    repack)   arg=repack;;
    backbuffer|fbo|gdi|none|opengl|readdraw|readtex|texdraw|textex|auto) arg=$2;;
    [0-9]*)   arg=$2;;
    *) ww_die "illegal value $2 for $1";;
esac
echo "Setting Direct3D/$1 to $arg"
cat > "$WW_TEMP"/set-wined3d.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\Direct3D]
"$1"="$arg"

_EOF_
ww_regedit "$WW_TEMP_WIN\\set-wined3d.reg"
}

#---------------------------------------------------------------------------------------

ww_set_winver()
{
(
    wine reg delete "HKLM\Software\Microsoft\Windows\CurrentVersion" /v SubVersionNumber /f || true
    wine reg delete "HKLM\Software\Microsoft\Windows\CurrentVersion" /v VersionNumber /f || true
    wine reg delete "HKLM\Software\Microsoft\Windows NT\CurrentVersion" /v CSDVersion /f || true
    wine reg delete "HKLM\Software\Microsoft\Windows NT\CurrentVersion" /v CurrentBuildNumber /f || true
    wine reg delete "HKLM\Software\Microsoft\Windows NT\CurrentVersion" /v CurrentVersion /f || true
    wine reg delete "HKLM\System\CurrentControlSet\Control\ProductOptions" /v ProductType /f || true
    wine reg delete "HKLM\System\CurrentControlSet\Control\ServiceCurrent" /v OS /f || true
    wine reg delete "HKLM\System\CurrentControlSet\Control\Windows" /v CSDVersion /f || true
    wine reg delete "HKCU\Software\Wine" /v Version /f || true
    wine reg delete "HKLM\\System\\CurrentControlSet\\Control\\ProductOptions" /v ProductType /f || true
) > /dev/null 2>&1

    case $1 in
    win31)
        echo "Setting Windows version to $1"
        cat > "$WW_TEMP"/set-winver.reg <<_EOF_
REGEDIT4

[HKEY_USERS\S-1-5-4\Software\Wine]
"Version"="win31"

_EOF_
        ww_regedit "$WW_TEMP_WIN"\\set-winver.reg
        return
        ;;
    win95)
        echo "Setting Windows version to $1"
        cat > "$WW_TEMP"/set-winver.reg <<_EOF_
REGEDIT4

[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion]
"ProductName"="Microsoft Windows 95"
"SubVersionNumber"=""
"VersionNumber"="4.0.950"

_EOF_
        ww_regedit "$WW_TEMP_WIN"\\set-winver.reg
        return
        ;;
    win98)
        echo "Setting Windows version to $1"
        cat > "$WW_TEMP"/set-winver.reg <<_EOF_
REGEDIT4

[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion]
"ProductName"="Microsoft Windows 98"
"SubVersionNumber"=" A "
"VersionNumber"="4.10.2222"

_EOF_
        ww_regedit "$WW_TEMP_WIN"\\set-winver.reg
        return
        ;;
    nt40)
        echo "Setting Windows version to $1"
        cat > "$WW_TEMP"/set-winver.reg <<_EOF_
REGEDIT4

[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion]
"CSDVersion"="Service Pack 6a"
"CurrentBuildNumber"="1381"
"CurrentVersion"="4.0"

[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\ProductOptions]
"ProductType"="WinNT"

[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\ServiceCurrent]
"OS"="Windows_NT"

[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows]
"CSDVersion"=dword:00000600

_EOF_
        ww_regedit "$WW_TEMP_WIN"\\set-winver.reg
        return
        ;;
    win2k)
        csdversion="Service Pack 4"
        currentbuildnumber="2195"
        currentversion="5.0"
        csdversion_hex=dword:00000400
        ;;
    winxp)
        csdversion="Service Pack 3"
        currentbuildnumber="2600"
        currentversion="5.1"
        csdversion_hex=dword:00000300
        ;;
    win2k3)
        csdversion="Service Pack 2"
        currentbuildnumber="3790"
        currentversion="5.2"
        csdversion_hex=dword:00000200
        wine reg add "HKLM\\System\\CurrentControlSet\\Control\\ProductOptions" /v ProductType /d "ServerNT" /f
        ;;
    vista)
        csdversion="Service Pack 2"
        currentbuildnumber="6002"
        currentversion="6.0"
        csdversion_hex=dword:00000200
        wine reg add "HKLM\\System\\CurrentControlSet\\Control\\ProductOptions" /v ProductType /d "WinNT" /f
        ;;
    win7)
        csdversion="Service Pack 1"
        currentbuildnumber="7601"
        currentversion="6.1"
        csdversion_hex=dword:00000100
        wine reg add "HKLM\\System\\CurrentControlSet\\Control\\ProductOptions" /v ProductType /d "WinNT" /f
        ;;
    *)
        ww_die "Invalid Windows version given."
        ;;
    esac
# ------------------- WINDOWS 8 -----------------
# "CSDVersion"=" "
# "CurrentBuildNumber"="9200"
# "CurrentVersion"="6.2"
# "ProductName"="Microsoft Windows 8"
# csdversion_hex=dword:00000000
# -----------------------------------------------
    echo "Setting Windows version to $1"
    cat > "$WW_TEMP"/set-winver.reg <<_EOF_
REGEDIT4

[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion]
"CSDVersion"="$csdversion"
"CurrentBuildNumber"="$currentbuildnumber"
"CurrentVersion"="$currentversion"

[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows]
"CSDVersion"=$csdversion_hex

_EOF_
ww_regedit "$WW_TEMP_WIN"\\set-winver.reg
}

#---------------------------------------------------------------------------------------

ww_sha1sum()
{
local WW_FILE="$1"
if [ -x "`which sha1sum 2>/dev/null`" ]
then
    sha1sum < "$WW_FILE" | sed 's/(stdin)= //;s/ .*//'
elif [ -x "`which openssl 2>/dev/null`" ]
then
    openssl dgst -sha1 < "$WW_FILE" | sed 's/(stdin)= //;s/ .*//'
else
    ww_die "No sha1sum utility available."
fi
}

#---------------------------------------------------------------------------------------

ww_try()
{
export WINEDLLOVERRIDES
printf '%s\n' "Executing $*"
"$@"
status=$?
if test $status -ne 0
then
    ww_die "Note: command '$@' returned status $status.  Aborting."
fi
}

#---------------------------------------------------------------------------------------

ww_unset_winver()
{
ww_set_winver winxp
}

#---------------------------------------------------------------------------------------

ww_unzip()
{
destdir="$1"
zipfile="$2"
shift 2
if test -x "`which unzip 2>/dev/null`"
then
    ww_try unzip -o -q -d"$destdir" "$zipfile" "$@"
else
    ww_die "Cannot find unzip. Please install it (e.g. 'sudo apt-get install unzip' or 'sudo yum install unzip')."
fi
unset destdir zipfile
}

#---------------------------------------------------------------------------------------

ww_vcrun6_helper()
{
if test ! -f "$WW_TEMP"/vcredist.exe
then
    ww_wine "$WW_CACHE"/vcrun6.exe "/T:$WW_TEMP_WIN" /c $WW_UNATTENDED_SLASH_Q
    ww_exists "$WW_TEMP"/vcredist.exe || ww_die vcredist.exe not found
fi
}

#---------------------------------------------------------------------------------------

ww_warn()
{
echo "------------------------------------------------------" >&2
echo "$@" >&2
echo "------------------------------------------------------" >&2
}

#---------------------------------------------------------------------------------------

ww_win2ksp4_helper()
{
filename=$1
ww_cabextract -d "$WW_TEMP" -L -F $filename "$WW_CACHE"/win2ksp4.exe
}

#---------------------------------------------------------------------------------------

ww_win7sp1_helper()
{
filename=$1
ww_cabextract -d "$WW_TEMP" -L -F $filename "$WW_CACHE"/win7sp1.exe
}

#---------------------------------------------------------------------------------------

ww_wine()
{
ww_try wine "$@"
}

#---------------------------------------------------------------------------------------

ww_wine_checksum()
{
test -f "$WW_CACHE"/wslin32 || ww_die "Wine checksum base doesn't found!"
cat "$WW_CACHE"/wslin32 | grep "$1;" | cut -d';' -f3-

}

#---------------------------------------------------------------------------------------

ww_wine_version()
{
case $2 in
    1.3.*)     minor=3; micro=`echo $2 | sed 's/.*\.//'`;;
    1.4)       minor=4; micro=0;;
    1.4.*)     minor=4; micro=`echo $2 | sed 's/.*\.//'`;;
    1.5.*)     minor=5; micro=`echo $2 | sed 's/.*\.//'`;;
    1.6|1.6-*) minor=6; micro=0;;
    1.6.*)     minor=6; micro=`echo $2 | sed 's/.*\.//'`;;
    1.7.*)     minor=7; micro=`echo $2 | sed 's/.*\.//'`;;
    1.8|1.8-*) minor=8; micro=0;;
    1.8.*)     minor=8; micro=`echo $2 | sed 's/.*\.//'`;;
    1.9.*)     minor=9; micro=`echo $2 | sed 's/.*\.//'`;;
    *)         ww_die "Bug: unrecognized version $2";;
esac
if test $WW_WINE_MINOR = $minor
then
    test $WW_WINE_MICRO $1 $micro || return 1
else
    test $WW_WINE_MINOR $1 $minor || return 1
fi
}

#---------------------------------------------------------------------------------------

ww_wine_version_in()
{
for range
do
  val1=`echo $range | sed 's/,.*//'`
  val2=`echo $range | sed 's/.*,//'`

  # If in this range, return true
  case $range in
  ,*)                                ww_wine_version -le "$val2" && unset range val1 val2 && return 0;;
  *,) ww_wine_version -ge "$val1"                                && unset range val1 val2 && return 0;;
  *)  ww_wine_version -ge "$val1" && ww_wine_version -le "$val2" && unset range val1 val2 && return 0;;
  esac
done
unset range val1 val2
return 1
}

#---------------------------------------------------------------------------------------

ww_wm9codecs()
{
ww_set_winver win2k
ww_cd_repo_wine wm9codecs.exe $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_workaround_wine_bug()
{
case "$2" in
[0-9]*) ww_die "Bug: want message in ww_workaround_wine_bug arg 2, got $2" ;;
"") _ww_msg="";;
*)  _ww_msg="-- $2";;
esac
if test "$3" && ww_wine_version_in $3 $4 $5 $6
then
    echo Current wine does not have wine bug $1, so not applying workaround
    return 1
fi
case $LANG in
    da*) ww_warn "Arbejder uden om wine-fejl ${1} $_ww_msg" ;;
    de*) ww_warn "Wine-Fehler ${1} wird umgegangen $_ww_msg" ;;
    pl*) ww_warn "Obchodzenie błędu w wine ${1} $_ww_msg" ;;
    ru*) ww_warn "Обход ошибки ${1} $_ww_msg" ;;
    uk*) ww_warn "Обхід помилки ${1} $_ww_msg" ;;
    zh_CN*) ww_warn "绕过 wine bug ${1} $_ww_msg" ;;
    zh_TW*|zh_HK*) ww_warn "繞過 wine bug ${1} $_ww_msg" ;;
    *) ww_warn "Working around wine bug ${1} $_ww_msg" ;;
esac
return 0
}

#---------------------------------------------------------------------------------------

ww_xpsp3_helper()
{
filename=$1
ww_cabextract -d "$WW_TEMP" -L -F $filename "$WW_CACHE"/xpsp3.exe
}

#---------------------------------------------------------------------------------------
#                                       PACKAGES                                        
#---------------------------------------------------------------------------------------

ww_download_adobeair()
{
ww_download 2fdd561556fe881c4e5538d4ee37f523871befd3 'adobeair.exe' 'http://airdownload.adobe.com/air/win/download/20.0/AdobeAIRInstaller.exe' '' 
}

ww_check_adobeair()
{
ww_native "$WW_COMMON_FILES/Adobe AIR/Versions/1.0/Adobe AIR.dll"
}

ww_install_adobeair()
{
ww_cd_repo_wine adobeair.exe $WW_UNATTENDED_DASH_SILENT
}

#---------------------------------------------------------------------------------------

ww_download_allcodecs()
{
ww_download b3981b13fbc45823131f69d125992d6330212f27 'ahk.zip' 'http://www.autohotkey.com/download/AutoHotkey104805.zip' '' 
ww_download c912d30a8fa500c7841444559feb1f49301611c4 'dirac.exe' 'http://downloads.sourceforge.net/dirac/DiracDirectShowFilter-1.0.2.exe' '' 
ww_dx_feb2010_download
ww_download 8534c31489e51df70ee9583438d6211e6f0696d0 'ffdshow.exe' 'http://downloads.sourceforge.net/ffdshow-tryout/ffdshow_beta7_rev3154_20091209.exe' '' 
ww_download 2c5d64f472abe3f601ce352dcca75b4f02996f8a 'icodecs.exe' 'http://www.cucusoft.com/codecdownload/codinstl.exe' '' 
ww_download 470640aa4bb7db8e69196b5edb0010933569e98d 'vcrun2008.exe' 'http://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe' '' 
ww_download a8c4dd33e281c166488846a10edf97ff0ce37044 'vcrun6.exe' 'http://download.microsoft.com/download/vc60pro/Update/2/W9XNT4/EN-US/VC6RedistSetup_deu.exe' '' 
ww_download 0a11498a96f75ad019c4c7d06161504140337dc0 'xvid.exe' 'http://www.koepi.info/Xvid-1.3.2-20110601.exe' '' 
}

ww_check_allcodecs()
{
false
}

ww_install_allcodecs()
{
ww_install dirac
ww_install l3codecx
ww_install ffdshow
ww_install icodecs
ww_install xvid
}

#---------------------------------------------------------------------------------------

ww_download_allfonts()
{
ww_download 560e4bcafdebaf29645fbf92633a2ae0d2f9801f 'DroidSans-Bold.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSans-Bold.ttf' '' 
ww_download 62f2841f61e4be66a0303cd1567ed2d300b4e31c 'DroidSans.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSans.ttf' '' 
ww_download c5e4f11e2f1d0b84e5f268a7ebfd28b54dc6bcdc 'DroidSansFallback.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSansFallback.ttf' '' 
ww_download b3a248c11692aa88a30eb25df425b8910fe05dc5 'DroidSansJapanese.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSansJapanese.ttf' '' 
ww_download 133fb6cf26ea073b456fb557b94ce8c46143b117 'DroidSansMono.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSansMono.ttf' '' 
ww_download 2775e9b8e96a3e9593acb5cf6923abb2e6008187 'DroidSerif-Bold.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSerif-Bold.ttf' '' 
ww_download 41ce5fef1bd0164caed6958885d7285c841c95f1 'DroidSerif-BoldItalic.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSerif-BoldItalic.ttf' '' 
ww_download e91cc6c1ae9a6699683bcee024551cb58d1be790 'DroidSerif-Italic.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSerif-Italic.ttf' '' 
ww_download a689ce25a4063cf501c12d616f832f2235b5b93b 'DroidSerif-Regular.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSerif-Regular.ttf' '' 
ww_download 6d75f8436f39ab2da5c31ce651b7443b4ad2916e 'arial32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/arial32.exe' '' 
ww_download d45cdab84b7f4c1efd6d1b369f50ed0390e3d344 'arialb32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/arialb32.exe' '' 
ww_download afdee34f700007de6ea87b43c92a88b7385ba65b 'baekmuk.tar.gz' 'http://http.debian.net/debian/pool/main/f/fonts-baekmuk/fonts-baekmuk_2.2.orig.tar.gz' '' 
ww_download ab48a8ebac88219c84f293c6c1e81f1a0f420da6 'cam-const-cons.exe' 'http://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe' '' 
ww_download 2371d0327683dcc5ec1684fe7c275a8de1ef9a51 'comic32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/comic32.exe' '' 
ww_download 06a745023c034f88b4135f5e294fece1a3c1b057 'courie32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/courie32.exe' '' 
ww_download 9b076c40cb63aa0d8512aa8e610ba11d3466e441 'eufonts.exe' 'http://download.microsoft.com/download/a/1/8/a180e21e-9c2b-4b54-9c32-bf7fd7429970/EUupdate.EXE' '' 
ww_download 90e4070cb356f1d811acb943080bf97e419a8f1e 'georgi32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/georgi32.exe' '' 
ww_download 86b34d650cfbbe5d3512d49d2545f7509a55aad2 'impact32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/impact32.exe' '' 
ww_download 57dd13ab58c0005d3ee2932539e4987ab0242bc7 'ipamona.tar.gz' 'http://www.geocities.jp/ipa_mona/opfc-ModuleHP-1.1.1_withIPAMonaFonts-1.0.8.tar.gz' '' 
ww_download 097882c92e3260742a3dc3bf033792120d8635a3 'liberation.tar.gz' 'https://fedorahosted.org/releases/l/i/liberation-fonts/liberation-fonts-1.04.tar.gz' '' 
ww_download 64c47ad92265f6f10b0fd909a703d4fd1b05b2d5 'lucida.exe' 'ftp://ftp.fu-berlin.de/pc/security/ms-patches/winnt/usa/NT40TSE/hotfixes-postSP3/Euro-fix/eurofixi.exe' '' 
ww_download d3e2dd921c6694d24865600e40eceaf2a635d1c6 'opensymbol.deb' 'http://security.debian.org/debian-security/pool/updates/main/libr/libreoffice/fonts-opensymbol_102.6+LibO4.3.3-2+deb8u3_all.deb' '' 'https://web.archive.org/web/20160414161149/http://security.debian.org/debian-security/pool/updates/main/libr/libreoffice/fonts-opensymbol_102.6+LibO4.3.3-2+deb8u3_all.deb' '' 
ww_download 888ce7b7ab5fd41f9802f3a65fd0622eb651a068 'tahoma.exe' 'http://download.microsoft.com/download/office97pro/fonts/1/w95/en-us/tahoma32.exe' '' 'https://web.archive.org/web/20160401090253/http://download.microsoft.com/download/office97pro/fonts/1/w95/en-us/tahoma32.exe' '' 
ww_download 4f636d5c7c1bc16b96ea723adb16838cfb6df059 'takao.zip' 'http://launchpad.net/takao-fonts/trunk/003.02.01/+download/takao-fonts-ttf-003.02.01.zip' '' 
ww_download 20b79e65cdef4e2d7195f84da202499e3aa83060 'times32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/times32.exe' '' 
ww_download 50aab0988423efcc9cf21fac7d64d534d6d0a34a 'trebuc32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/trebuc32.exe' '' 
ww_download efbab0d5d8cb5cff091307d2360dcb1bfe1ae6e1 'uff.zip' 'http://font.ubuntu.com/download/ubuntu-font-family-0.70.1.zip' '' 
ww_download bb8a3960dc0a96aa305de28312ea8a0ab64123d2 'unifont.zip' 'http://unifoundry.com/unifont-5.1.20080907.zip' '' 
ww_download f5b93cedf500edc67502f116578123618c64a42a 'verdan32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/verdan32.exe' '' 
ww_download 2fb4a42c53e50bc70707a7b3c57baf62ba58398f 'webdin32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/webdin32.exe' '' 
ww_download 28023041b22b6368bcfae076de68109b81e77976 'wenquanyi.tar.gz' 'http://downloads.sourceforge.net/wqy/wqy-microhei-0.2.0-beta.tar.gz' '' 
}

ww_check_allfonts()
{
false
}

ww_install_allfonts()
{
ww_install cambria
ww_install constantia
ww_install consolas
ww_install corefonts
ww_install droid
ww_install eufonts
ww_install liberation
ww_install lucida
ww_install opensymbol
ww_install tahoma
ww_install uff
ww_install unifont
ww_install cjkfonts
ww_install fakejapanese_ipamona
}

#---------------------------------------------------------------------------------------

ww_download_amstream()
{
ww_dx_feb2010_download
}

ww_check_amstream()
{
ww_native "$WW_SYSTEM32/amstream.dll"
}

ww_install_amstream()
{
ww_cabextract -d "$WW_TEMP" -L -F dxnt.cab "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'amstream.dll' "$WW_TEMP/dxnt.cab"
ww_regsvr amstream.dll

ww_override native amstream
}

#---------------------------------------------------------------------------------------

ww_download_ao_disabled()
{
:
}

ww_check_ao_disabled()
{
false
}

ww_install_ao_disabled()
{
ww_set_wined3d_var AlwaysOffscreen disabled
}

#---------------------------------------------------------------------------------------

ww_download_ao_enabled()
{
:
}

ww_check_ao_enabled()
{
false
}

ww_install_ao_enabled()
{
ww_set_wined3d_var AlwaysOffscreen enabled
}

#---------------------------------------------------------------------------------------

ww_download_art2kmin()
{
ww_download 571811b7536e97cf4e4e53bbf8260cddd69f9b2d 'art2kmin.exe' 'http://download.microsoft.com/download/D/2/A/D2A2FC8B-0447-491C-A5EF-E8AA3A74FB98/AccessRuntime.exe' '' 
}

ww_check_art2kmin()
{
ww_native "$WW_COMMON_FILES/Microsoft Shared/OFFICE12/ACEES.DLL"
}

ww_install_art2kmin()
{
ww_cd_repo_wine art2kmin.exe $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_atmlib()
{
ww_download fadea6d94a014b039839fecc6e6a11c20afa4fa8 'win2ksp4.exe' 'ftp://ftp.vcitynet.com/win32/win2k/W2KSP4_EN.EXE' '' 'http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 'https://web.archive.org/web/20160129053851/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 
}

ww_check_atmlib()
{
ww_native "$WW_SYSTEM32/atmlib.dll"
}

ww_install_atmlib()
{
ww_win2ksp4_helper i386/atmlib.dl_
ww_cabextract -d "$WW_SYSTEM32" "$WW_TEMP"/i386/atmlib.dl_
}

#---------------------------------------------------------------------------------------

ww_download_avifil32()
{
ww_download c81472f7eeea2eca421e116cd4c03e2300ebfde4 'xpsp3.exe' 'https://web.archive.org/web/20150811102120/http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://mail.digipro.rs/Public/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://soporte.uson.mx/UTILES/04_SERVICE_PACKS/Windows/XP/SP3/ingles/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://ftp.sae24.ru/tools/System/M%24win_SP/xp_sp3/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 
}

ww_check_avifil32()
{
ww_native "$WW_SYSTEM32/avifil32.dll"
}

ww_install_avifil32()
{
ww_xpsp3_helper i386/avifil32.dl_
ww_cabextract -d "$WW_SYSTEM32" "$WW_TEMP"/i386/avifil32.dl_
}

#---------------------------------------------------------------------------------------

ww_download_baekmuk()
{
ww_download afdee34f700007de6ea87b43c92a88b7385ba65b 'baekmuk.tar.gz' 'http://http.debian.net/debian/pool/main/f/fonts-baekmuk/fonts-baekmuk_2.2.orig.tar.gz' '' 
}

ww_check_baekmuk()
{
ww_exists "$WW_FONTS/batang.ttf"
}

ww_install_baekmuk()
{
ww_cd "$WW_TEMP"
tar zxvf "$WW_CACHE/baekmuk.tar.gz" baekmuk-ttf-2.2/ttf
ww_mv baekmuk-ttf-2.2/ttf/*.ttf "$WW_FONTS"
ww_register_font batang.ttf "Baekmuk Batang"
ww_register_font gulim.ttf "Baekmuk Gulim"
ww_register_font dotum.ttf "Baekmuk Dotum"
ww_register_font hline.ttf "Baekmuk Headline"
}

#---------------------------------------------------------------------------------------

ww_download_binkw32()
{
ww_download 6a30900885390ef361dbb67444a7944143db36bf 'binkw32.zip' 'http://www.down-dll.com/dll/b/__32-binkw32.dll3.0.0.0.zip' '' 
}

ww_check_binkw32()
{
ww_native "$WW_SYSTEM32/binkw32.dll"
}

ww_install_binkw32()
{
ww_unzip "$WW_TEMP" "$WW_CACHE"/binkw32.zip
ww_cp "$WW_TEMP"/binkw32.dll "$WW_SYSTEM32"/binkw32.dll

ww_override native binkw32
}

#---------------------------------------------------------------------------------------

ww_download_cabinet()
{
ww_download f68594d1f578c3b47bf0639c46c11c5da161feee 'mdac27.exe' 'https://web.archive.org/web/20080731135848/http://download.microsoft.com/download/3/b/f/3bf74b01-16ba-472d-9a8c-42b2b4fa0d76/mdac_typ.exe' '' 
}

ww_check_cabinet()
{
ww_native "$WW_SYSTEM32/cabinet.dll"
}

ww_install_cabinet()
{
ww_cabextract -d "$WW_TEMP" "$WW_CACHE"/mdac27.exe
ww_cp "$WW_TEMP"/cabinet.dll "$WW_SYSTEM32"/cabinet.dll

ww_override native,builtin cabinet
}

#---------------------------------------------------------------------------------------

ww_download_cambria()
{
ww_download ab48a8ebac88219c84f293c6c1e81f1a0f420da6 'cam-const-cons.exe' 'http://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe' '' 
}

ww_check_cambria()
{
ww_exists "$WW_FONTS/cambria.ttc"
}

ww_install_cambria()
{
ww_cabextract -d "$WW_TEMP" -L -F ppviewer.cab "$WW_CACHE"/cam-const-cons.exe
ww_cabextract -d "$WW_FONTS" -L -F "CAMBRIA*.TT*" "$WW_TEMP"/ppviewer.cab
ww_register_font cambria.ttc "Cambria"
ww_register_font cambriab.ttf "Cambria Bold"
ww_register_font cambriai.ttf "Cambria Italic"
ww_register_font cambriaz.ttf "Cambria Bold Italic"
}

#---------------------------------------------------------------------------------------

ww_download_cjkfonts()
{
ww_download afdee34f700007de6ea87b43c92a88b7385ba65b 'baekmuk.tar.gz' 'http://http.debian.net/debian/pool/main/f/fonts-baekmuk/fonts-baekmuk_2.2.orig.tar.gz' '' 
ww_download 4f636d5c7c1bc16b96ea723adb16838cfb6df059 'takao.zip' 'http://launchpad.net/takao-fonts/trunk/003.02.01/+download/takao-fonts-ttf-003.02.01.zip' '' 
ww_download bb8a3960dc0a96aa305de28312ea8a0ab64123d2 'unifont.zip' 'http://unifoundry.com/unifont-5.1.20080907.zip' '' 
ww_download 28023041b22b6368bcfae076de68109b81e77976 'wenquanyi.tar.gz' 'http://downloads.sourceforge.net/wqy/wqy-microhei-0.2.0-beta.tar.gz' '' 
}

ww_check_cjkfonts()
{
false
}

ww_install_cjkfonts()
{
ww_install fakechinese
ww_install fakejapanese
ww_install fakekorean
ww_install unifont
}

#---------------------------------------------------------------------------------------

ww_download_cmd()
{
ww_download ac6e28cfd12942e74aa08bddf7715705edb85b6b 'cmd.exe' 'https://web.archive.org/web/20150526022037/http://download.microsoft.com/download/8/d/c/8dc79965-dfbc-4b25-9546-e23bc4b791c6/Q811493_W2K_SP4_X86_EN.exe' '' 'http://download.microsoft.com/download/8/d/c/8dc79965-dfbc-4b25-9546-e23bc4b791c6/Q811493_W2K_SP4_X86_EN.exe' '' 
}

ww_check_cmd()
{
ww_native "$WW_SYSTEM32/cmd.exe"
}

ww_install_cmd()
{
ww_cabextract -d "$WW_SYSTEM32" "$WW_CACHE/cmd.exe" -F cmd.exe
ww_override native,builtin cmd.exe
}

#---------------------------------------------------------------------------------------

ww_download_comctl32()
{
ww_download 94c3c494258cc54bd65d2f0153815737644bffde 'comctl32.exe' 'ftp://ftp.ie.debian.org/disk1/download.sourceforge.net/pub/sourceforge/p/po/pocmin/Win%2095_98%20Controls/Win%2095_98%20Controls/CC32inst.exe' '' 
}

ww_check_comctl32()
{
ww_native "$WW_SYSTEM32/comctl32.dll"
}

ww_install_comctl32()
{
ww_wine "$WW_CACHE"/comctl32.exe "/T:$WW_TEMP_WIN" /c $WW_UNATTENDED_SLASH_Q
ww_unzip "$WW_TEMP" "$WW_TEMP"/comctl32.exe
ww_wine "$WW_TEMP"/x86/50ComUpd.Exe "/T:$WW_TEMP_WIN" /c $WW_UNATTENDED_SLASH_Q
ww_cp "$WW_TEMP"/comcnt.dll "$WW_SYSTEM32"/comctl32.dll

ww_override native,builtin comctl32

ww_override_app winecfg.exe builtin comctl32
ww_override_app explorer.exe builtin comctl32
ww_override_app iexplore.exe builtin comctl32
}

#---------------------------------------------------------------------------------------

ww_download_comctl32ocx()
{
ww_download f52cf2034488235b37a1da837d1c40eb2a1bad84 'comctl32ocx.exe' 'http://download.microsoft.com/download/3/a/5/3a5925ac-e779-4b1c-bb01-af67dc2f96fc/VisualBasic6-KB896559-v1-ENU.exe' '' 
ww_download 766f9ccf8849a04d757faee379da54d635c8ac71 'mscomct2.cab' 'https://web.archive.org/web/20141012205821/http://activex.microsoft.com/controls/vb6/mscomct2.cab' '' 
}

ww_check_comctl32ocx()
{
ww_native "$WW_SYSTEM32/mscomctl.ocx"
}

ww_install_comctl32ocx()
{
ww_cabextract -d "$WW_TEMP" "$WW_CACHE"/comctl32ocx.exe
ww_try cp "$WW_TEMP"/mscomctl.ocx "$WW_SYSTEM32"/mscomctl.ocx
ww_try cp "$WW_TEMP"/comctl32.ocx "$WW_SYSTEM32"/comctl32.ocx
ww_regsvr comctl32.ocx
ww_regsvr mscomctl.ocx

ww_cabextract -d "$WW_TEMP" "$WW_CACHE"/mscomct2.cab
ww_try cp "$WW_TEMP"/mscomct2.ocx "$WW_SYSTEM32"/mscomct2.ocx
ww_regsvr mscomct2.ocx
}

#---------------------------------------------------------------------------------------

ww_download_comdlg32ocx()
{
ww_download d4f3e193c6180eccd73bad53a8500beb5b279cbf 'comdlg32ocx.cab' 'https://web.archive.org/web/20141227220748/http://activex.microsoft.com/controls/vb6/ComDlg32.cab' '' 
}

ww_check_comdlg32ocx()
{
ww_native "$WW_SYSTEM32/comdlg32.ocx"
}

ww_install_comdlg32ocx()
{
ww_cabextract -d "$WW_TEMP" "$WW_CACHE"/comdlg32ocx.cab
ww_try cp "$WW_TEMP"/comdlg32.ocx "$WW_SYSTEM32"/comdlg32.ocx
ww_regsvr comdlg32.ocx
}

#---------------------------------------------------------------------------------------

ww_download_consolas()
{
ww_download ab48a8ebac88219c84f293c6c1e81f1a0f420da6 'cam-const-cons.exe' 'http://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe' '' 
}

ww_check_consolas()
{
ww_exists "$WW_FONTS/consola.ttf"
}

ww_install_consolas()
{
ww_cabextract -d "$WW_TEMP" -L -F ppviewer.cab "$WW_CACHE"/cam-const-cons.exe
ww_cabextract -d "$WW_FONTS" -L -F 'CONSOL*.TTF' "$WW_TEMP"/ppviewer.cab
ww_register_font consola.ttf "Consoleas"
ww_register_font consolab.ttf "Consoleas Bold"
ww_register_font consolai.ttf "Consoleas Italic"
ww_register_font consolaz.ttf "Consoleas Bold Italic"
}

#---------------------------------------------------------------------------------------

ww_download_constantia()
{
ww_download ab48a8ebac88219c84f293c6c1e81f1a0f420da6 'cam-const-cons.exe' 'http://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe' '' 
}

ww_check_constantia()
{
ww_exists "$WW_FONTS/constan.ttf"
}

ww_install_constantia()
{
ww_cabextract -d "$WW_TEMP" -L -F ppviewer.cab "$WW_CACHE"/cam-const-cons.exe
ww_cabextract -d "$WW_FONTS" -L -F 'CONSTAN*.TTF' "$WW_TEMP"/ppviewer.cab
ww_register_font constan.ttf "Constantia"
ww_register_font constanb.ttf "Constantia Bold"
ww_register_font constani.ttf "Constantia Italic"
ww_register_font constanz.ttf "Constantia Bold Italic"
}

#---------------------------------------------------------------------------------------

ww_download_corefonts()
{
ww_download 6d75f8436f39ab2da5c31ce651b7443b4ad2916e 'arial32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/arial32.exe' '' 
ww_download d45cdab84b7f4c1efd6d1b369f50ed0390e3d344 'arialb32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/arialb32.exe' '' 
ww_download 2371d0327683dcc5ec1684fe7c275a8de1ef9a51 'comic32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/comic32.exe' '' 
ww_download 06a745023c034f88b4135f5e294fece1a3c1b057 'courie32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/courie32.exe' '' 
ww_download 90e4070cb356f1d811acb943080bf97e419a8f1e 'georgi32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/georgi32.exe' '' 
ww_download 86b34d650cfbbe5d3512d49d2545f7509a55aad2 'impact32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/impact32.exe' '' 
ww_download 20b79e65cdef4e2d7195f84da202499e3aa83060 'times32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/times32.exe' '' 
ww_download 50aab0988423efcc9cf21fac7d64d534d6d0a34a 'trebuc32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/trebuc32.exe' '' 
ww_download f5b93cedf500edc67502f116578123618c64a42a 'verdan32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/verdan32.exe' '' 
ww_download 2fb4a42c53e50bc70707a7b3c57baf62ba58398f 'webdin32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/webdin32.exe' '' 
}

ww_check_corefonts()
{
ww_exists "$WW_FONTS/Arial.TTF"
}

ww_install_corefonts()
{
ww_cabextract -q -d "$WW_TEMP" "$WW_CACHE"/arial32.exe
ww_cp "$WW_TEMP"/Arial*.TTF "$WW_FONTS"
ww_register_font Arial.TTF "Arial"
ww_register_font Arialbd.TTF "Arial Bold"
ww_register_font Arialbi.TTF "Arial Bold Italic"
ww_register_font Ariali.TTF "Arial Italic"

ww_cabextract -q -d "$WW_TEMP" "$WW_CACHE"/arialb32.exe
ww_cp "$WW_TEMP"/AriBlk.TTF "$WW_FONTS"
ww_register_font AriBlk.TTF "Arial Black"

ww_cabextract -q -d "$WW_TEMP" "$WW_CACHE"/comic32.exe
ww_cp "$WW_TEMP"/Comic*.TTF "$WW_FONTS"
ww_register_font Comic.TTF "Comic Sans MS"
ww_register_font Comicbd.TTF "Comic Sans MS Bold"

ww_cabextract -q -d "$WW_TEMP" "$WW_CACHE"/courie32.exe
ww_cp "$WW_TEMP"/cour*.ttf "$WW_FONTS"
ww_register_font Cour.TTF "Courier New"
ww_register_font CourBD.TTF "Courier New Bold"
ww_register_font CourBI.TTF "Courier New Bold Italic"
ww_register_font Couri.TTF "Courier New Italic"

ww_cabextract -q -d "$WW_TEMP" "$WW_CACHE"/georgi32.exe
ww_cp "$WW_TEMP"/Georgia*.TTF "$WW_FONTS"
ww_register_font Georgia.TTF "Georgia"
ww_register_font Georgiab.TTF "Georgia Bold"
ww_register_font Georgiaz.TTF "Georgia Bold Italic"
ww_register_font Georgiai.TTF "Georgia Italic"

ww_cabextract -q -d "$WW_TEMP" "$WW_CACHE"/impact32.exe
ww_cp "$WW_TEMP"/Impact.TTF "$WW_FONTS"
ww_register_font Impact.TTF "Impact"

ww_cabextract -q -d "$WW_TEMP" "$WW_CACHE"/times32.exe
ww_cp "$WW_TEMP"/Times*.TTF "$WW_FONTS"
ww_register_font Times.TTF "Times New Roman"
ww_register_font Timesbd.TTF "Times New Roman Bold"
ww_register_font Timesbi.TTF "Times New Roman Bold Italic"
ww_register_font Timesi.TTF "Times New Roman Italic"

ww_cabextract -q -d "$WW_TEMP" "$WW_CACHE"/trebuc32.exe
ww_cp "$WW_TEMP"/[tT]rebuc*.ttf "$WW_FONTS"
ww_register_font Trebuc.TTF "Trebucet MS"
ww_register_font Trebucbd.TTF "Trebucet MS Bold"
ww_register_font Trebucbi.TTF "Trebucet MS Bold Italic"
ww_register_font Trebucit.TTF "Trebucet MS Italic"

ww_cabextract -q -d "$WW_TEMP" "$WW_CACHE"/verdan32.exe
ww_cp "$WW_TEMP"/Verdana*.TTF "$WW_FONTS"
ww_register_font Verdana.TTF "Verdana"
ww_register_font Verdanab.TTF "Verdana Bold"
ww_register_font Verdanaz.TTF "Verdana Bold Italic"
ww_register_font Verdanai.TTF "Verdana Italic"

ww_cabextract -q -d "$WW_TEMP" "$WW_CACHE"/webdin32.exe
ww_cp "$WW_TEMP"/Webdings.TTF "$WW_FONTS"
ww_register_font Webdings.TTF "Webdings"
}

#---------------------------------------------------------------------------------------

ww_download_crypt32()
{
ww_download fadea6d94a014b039839fecc6e6a11c20afa4fa8 'win2ksp4.exe' 'ftp://ftp.vcitynet.com/win32/win2k/W2KSP4_EN.EXE' '' 'http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 'https://web.archive.org/web/20160129053851/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 
ww_download c81472f7eeea2eca421e116cd4c03e2300ebfde4 'xpsp3.exe' 'https://web.archive.org/web/20150811102120/http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://mail.digipro.rs/Public/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://soporte.uson.mx/UTILES/04_SERVICE_PACKS/Windows/XP/SP3/ingles/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://ftp.sae24.ru/tools/System/M%24win_SP/xp_sp3/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 
}

ww_check_crypt32()
{
ww_native "$WW_SYSTEM32/crypt32.dll"
}

ww_install_crypt32()
{
ww_install msasn1

ww_xpsp3_helper i386/crypt32.dl_
ww_cabextract -d "$WW_SYSTEM32" "$WW_TEMP"/i386/crypt32.dl_

ww_override native crypt32
}

#---------------------------------------------------------------------------------------

ww_download_d3dcompiler_43()
{
ww_dx_jun2010_download
}

ww_check_d3dcompiler_43()
{
ww_native "$WW_SYSTEM32/d3dcompiler_43.dll"
}

ww_install_d3dcompiler_43()
{
dllname=d3dcompiler_43

ww_cabextract -d "$WW_TEMP" -L -F "*$dllname*x86*" "$WW_DX_JUN_PATH"
for x in "$WW_TEMP"/*.cab
do
  ww_cabextract -d "$WW_SYSTEM32" -L -F "$dllname.dll" "$x"
done

ww_override native $dllname
}

#---------------------------------------------------------------------------------------

ww_download_d3drm()
{
ww_dx_feb2010_download
}

ww_check_d3drm()
{
ww_native "$WW_SYSTEM32/d3drm.dll"
}

ww_install_d3drm()
{
ww_cabextract -d "$WW_TEMP" -L -F "dxnt.cab" "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F "d3drm.dll" "$WW_TEMP/dxnt.cab"

ww_override native d3drm
}

#---------------------------------------------------------------------------------------

ww_download_d3dx10()
{
ww_dx_jun2010_download
}

ww_check_d3dx10()
{
ww_native "$WW_SYSTEM32/d3dx10_33.dll"
}

ww_install_d3dx10()
{
ww_cabextract -d "$WW_TEMP" -L -F '*d3dx10*x86*' "$WW_DX_JUN_PATH"

for x in "$WW_TEMP"/*.cab
do
    ww_cabextract -d "$WW_SYSTEM32" -L -F 'd3dx10*.dll' "$x"
done

ww_override native d3dx10_33 d3dx10_34 d3dx10_35 d3dx10_36 d3dx10_37
ww_override native d3dx10_38 d3dx10_39 d3dx10_40 d3dx10_41 d3dx10_42 d3dx10_43
}

#---------------------------------------------------------------------------------------

ww_download_d3dx10_43()
{
ww_dx_jun2010_download
}

ww_check_d3dx10_43()
{
ww_native "$WW_SYSTEM32/d3dx10_43.dll"
}

ww_install_d3dx10_43()
{
dllname=d3dx10_43
ww_cabextract -d "$WW_TEMP" -L -F "*$dllname*x86*" "$WW_DX_JUN_PATH"
for x in "$WW_TEMP"/*.cab
do
    ww_cabextract -d "$WW_SYSTEM32" -L -F "$dllname.dll" "$x"
done
ww_override native $dllname
}

#---------------------------------------------------------------------------------------

ww_download_d3dx11_42()
{
ww_dx_jun2010_download
}

ww_check_d3dx11_42()
{
ww_native "$WW_SYSTEM32/d3dx11_42.dll"
}

ww_install_d3dx11_42()
{
dllname=d3dx11_42

ww_cabextract -d "$WW_TEMP" -L -F "*$dllname*x86*" "$WW_DX_JUN_PATH"

for x in "$WW_TEMP"/*.cab
do
  ww_cabextract -d "$WW_SYSTEM32" -L -F "$dllname.dll" "$x"
done

ww_override native $dllname
}

#---------------------------------------------------------------------------------------

ww_download_d3dx11_43()
{
ww_dx_jun2010_download
}

ww_check_d3dx11_43()
{
ww_native "$WW_SYSTEM32/d3dx11_43.dll"
}

ww_install_d3dx11_43()
{
dllname=d3dx11_43

ww_cabextract -d "$WW_TEMP" -L -F "*$dllname*x86*" "$WW_DX_JUN_PATH"

for x in "$WW_TEMP"/*.cab
do
  ww_cabextract -d "$WW_SYSTEM32" -L -F "$dllname.dll" "$x"
done

ww_override native $dllname
}

#---------------------------------------------------------------------------------------

ww_download_d3dx9()
{
ww_dx_jun2010_download
}

ww_check_d3dx9()
{
ww_native "$WW_SYSTEM32/d3dx9_43.dll"
}

ww_install_d3dx9()
{
ww_cabextract -d "$WW_TEMP" -L -F '*d3dx9*x86*' "$WW_DX_FEB_PATH"
for x in "$WW_TEMP"/*.cab
do
    ww_cabextract -d "$WW_SYSTEM32" -L -F 'd3dx9*.dll' "$x"
done
ww_override native d3dx9_24 d3dx9_25 d3dx9_26 d3dx9_27 d3dx9_28 d3dx9_29 d3dx9_30
ww_override native d3dx9_31 d3dx9_32 d3dx9_33 d3dx9_34 d3dx9_35 d3dx9_36 d3dx9_37
ww_override native d3dx9_38 d3dx9_39 d3dx9_40 d3dx9_41 d3dx9_42 d3dx9_43
}

#---------------------------------------------------------------------------------------

ww_download_d3dx9_26()
{
ww_dx_feb2010_download
}

ww_check_d3dx9_26()
{
ww_native "$WW_SYSTEM32/d3dx9_26.dll"
}

ww_install_d3dx9_26()
{
ww_d3dx_helper d3dx9_26
}

#---------------------------------------------------------------------------------------

ww_download_d3dx9_28()
{
ww_dx_feb2010_download
}

ww_check_d3dx9_28()
{
ww_native "$WW_SYSTEM32/d3dx9_28.dll"
}

ww_install_d3dx9_28()
{
ww_d3dx_helper d3dx9_28
}

#---------------------------------------------------------------------------------------

ww_download_d3dx9_31()
{
ww_dx_feb2010_download
}

ww_check_d3dx9_31()
{
ww_native "$WW_SYSTEM32/d3dx9_31.dll"
}

ww_install_d3dx9_31()
{
ww_d3dx_helper d3dx9_31
}

#---------------------------------------------------------------------------------------

ww_download_d3dx9_35()
{
ww_dx_feb2010_download
}

ww_check_d3dx9_35()
{
ww_native "$WW_SYSTEM32/d3dx9_35.dll"
}

ww_install_d3dx9_35()
{
ww_d3dx_helper d3dx9_35
}

#---------------------------------------------------------------------------------------

ww_download_d3dx9_36()
{
ww_dx_feb2010_download
}

ww_check_d3dx9_36()
{
ww_native "$WW_SYSTEM32/d3dx9_36.dll"
}

ww_install_d3dx9_36()
{
ww_d3dx_helper d3dx9_36
}

#---------------------------------------------------------------------------------------

ww_download_d3dx9_39()
{
ww_dx_feb2010_download
}

ww_check_d3dx9_39()
{
ww_native "$WW_SYSTEM32/d3dx9_39.dll"
}

ww_install_d3dx9_39()
{
ww_d3dx_helper d3dx9_39
}

#---------------------------------------------------------------------------------------

ww_download_d3dx9_42()
{
ww_dx_feb2010_download
}

ww_check_d3dx9_42()
{
ww_native "$WW_SYSTEM32/d3dx9_42.dll"
}

ww_install_d3dx9_42()
{
ww_d3dx_helper d3dx9_42
}

#---------------------------------------------------------------------------------------

ww_download_d3dx9_43()
{
ww_dx_jun2010_download
}

ww_check_d3dx9_43()
{
ww_native "$WW_SYSTEM32/d3dx9_43.dll"
}

ww_install_d3dx9_43()
{
dllname=d3dx9_43

ww_cabextract -d "$WW_TEMP" -L -F "*$dllname*x86*" "$WW_DX_JUN_PATH"
for x in "$WW_TEMP"/*.cab
do
  ww_cabextract -d "$WW_SYSTEM32" -L -F "$dllname.dll" "$x"
done

ww_override native $dllname
}

#---------------------------------------------------------------------------------------

ww_download_d3dxof()
{
ww_dx_feb2010_download
}

ww_check_d3dxof()
{
ww_native "$WW_SYSTEM32/d3dxof.dll"
}

ww_install_d3dxof()
{
ww_cabextract -d "$WW_TEMP" -L -F 'dxnt.cab' "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'd3dxof.dll' "$WW_TEMP/dxnt.cab"

ww_override native d3dxof
}

#---------------------------------------------------------------------------------------

ww_download_dbghelp()
{
ww_download c81472f7eeea2eca421e116cd4c03e2300ebfde4 'xpsp3.exe' 'https://web.archive.org/web/20150811102120/http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://mail.digipro.rs/Public/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://soporte.uson.mx/UTILES/04_SERVICE_PACKS/Windows/XP/SP3/ingles/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://ftp.sae24.ru/tools/System/M%24win_SP/xp_sp3/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 
}

ww_check_dbghelp()
{
ww_native "$WW_SYSTEM32/dbghelp.dll"
}

ww_install_dbghelp()
{
ww_xpsp3_helper i386/dbghelp.dll

ww_cp "$WW_TEMP"/i386/dbghelp.dll "$WW_SYSTEM32"

ww_override native dbghelp
}

#---------------------------------------------------------------------------------------

ww_download_ddr_gdi()
{
:
}

ww_check_ddr_gdi()
{
false
}

ww_install_ddr_gdi()
{
ww_set_wined3d_var DirectDrawRenderer gdi
}

#---------------------------------------------------------------------------------------

ww_download_ddr_opengl()
{
:
}

ww_check_ddr_opengl()
{
false
}

ww_install_ddr_opengl()
{
ww_set_wined3d_var DirectDrawRenderer opengl
}

#---------------------------------------------------------------------------------------

ww_download_desktop_mode()
{
:
}

ww_check_desktop_mode()
{
false
}

ww_install_desktop_mode()
{
ww_set_virtual_desktop on "$WW_SCREEN_RES"
}

#---------------------------------------------------------------------------------------

ww_download_devenum()
{
ww_dx_feb2010_download
}

ww_check_devenum()
{
ww_native "$WW_SYSTEM32/devenum.dll"
}

ww_install_devenum()
{
ww_cabextract -d "$WW_TEMP" -L -F 'dxnt.cab' "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'devenum.dll' "$WW_TEMP/dxnt.cab"
ww_regsvr devenum.dll
ww_override native devenum
}

#---------------------------------------------------------------------------------------

ww_download_dinput()
{
ww_dx_feb2010_download
}

ww_check_dinput()
{
ww_native "$WW_SYSTEM32/dinput.dll"
}

ww_install_dinput()
{
ww_cabextract -d "$WW_TEMP" -L -F 'dxnt.cab' "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dinput.dll' "$WW_TEMP/dxnt.cab"
ww_regsvr dinput
ww_override native dinput
}

#---------------------------------------------------------------------------------------

ww_download_dinput8()
{
ww_dx_feb2010_download
}

ww_check_dinput8()
{
ww_native "$WW_SYSTEM32/dinput8.dll"
}

ww_install_dinput8()
{
ww_cabextract -d "$WW_TEMP" -L -F 'dxnt.cab' "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dinput8.dll' "$WW_TEMP/dxnt.cab"
ww_regsvr dinput8
ww_override native dinput8
}

#---------------------------------------------------------------------------------------

ww_download_dirac()
{
ww_download b3981b13fbc45823131f69d125992d6330212f27 'ahk.zip' 'http://www.autohotkey.com/download/AutoHotkey104805.zip' '' 
ww_download c912d30a8fa500c7841444559feb1f49301611c4 'dirac.exe' 'http://downloads.sourceforge.net/dirac/DiracDirectShowFilter-1.0.2.exe' '' 
ww_download 470640aa4bb7db8e69196b5edb0010933569e98d 'vcrun2008.exe' 'http://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe' '' 
}

ww_check_dirac()
{
ww_native "$WW_PROGRAM_FILES/Dirac/DiracDecoder.dll"
}

ww_install_dirac()
{
ww_install vcrun2008

ww_cd_repo
ww_ahk "
    SetTitleMatchMode, 2
    run dirac.exe
    WinWait, Dirac, Welcome
    ControlClick, Button2
    WinWait, Dirac, License
    ControlClick, Button2
    WinWait, Dirac, Location
    ControlClick, Button2
    WinWait, Dirac, Components
    ControlClick, Button2
    WinWait, Dirac, environment
    ControlCLick, Button1
    WinWait, Dirac, installed
    ControlClick, Button2
    WinWaitClose
"
}

#---------------------------------------------------------------------------------------

ww_download_directmusic()
{
ww_dx_feb2010_download
}

ww_check_directmusic()
{
ww_native "$WW_SYSTEM32/dmusic.dll"
}

ww_install_directmusic()
{
ww_install "dsound"

ww_cabextract -d "$WW_TEMP" -L -F dxnt.cab "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'devenum.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dmband.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dmcompos.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dmime.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dmloader.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dmscript.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dmstyle.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dmsynth.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dmusic.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dmusic32.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dswave.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'streamci.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'quartz.dll' "$WW_TEMP/dxnt.cab"

ww_regsvr devenum.dll
ww_regsvr dmband.dll
ww_regsvr dmcompos.dll
ww_regsvr dmime.dll
ww_regsvr dmloader.dll
ww_regsvr dmscript.dll
ww_regsvr dmstyle.dll
ww_regsvr dmsynth.dll
ww_regsvr dmusic.dll
ww_regsvr dswave.dll
ww_regsvr quartz.dll

ww_override native devenum dmband dmcompos dmime dmloader dmscript dmstyle dmsynth dmusic dmusic32 dswave streamci quartz
}

#---------------------------------------------------------------------------------------

ww_download_directplay()
{
ww_dx_feb2010_download
}

ww_check_directplay()
{
ww_native "$WW_SYSTEM32/dplayx.dll"
}

ww_install_directplay()
{
ww_cabextract -d "$WW_TEMP" -L -F dxnt.cab "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dplaysvr.exe' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dplayx.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dpnet.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dpnhpast.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dpnsvr.exe' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dpwsockx.dll' "$WW_TEMP/dxnt.cab"

ww_override native dplayx dpnet dpnhpast dpnsvr.exe dpwsockx

ww_regsvr dplayx.dll
ww_regsvr dpnet.dll
ww_regsvr dpnhpast.dll
}

#---------------------------------------------------------------------------------------

ww_download_directx9()
{
ww_dx_feb2010_download
}

ww_check_directx9()
{
ww_native "$WW_SYSTEM32/d3dx10_33.dll"
}

ww_install_directx9()
{
ww_warn "You probably shouldn't be using this. d3dx9 or, better, d3dx9_36 usually suffice."

ww_set_winver winxp

ww_cd_repo
WINEDLLOVERRIDES="wintrust=b,mscoree=,ddraw,d3d8,d3d9,dsound,dinput=n" \
    ww_wine directx9.feb2010.exe /t:"$WW_TEMP_WIN" $WW_UNATTENDED_SLASH_Q

ww_override native d3dim d3drm d3dx8 d3dx9_24 d3dx9_25 d3dx9_26 d3dx9_27 d3dx9_28 d3dx9_29
ww_override native d3dx9_30 d3dx9_31 d3dx9_32 d3dx9_33 d3dx9_34 d3dx9_35 d3dx9_36 d3dx9_37
ww_override native d3dx9_38 d3dx9_39 d3dx9_40 d3dx9_41 d3dx9_42 d3dx9_43 d3dxof
ww_override native dciman32 ddrawex devenum dmband dmcompos dmime dmloader dmscript dmstyle
ww_override native dmsynth dmusic dmusic32 dnsapi dplay dplayx dpnaddr dpnet dpnhpast dpnlobby
ww_override native dswave dxdiagn msdmo qcap quartz streamci
ww_override native dxdiag.exe
ww_override builtin d3d8 d3d9 dinput dinput8 dsound

ww_wine "$WW_TEMP_WIN"\\DXSETUP.exe $WW_UNATTENDED_SLASH_SILENT
}

#---------------------------------------------------------------------------------------

ww_download_disable_d3dx11_42()
{
:
}

ww_check_disable_d3dx11_42()
{
false
}

ww_install_disable_d3dx11_42()
{
ww_override disabled d3dx11_42
}

#---------------------------------------------------------------------------------------

ww_download_disable_d3dx11_43()
{
:
}

ww_check_disable_d3dx11_43()
{
false
}

ww_install_disable_d3dx11_43()
{
ww_override disabled d3dx11_43
}

#---------------------------------------------------------------------------------------

ww_download_dmsynth()
{
ww_dx_feb2010_download
}

ww_check_dmsynth()
{
ww_native "$WW_SYSTEM32/dmsynth.dll"
}

ww_install_dmsynth()
{
ww_cabextract -d "$WW_TEMP" -L -F dxnt.cab "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dmsynth.dll' "$WW_TEMP/dxnt.cab"

ww_regsvr dmsynth.dll

ww_override native dmsynth
}

#---------------------------------------------------------------------------------------

ww_download_dotnet11()
{
ww_download b3981b13fbc45823131f69d125992d6330212f27 'ahk.zip' 'http://www.autohotkey.com/download/AutoHotkey104805.zip' '' 
ww_download 6d75f8436f39ab2da5c31ce651b7443b4ad2916e 'arial32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/arial32.exe' '' 
ww_download d45cdab84b7f4c1efd6d1b369f50ed0390e3d344 'arialb32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/arialb32.exe' '' 
ww_download 2371d0327683dcc5ec1684fe7c275a8de1ef9a51 'comic32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/comic32.exe' '' 
ww_download 06a745023c034f88b4135f5e294fece1a3c1b057 'courie32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/courie32.exe' '' 
ww_download 16a354a2207c4c8846b617cbc78f7b7c1856340e 'dotnet11.exe' 'http://download.microsoft.com/download/a/a/c/aac39226-8825-44ce-90e3-bf8203e74006/dotnetfx.exe' '' 
ww_download 90e4070cb356f1d811acb943080bf97e419a8f1e 'georgi32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/georgi32.exe' '' 
ww_download 86b34d650cfbbe5d3512d49d2545f7509a55aad2 'impact32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/impact32.exe' '' 
ww_download 20b79e65cdef4e2d7195f84da202499e3aa83060 'times32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/times32.exe' '' 
ww_download 50aab0988423efcc9cf21fac7d64d534d6d0a34a 'trebuc32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/trebuc32.exe' '' 
ww_download f5b93cedf500edc67502f116578123618c64a42a 'verdan32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/verdan32.exe' '' 
ww_download 2fb4a42c53e50bc70707a7b3c57baf62ba58398f 'webdin32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/webdin32.exe' '' 
}

ww_check_dotnet11()
{
ww_exists "$WW_WINDOWS/Microsoft.NET/Framework/v1.1.4322/ndpsetup.ico"
}

ww_install_dotnet11()
{
ww_remove_mono
ww_install corefonts
ww_fontfix

ww_cd_repo
WINEDLLOVERRIDES="winemenubuilder.exe=n;regsvcs.exe=b" ww_ahk "
SetTitleMatchMode, 2
run, dotnet11.exe /q /C:\"install /q\"

Loop
{
    sleep 1000
    ifwinexist, Fatal error, Failed to delay load library
    {
        WinClose, Fatal error, Failed to delay load library
        continue
    }
    Process, exist, dotnetfx.exe
    dotnet_pid = %ErrorLevel%  ; Save the value immediately since ErrorLevel is often changed.
    if dotnet_pid = 0
    {
        break
    }
}
"
}

#---------------------------------------------------------------------------------------

ww_download_dotnet11sp1()
{
ww_download b3981b13fbc45823131f69d125992d6330212f27 'ahk.zip' 'http://www.autohotkey.com/download/AutoHotkey104805.zip' '' 
ww_download 6d75f8436f39ab2da5c31ce651b7443b4ad2916e 'arial32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/arial32.exe' '' 
ww_download d45cdab84b7f4c1efd6d1b369f50ed0390e3d344 'arialb32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/arialb32.exe' '' 
ww_download 2371d0327683dcc5ec1684fe7c275a8de1ef9a51 'comic32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/comic32.exe' '' 
ww_download 06a745023c034f88b4135f5e294fece1a3c1b057 'courie32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/courie32.exe' '' 
ww_download 16a354a2207c4c8846b617cbc78f7b7c1856340e 'dotnet11.exe' 'http://download.microsoft.com/download/a/a/c/aac39226-8825-44ce-90e3-bf8203e74006/dotnetfx.exe' '' 
ww_download 74a5b25d65a70b8ecd6a9c301a0aea10d8483a23 'dotnet11sp1.exe' 'http://download.microsoft.com/download/8/b/4/8b4addd8-e957-4dea-bdb8-c4e00af5b94b/NDP1.1sp1-KB867460-X86.exe' '' 
ww_download 90e4070cb356f1d811acb943080bf97e419a8f1e 'georgi32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/georgi32.exe' '' 
ww_download 86b34d650cfbbe5d3512d49d2545f7509a55aad2 'impact32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/impact32.exe' '' 
ww_download 20b79e65cdef4e2d7195f84da202499e3aa83060 'times32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/times32.exe' '' 
ww_download 50aab0988423efcc9cf21fac7d64d534d6d0a34a 'trebuc32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/trebuc32.exe' '' 
ww_download f5b93cedf500edc67502f116578123618c64a42a 'verdan32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/verdan32.exe' '' 
ww_download 2fb4a42c53e50bc70707a7b3c57baf62ba58398f 'webdin32.exe' 'ftp://ftp.fi.debian.org/gentoo/distfiles/webdin32.exe' '' 
}

ww_check_dotnet11sp1()
{
ww_exists "$WW_WINDOWS/Microsoft.NET/Framework/v1.1.4322/CONFIG/web_hightrust.config.default"
}

ww_install_dotnet11sp1()
{
ww_remove_mono
ww_install dotnet11

ww_cd_repo
WINEDLLOVERRIDES="winemenubuilder.exe=n;regsvcs.exe=b" ww_ahk "
SetTitleMatchMode, 2
run, dotnet11sp1.exe /q /C:"install /q"

Loop
{
    sleep 1000
    ifwinexist, Fatal error, Failed to delay load library
    {
        WinClose, Fatal error, Failed to delay load library
        continue
    }
    Process, exist, dotnetfx.exe
    dotnet_pid = %ErrorLevel%
    if dotnet_pid = 0
    {
        break
    }
}
"
}

#---------------------------------------------------------------------------------------

ww_download_dotnet20()
{
ww_download a3625c59d7a2995fb60877b5f5324892a1693b2a 'dotnet20.exe' 'http://download.lenovo.com/ibmdl/pub/pc/pccbbs/thinkvantage_en/dotnetfx.exe' '' 
}

ww_check_dotnet20()
{
ww_native "$WW_WINDOWS/Microsoft.NET/Framework/v2.0.50727/Microsoft .NET Framework 2.0/install.exe"
}

ww_install_dotnet20()
{
ww_remove_mono
ww_fontfix
ww_set_winver win2k
if ww_workaround_wine_bug 34803
then
    wine reg delete 'HKLM\Software\Microsoft\.NETFramework\v2.0.50727\SBSDisabled' /f
fi
ww_cd_repo
ww_try wine dotnet20.exe /q /c:"install.exe /q"
ww_unset_winver
rm -f "$WW_SYSTEM32"/msvc?80.dll
}

#---------------------------------------------------------------------------------------

ww_download_dotnet20sp1()
{
ww_download a3625c59d7a2995fb60877b5f5324892a1693b2a 'dotnet20.exe' 'http://download.lenovo.com/ibmdl/pub/pc/pccbbs/thinkvantage_en/dotnetfx.exe' '' 
ww_download eef5a36924cdf0c02598ccf96aa4f60887a49840 'dotnet20sp1.exe' 'http://download.microsoft.com/download/0/8/c/08c19fa4-4c4f-4ffb-9d6c-150906578c9e/NetFx20SP1_x86.exe' '' 
}

ww_check_dotnet20sp1()
{
ww_native "$WW_WINDOWS/winsxs/manifests/x86_Microsoft.VC80.CRT_1fc8b3b9a1e18e3b_8.0.50727.1433_x-ww_5cf844d2.cat"
}

ww_install_dotnet20sp1()
{
ww_remove_mono

ww_install dotnet20

WINEDLLOVERRIDES="winemenubuilder.exe=n"
ww_warn "Setting windows version so installer works"

wineserver -k
ww_set_winver win2k
wineserver -w
WINEDLLOVERRIDES="winemenubuilder.exe=n;ngen.exe,regsvcs.exe,mscorsvw.exe=b"
export WINEDLLOVERRIDES

wine reg add "HKLM\\Software\\Microsoft\\NET Framework Setup\\NDP\\v2.0.50727" /v Version /t REG_SZ /d "2.0.50727" /f

ww_cd_repo
wine dotnet20sp1.exe /q
status=$?

case $status in
    0) ;;
    105) echo "Exit status $status - normal, user selected 'restart now'" ;;
    194) echo "Exit status $status - normal, user selected 'restart later'" ;;
    *) ww_die "Exit status $status - dotnet20sp1 installation failed" ;;
esac

rm -f "$WW_SYSTEM32"/msvc?80.dll

ww_unset_winver
}

#---------------------------------------------------------------------------------------

ww_download_dotnet20sp2()
{
ww_download b3981b13fbc45823131f69d125992d6330212f27 'ahk.zip' 'http://www.autohotkey.com/download/AutoHotkey104805.zip' '' 
ww_download a3625c59d7a2995fb60877b5f5324892a1693b2a 'dotnet20.exe' 'http://download.lenovo.com/ibmdl/pub/pc/pccbbs/thinkvantage_en/dotnetfx.exe' '' 
ww_download 22d776d4d204863105a5db99e8b8888be23c61a7 'dotnet20sp2.exe' 'http://download.microsoft.com/download/c/6/e/c6e88215-0178-4c6c-b5f3-158ff77b1f38/NetFx20SP2_x86.exe' '' 
}

ww_check_dotnet20sp2()
{
ww_exists "$WW_WINDOWS/winsxs/manifests/x86_Microsoft.VC80.CRT_1fc8b3b9a1e18e3b_8.0.50727.3053_x-ww_b80fa8ca.cat"
}

ww_install_dotnet20sp2()
{
ww_remove_mono

ww_install dotnet20

if ww_workaround_wine_bug 34803
then
    wine reg delete 'HKLM\Software\Microsoft\.NETFramework\v2.0.50727\SBSDisabled' /f
fi

ww_cd_repo
ww_ahk "
    SetTitleMatchMode, 2
    run, dotnet20sp2.exe /q /c:"install.exe /q"

    Loop
    {
        sleep 1000
        ifwinexist,, cannot be uninstalled
        {
            WinClose,, cannot be uninstalled
            continue
        }
        Process, exist, NetFx20SP2_x86.exe
        dotnet_pid = %ErrorLevel%
        if dotnet_pid = 0
        {
            break
        }
    }
"
status=$?

case $status in
    0) ;;
    105) echo "Exit status $status - normal, user selected 'restart now'" ;;
    194) echo "Exit status $status - normal, user selected 'restart later'" ;;
    *) ww_die "Exit status $status - dotnet20sp2 installation failed" ;;
esac

ww_unset_winver
}

#---------------------------------------------------------------------------------------

ww_download_dotnet30()
{
ww_download a3625c59d7a2995fb60877b5f5324892a1693b2a 'dotnet20.exe' 'http://download.lenovo.com/ibmdl/pub/pc/pccbbs/thinkvantage_en/dotnetfx.exe' '' 
ww_download f3d2c3c7e4c0c35450cf6dab1f9f2e9e7ff50039 'dotnet30.exe' 'ftp://ftp.kworld.com.tw/kworld/temp/Framework/dotnetfx3.exe' '' 
}

ww_check_dotnet30()
{
ww_exists "$WW_WINDOWS/Microsoft.NET/Framework/v3.0/Microsoft .NET Framework 3.0/logo.bmp"
}

ww_install_dotnet30()
{
ww_remove_mono

if test -f /proc/sys/kernel/yama/ptrace_scope
then
    case `cat /proc/sys/kernel/yama/ptrace_scope` in
    0) ;;
    *) ww_warn "If install fails, set /proc/sys/kernel/yama/ptrace_scope to 0. See http://bugs.winehq.org/show_bug.cgi?id=30410" ;;
    esac
fi

ww_install dotnet20

ww_warn "Installing .net 3.0 runtime takes 3 minutes on a very fast machine, and the Finished dialog may hide in the taskbar."

LANGPACKS_BASE_PATH="$WW_WINDOWS/SYSMSICache/Framework/v3.0"
test -d "${LANGPACKS_BASE_PATH}" || mkdir -p "${LANGPACKS_BASE_PATH}"
for lang in ar cs da de el es 'fi' fr he it jp ko nb nl pl pt-BR pt-PT ru \
            sv tr zh-CHS zh-CHT
do
    ln -sf "${WW_SYSTEM32}/spupdsvc.exe" "${LANGPACKS_BASE_PATH}/dotnetfx3langpack${lang}.exe"
done

ww_set_winver winxp

wine sc delete "FontCache3.0.0.0"

WINEDLLOVERRIDES="winemenubuilder.exe=n;ngen.exe,mscorsvw.exe=b;$WINEDLLOVERRIDES"

ww_cd_repo
wine dotnet30.exe /q /c:"install.exe /q"
}

#---------------------------------------------------------------------------------------

ww_download_dotnet30sp1()
{
ww_download a3625c59d7a2995fb60877b5f5324892a1693b2a 'dotnet20.exe' 'http://download.lenovo.com/ibmdl/pub/pc/pccbbs/thinkvantage_en/dotnetfx.exe' '' 
ww_download eef5a36924cdf0c02598ccf96aa4f60887a49840 'dotnet20sp1.exe' 'http://download.microsoft.com/download/0/8/c/08c19fa4-4c4f-4ffb-9d6c-150906578c9e/NetFx20SP1_x86.exe' '' 
ww_download f3d2c3c7e4c0c35450cf6dab1f9f2e9e7ff50039 'dotnet30.exe' 'ftp://ftp.kworld.com.tw/kworld/temp/Framework/dotnetfx3.exe' '' 
ww_download 8d779e337920b097aa0c01859912950606e9fc12 'dotnet30sp1.exe' 'http://download.microsoft.com/download/8/F/E/8FEEE89D-9E4F-4BA3-993E-0FFEA8E21E1B/NetFx30SP1_x86.exe' '' 
ww_download 5d332ebd1025e294adafe72030fe33db707b2c82 'dotnet30sp1.xpsep.msi' 'http://download.microsoft.com/download/2/5/2/2526f55d-32bc-410f-be18-164ba67ae07d/XPSEP%20XP%20and%20Server%202003%2032%20bit.msi' '' 
}

ww_check_dotnet30sp1()
{
ww_native "$WW_SYSTEM32/XpsFilt.dll"
}

ww_install_dotnet30sp1()
{
ww_remove_mono
ww_install dotnet30
wineserver -w
ww_install dotnet20sp1
wineserver -w

wine reg add "HKLM\\Software\\Microsoft\\Net Framework Setup\\NDP\\v3.0" /v Version /t REG_SZ /d "3.0" /f
wine reg add "HKLM\\Software\\Microsoft-\\Net Framework Setup\\NDP\\v3.0" /v SP /t REG_DWORD /d 0001 /f

ww_cd_repo
ww_try wine msiexec /i "dotnet30sp1.xpsep.msi" ${WW_UNATTENDED_SLASH_QB}
wine sc delete FontCache3.0.0.0

wine dotnet30sp1.exe /q
status=$?
ww_info dotnet30sp1.exe exited with status $status
}

#---------------------------------------------------------------------------------------

ww_download_dotnet35()
{
ww_download a3625c59d7a2995fb60877b5f5324892a1693b2a 'dotnet20.exe' 'http://download.lenovo.com/ibmdl/pub/pc/pccbbs/thinkvantage_en/dotnetfx.exe' '' 
ww_download eef5a36924cdf0c02598ccf96aa4f60887a49840 'dotnet20sp1.exe' 'http://download.microsoft.com/download/0/8/c/08c19fa4-4c4f-4ffb-9d6c-150906578c9e/NetFx20SP1_x86.exe' '' 
ww_download f3d2c3c7e4c0c35450cf6dab1f9f2e9e7ff50039 'dotnet30.exe' 'ftp://ftp.kworld.com.tw/kworld/temp/Framework/dotnetfx3.exe' '' 
ww_download 8d779e337920b097aa0c01859912950606e9fc12 'dotnet30sp1.exe' 'http://download.microsoft.com/download/8/F/E/8FEEE89D-9E4F-4BA3-993E-0FFEA8E21E1B/NetFx30SP1_x86.exe' '' 
ww_download 5d332ebd1025e294adafe72030fe33db707b2c82 'dotnet30sp1.xpsep.msi' 'http://download.microsoft.com/download/2/5/2/2526f55d-32bc-410f-be18-164ba67ae07d/XPSEP%20XP%20and%20Server%202003%2032%20bit.msi' '' 
ww_download 0a271bb44531aadef902829f98dfad66e4a57586 'dotnet35.exe' 'http://download.microsoft.com/download/6/0/f/60fc5854-3cb8-4892-b6db-bd4f42510f28/dotnetfx35.exe' '' 
ww_download d4c2178dfb807e1a0267fce0fd06b8d51106d913 'msxml3.msi' 'ftp://85.66.4.250/E_meghajto/ZOLI_C_SAVE/Documents%20and%20Settings/Docsis/Local%20Settings/Temp/NERO14767/Data/Redist/msxml3.msi' '' 
}

ww_check_dotnet35()
{
ww_native "$WW_WINDOWS/Microsoft.NET/Framework/v3.5/MSBuild.exe"
}

ww_install_dotnet35()
{
ww_warn "dotnet35 does not yet fully work or install on wine. Caveat emptor."

ww_remove_mono

ww_install dotnet30sp1
wineserver -w

if ww_workaround_wine_bug 33450 "Installing msxml3"  ,1.5.28
then
    ww_install msxml3
fi

wine reg delete "HKLM\\Software\\Microsoft\\NET Framework Setup\\NDP\\v3.5" /f

cd "$WW_TEMP"
ww_cabextract $WW_UNATTENDED_DASH_Q "$WW_CACHE"/dotnet35.exe
cd wcu/dotNetFramework
wine dotNetFx35setup.exe /lang:ENU $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_dotnet35sp1()
{
ww_download b3981b13fbc45823131f69d125992d6330212f27 'ahk.zip' 'http://www.autohotkey.com/download/AutoHotkey104805.zip' '' 
ww_download a3625c59d7a2995fb60877b5f5324892a1693b2a 'dotnet20.exe' 'http://download.lenovo.com/ibmdl/pub/pc/pccbbs/thinkvantage_en/dotnetfx.exe' '' 
ww_download eef5a36924cdf0c02598ccf96aa4f60887a49840 'dotnet20sp1.exe' 'http://download.microsoft.com/download/0/8/c/08c19fa4-4c4f-4ffb-9d6c-150906578c9e/NetFx20SP1_x86.exe' '' 
ww_download 22d776d4d204863105a5db99e8b8888be23c61a7 'dotnet20sp2.exe' 'http://download.microsoft.com/download/c/6/e/c6e88215-0178-4c6c-b5f3-158ff77b1f38/NetFx20SP2_x86.exe' '' 
ww_download f3d2c3c7e4c0c35450cf6dab1f9f2e9e7ff50039 'dotnet30.exe' 'ftp://ftp.kworld.com.tw/kworld/temp/Framework/dotnetfx3.exe' '' 
ww_download 8d779e337920b097aa0c01859912950606e9fc12 'dotnet30sp1.exe' 'http://download.microsoft.com/download/8/F/E/8FEEE89D-9E4F-4BA3-993E-0FFEA8E21E1B/NetFx30SP1_x86.exe' '' 
ww_download 5d332ebd1025e294adafe72030fe33db707b2c82 'dotnet30sp1.xpsep.msi' 'http://download.microsoft.com/download/2/5/2/2526f55d-32bc-410f-be18-164ba67ae07d/XPSEP%20XP%20and%20Server%202003%2032%20bit.msi' '' 
ww_download 0a271bb44531aadef902829f98dfad66e4a57586 'dotnet35.exe' 'http://download.microsoft.com/download/6/0/f/60fc5854-3cb8-4892-b6db-bd4f42510f28/dotnetfx35.exe' '' 
ww_download 3dce66bae0dd71284ac7a971baed07030a186918 'dotnet35sp1.exe' 'http://download.microsoft.com/download/2/0/e/20e90413-712f-438c-988e-fdaa79a8ac3d/dotnetfx35.exe' '' 
ww_download d4c2178dfb807e1a0267fce0fd06b8d51106d913 'msxml3.msi' 'ftp://85.66.4.250/E_meghajto/ZOLI_C_SAVE/Documents%20and%20Settings/Docsis/Local%20Settings/Temp/NERO14767/Data/Redist/msxml3.msi' '' 
}

ww_check_dotnet35sp1()
{
ww_exists "$WW_WINDOWS/Microsoft.NET/Framework/v3.5/Microsoft .NET Framework 3.5 SP1/logo.bmp"
}

ww_install_dotnet35sp1()
{
ww_warn "dotnet35sp1 does not yet fully work or install on wine. Caveat emptor."

ww_remove_mono

ww_install dotnet35
wineserver -w
ww_install dotnet20sp2
wineserver -w

WINEDLLOVERRIDES="winemenubuilder.exe=n;ngen.exe,mscorsvw.exe=b"
export WINEDLLOVERRIDES

ww_cd_repo
ww_ahk "
    SetTitleMatchMode, 2
    run, dotnet35sp1.exe /lang:ENU $WW_UNATTENDED_SLASH_Q

    Loop
    {
        sleep 1000
        ifwinexist,, cannot be uninstalled
        {
            WinClose,, cannot be uninstalled
            continue
        }
        Process, exist, dotnetfx35.exe
        dotnet_pid = %ErrorLevel%
        if dotnet_pid = 0
        {
            break
        }
    }
"
}

#---------------------------------------------------------------------------------------

ww_download_dotnet40()
{
ww_download 58da3d74db353aad03588cbb5cea8234166d8b99 'dotnet40.exe' 'http://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe' '' 
}

ww_check_dotnet40()
{
ww_native "$WW_WINDOWS/Microsoft.NET/Framework/v4.0.30319/ngen.exe"
}

ww_install_dotnet40()
{
ww_warn "dotnet40 does not yet fully work or install on wine. Caveat emptor."

ww_remove_mono

wine reg delete "HKLM\Software\Microsoft\NET Framework Setup\NDP\v4" /f

ww_try rm -f "$WW_SYSTEM32/mscoree.dll"

ww_cd_repo

WINEDLLOVERRIDES="winemenubuilder.exe=n;fusion=b" wine dotnet40.exe /q /c:"install.exe /q" || true

ww_override native mscoree

wine reg add "HKLM\\Software\\Microsoft\\NET Framework Setup\\NDP\\v4\\Full" /v Install /t REG_DWORD /d 0001 /f
wine reg add "HKLM\\Software\\Microsoft\\NET Framework Setup\\NDP\\v4\\Full" /v Version /t REG_SZ /d "4.0.30319" /f
}

#---------------------------------------------------------------------------------------

ww_download_dotnet45()
{
ww_download a3625c59d7a2995fb60877b5f5324892a1693b2a 'dotnet20.exe' 'http://download.lenovo.com/ibmdl/pub/pc/pccbbs/thinkvantage_en/dotnetfx.exe' '' 
ww_download eef5a36924cdf0c02598ccf96aa4f60887a49840 'dotnet20sp1.exe' 'http://download.microsoft.com/download/0/8/c/08c19fa4-4c4f-4ffb-9d6c-150906578c9e/NetFx20SP1_x86.exe' '' 
ww_download f3d2c3c7e4c0c35450cf6dab1f9f2e9e7ff50039 'dotnet30.exe' 'ftp://ftp.kworld.com.tw/kworld/temp/Framework/dotnetfx3.exe' '' 
ww_download 8d779e337920b097aa0c01859912950606e9fc12 'dotnet30sp1.exe' 'http://download.microsoft.com/download/8/F/E/8FEEE89D-9E4F-4BA3-993E-0FFEA8E21E1B/NetFx30SP1_x86.exe' '' 
ww_download 5d332ebd1025e294adafe72030fe33db707b2c82 'dotnet30sp1.xpsep.msi' 'http://download.microsoft.com/download/2/5/2/2526f55d-32bc-410f-be18-164ba67ae07d/XPSEP%20XP%20and%20Server%202003%2032%20bit.msi' '' 
ww_download 0a271bb44531aadef902829f98dfad66e4a57586 'dotnet35.exe' 'http://download.microsoft.com/download/6/0/f/60fc5854-3cb8-4892-b6db-bd4f42510f28/dotnetfx35.exe' '' 
ww_download 58da3d74db353aad03588cbb5cea8234166d8b99 'dotnet40.exe' 'http://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe' '' 
ww_download b2ff712ca0947040ca0b8e9bd7436a3c3524bb5d 'dotnet45.exe' 'http://download.microsoft.com/download/b/a/4/ba4a7e71-2906-4b2d-a0e1-80cf16844f5f/dotnetfx45_full_x86_x64.exe' '' 
ww_download d4c2178dfb807e1a0267fce0fd06b8d51106d913 'msxml3.msi' 'ftp://85.66.4.250/E_meghajto/ZOLI_C_SAVE/Documents%20and%20Settings/Docsis/Local%20Settings/Temp/NERO14767/Data/Redist/msxml3.msi' '' 
}

ww_check_dotnet45()
{
ww_exists "$WW_WINDOWS/Microsoft.NET/Framework/v4.0.30319/Microsoft.Windows.ApplicationServer.Applications.45.man"
}

ww_install_dotnet45()
{
ww_remove_mono

wine reg delete "HKLM\Software\Microsoft\NET Framework Setup\NDP\v4" /f

ww_try rm -f "$WW_SYSTEM32/mscoree.dll"

ww_install dotnet35
ww_install dotnet40
ww_set_winver win7

ww_cd_repo

WINEDLLOVERRIDES="winemenubuilder.exe=n;fusion=b" wine dotnet45.exe /q /c:"install.exe /q"
status=$?
case $status in
    0) ;;
    105) echo "Exit status $status - normal, user selected 'restart now'" ;;
    194) echo "Exit status $status - normal, user selected 'restart later'" ;;
    *) ww_die "Exit status $status - dotnet45 installation failed" ;;
esac

ww_override native mscoree

ww_warn "Setting Windows version to 2003, otherwise applications using .NET 4.5 will subtly fail"
ww_set_winver win2k3
}

#---------------------------------------------------------------------------------------

ww_download_dotnet452()
{
ww_download a3625c59d7a2995fb60877b5f5324892a1693b2a 'dotnet20.exe' 'http://download.lenovo.com/ibmdl/pub/pc/pccbbs/thinkvantage_en/dotnetfx.exe' '' 
ww_download eef5a36924cdf0c02598ccf96aa4f60887a49840 'dotnet20sp1.exe' 'http://download.microsoft.com/download/0/8/c/08c19fa4-4c4f-4ffb-9d6c-150906578c9e/NetFx20SP1_x86.exe' '' 
ww_download f3d2c3c7e4c0c35450cf6dab1f9f2e9e7ff50039 'dotnet30.exe' 'ftp://ftp.kworld.com.tw/kworld/temp/Framework/dotnetfx3.exe' '' 
ww_download 8d779e337920b097aa0c01859912950606e9fc12 'dotnet30sp1.exe' 'http://download.microsoft.com/download/8/F/E/8FEEE89D-9E4F-4BA3-993E-0FFEA8E21E1B/NetFx30SP1_x86.exe' '' 
ww_download 5d332ebd1025e294adafe72030fe33db707b2c82 'dotnet30sp1.xpsep.msi' 'http://download.microsoft.com/download/2/5/2/2526f55d-32bc-410f-be18-164ba67ae07d/XPSEP%20XP%20and%20Server%202003%2032%20bit.msi' '' 
ww_download 0a271bb44531aadef902829f98dfad66e4a57586 'dotnet35.exe' 'http://download.microsoft.com/download/6/0/f/60fc5854-3cb8-4892-b6db-bd4f42510f28/dotnetfx35.exe' '' 
ww_download 58da3d74db353aad03588cbb5cea8234166d8b99 'dotnet40.exe' 'http://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe' '' 
ww_download 89f86f9522dc7a8a965facce839abb790a285a63 'dotnet452.exe' 'http://download.microsoft.com/download/E/2/1/E21644B5-2DF2-47C2-91BD-63C560427900/NDP452-KB2901907-x86-x64-AllOS-ENU.exe' '' 
ww_download d4c2178dfb807e1a0267fce0fd06b8d51106d913 'msxml3.msi' 'ftp://85.66.4.250/E_meghajto/ZOLI_C_SAVE/Documents%20and%20Settings/Docsis/Local%20Settings/Temp/NERO14767/Data/Redist/msxml3.msi' '' 
}

ww_check_dotnet452()
{
ww_exists "$WW_WINDOWS/Microsoft.NET/Framework/v4.0.30319/Microsoft.Windows.ApplicationServer.Applications.45.man"
}

ww_install_dotnet452()
{
ww_remove_mono

wine reg delete "HKLM\Software\Microsoft\NET Framework Setup\NDP\v4" /f

ww_try rm -f "$WW_SYSTEM32/mscoree.dll"

ww_install dotnet35
ww_install dotnet40
ww_set_winver win7

ww_cd_repo

WINEDLLOVERRIDES="winemenubuilder.exe=n;fusion=b" wine dotnet452.exe /q /c:"install.exe /q"
status=$?

case $status in
    0) ;;
    105) echo "Exit status $status - normal, user selected 'restart now'" ;;
    194) echo "Exit status $status - normal, user selected 'restart later'" ;;
    *) ww_die "Exit status $status - dotnet452 installation failed" ;;
esac

ww_override native mscoree

ww_warn "Setting Windows version to 2003, otherwise applications using .NET 4.5 will subtly fail"
ww_set_winver win2k3
}

#---------------------------------------------------------------------------------------

ww_download_dotnet_verifier()
{
ww_download b9712da2943e057668f21f68c473657a205c5cb8 'dotnet_verifier.zip' 'http://blogs.msdn.com/cfs-file.ashx/__key/CommunityServer-Components-PostAttachments/00-08-99-90-04/netfx_5F00_setupverifier_5F00_new.zip' '' 
}

ww_check_dotnet_verifier()
{
ww_native "$WW_SYSTEM32/netfx_setupverifier.exe"
}

ww_install_dotnet_verifier()
{
ww_cd_repo
ww_unzip "$WW_SYSTEM32" dotnet_verifier.zip netfx_setupverifier.exe
}

#---------------------------------------------------------------------------------------

ww_download_dpvoice()
{
ww_dx_feb2010_download
}

ww_check_dpvoice()
{
ww_native "$WW_SYSTEM32/dpvoice.dll" && ww_native "$WW_SYSTEM32/dpvvox.dll" && ww_native "$WW_SYSTEM32/dpvacm.dll"
}

ww_install_dpvoice()
{
ww_cabextract -d "$WW_TEMP" -L -F 'dxnt.cab' "$WW_DX_FEB_PATH"
for x in "$WW_TEMP"/*.cab
do
  ww_cabextract -d "$WW_SYSTEM32" -L -F 'dpvoice.dll' "$x"
  ww_cabextract -d "$WW_SYSTEM32" -L -F 'dpvvox.dll' "$x"
  ww_cabextract -d "$WW_SYSTEM32" -L -F 'dpvacm.dll' "$x"
done
ww_regsvr dpvoice.dll
ww_regsvr dpvvox.dll
ww_regsvr dpvacm.dll
ww_override native dpvoice
ww_override native dpvvox
ww_override native dpvacm
}

#---------------------------------------------------------------------------------------

ww_download_droid()
{
ww_download 560e4bcafdebaf29645fbf92633a2ae0d2f9801f 'DroidSans-Bold.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSans-Bold.ttf' '' 
ww_download 62f2841f61e4be66a0303cd1567ed2d300b4e31c 'DroidSans.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSans.ttf' '' 
ww_download c5e4f11e2f1d0b84e5f268a7ebfd28b54dc6bcdc 'DroidSansFallback.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSansFallback.ttf' '' 
ww_download b3a248c11692aa88a30eb25df425b8910fe05dc5 'DroidSansJapanese.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSansJapanese.ttf' '' 
ww_download 133fb6cf26ea073b456fb557b94ce8c46143b117 'DroidSansMono.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSansMono.ttf' '' 
ww_download 2775e9b8e96a3e9593acb5cf6923abb2e6008187 'DroidSerif-Bold.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSerif-Bold.ttf' '' 
ww_download 41ce5fef1bd0164caed6958885d7285c841c95f1 'DroidSerif-BoldItalic.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSerif-BoldItalic.ttf' '' 
ww_download e91cc6c1ae9a6699683bcee024551cb58d1be790 'DroidSerif-Italic.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSerif-Italic.ttf' '' 
ww_download a689ce25a4063cf501c12d616f832f2235b5b93b 'DroidSerif-Regular.ttf' 'https://github.com/android/platform_frameworks_base/raw/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSerif-Regular.ttf' '' 
}

ww_check_droid()
{
ww_exists "$WW_FONTS/DroidSans-Bold.ttf"
}

ww_install_droid()
{
ww_droid_helper DroidSans-Bold.ttf        "Droid Sans Bold"
ww_droid_helper DroidSansFallback.ttf     "Droid Sans Fallback"
ww_droid_helper DroidSansJapanese.ttf     "Droid Sans Japanese"
ww_droid_helper DroidSansMono.ttf         "Droid Sans Mono"
ww_droid_helper DroidSans.ttf             "Droid Sans"
ww_droid_helper DroidSerif-BoldItalic.ttf "Droid Serif Bold Italic"
ww_droid_helper DroidSerif-Bold.ttf       "Droid Serif Bold"
ww_droid_helper DroidSerif-Italic.ttf     "Droid Serif Italic"
ww_droid_helper DroidSerif-Regular.ttf    "Droid Serif"
}

#---------------------------------------------------------------------------------------

ww_download_dsdmo()
{
ww_dx_feb2010_download
}

ww_check_dsdmo()
{
ww_native "$WW_SYSTEM32/dsdmo.dll"
}

ww_install_dsdmo()
{
ww_cabextract -d "$WW_TEMP" -L -F dxnt.cab "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dsdmo.dll' "$WW_TEMP/dxnt.cab"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dsdmoprp.dll' "$WW_TEMP/dxnt.cab"
ww_regsvr dsdmo.dll
ww_regsvr dsdmoprp.dll
}

#---------------------------------------------------------------------------------------

ww_download_dsound()
{
ww_dx_feb2010_download
}

ww_check_dsound()
{
ww_native "$WW_SYSTEM32/dsound.dll"
}

ww_install_dsound()
{
ww_cabextract -d "$WW_TEMP" -L -F dxnt.cab "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'dsound.dll' "$WW_TEMP/dxnt.cab"

ww_regsvr dsound.dll

ww_override native dsound
}

#---------------------------------------------------------------------------------------

ww_download_dxdiag()
{
ww_download ea2345f602741343e97a5ece5d1d2c3cc44296c3 'directx81.exe' 'https://web.archive.org/web/20070403193305/http://download.microsoft.com/download/whistler/Update/8.1/W982KMeXP/EN-US/DX81Redist.exe' '' 'ftp://78.154.145.99/pub/windows/microsoft/dx/DX81Redist.exe' '' 'ftp://192.167.225.5/QuikTransfer/LabRX/DA%20SISTEMARE/80GB/old%20desk/NIIMAQ313/temp/3.1.3/DirectX%208.1/DX81Redist.exe' '' 'http://download.microsoft.com/download/whistler/Update/8.1/W982KMeXP/EN-US/DX81Redist.exe' '' 
ww_dx_feb2010_download
}

ww_check_dxdiag()
{
ww_native "$WW_SYSTEM32/dxdiag.exe"
}

ww_install_dxdiag()
{
ww_install gmdls

ww_cabextract -d "$WW_TEMP" -L -F dxnt.cab "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F "dxdiag.exe" "$WW_TEMP/dxnt.cab"
mkdir -p "$WW_WINDOWS/help"
ww_cabextract -d "$WW_WINDOWS/help" -L -F "dxdiag.chm" "$WW_TEMP/dxnt.cab"
ww_override native dxdiag.exe

if ww_workaround_wine_bug 1429
then
    ww_install dxdiagn
fi
if ww_workaround_wine_bug 9027
then
    ww_install directmusic
fi
}

#---------------------------------------------------------------------------------------

ww_download_dxdiagn()
{
ww_dx_feb2010_download
}

ww_check_dxdiagn()
{
ww_native "$WW_SYSTEM32/dxdiagn.dll"
}

ww_install_dxdiagn()
{
ww_cabextract -d "$WW_TEMP" -L -F dxnt.cab "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F dxdiagn.dll "$WW_TEMP/dxnt.cab"
ww_override native dxdiagn
}

#---------------------------------------------------------------------------------------

ww_download_esent()
{
ww_download c3516bc5c9e69fee6d9ac4f981f5b95977a8a2fa 'win7sp1.exe' 'http://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/windows6.1-KB976932-X86.exe' '' 
}

ww_check_esent()
{
ww_native "$WW_SYSTEM32/esent.dll"
}

ww_install_esent()
{
ww_win7sp1_helper x86_microsoft-windows-e..estorageengine-isam_31bf3856ad364e35_6.1.7601.17514_none_f3ebb0cc8a4dd814/esent.dll
ww_cp "$WW_TEMP/x86_microsoft-windows-e..estorageengine-isam_31bf3856ad364e35_6.1.7601.17514_none_f3ebb0cc8a4dd814/esent.dll" "$WW_SYSTEM32/esent.dll"

ww_override native,builtin esent
}

#---------------------------------------------------------------------------------------

ww_download_eufonts()
{
ww_download 9b076c40cb63aa0d8512aa8e610ba11d3466e441 'eufonts.exe' 'http://download.microsoft.com/download/a/1/8/a180e21e-9c2b-4b54-9c32-bf7fd7429970/EUupdate.EXE' '' 
}

ww_check_eufonts()
{
ww_exists "$WW_FONTS/trebucbd.ttf"
}

ww_install_eufonts()
{
ww_cabextract -q -d "$WW_TEMP" "$WW_CACHE"/eufonts.exe
ww_cp "$WW_TEMP"/*.ttf "$WW_FONTS"

ww_register_font ArialBI.ttf "Arial Bold Italic"
ww_register_font ArialI.ttf "Arial Italic"
ww_register_font Arial.ttf "Arial"
ww_register_font TimesBd.ttf "Times New Roman Bold"
ww_register_font TimesBI.ttf "Times New Roman Bold Italic"
ww_register_font TimesI.ttf "Times New Roman Italic"
ww_register_font Times.ttf "Times New Roman"
ww_register_font trebucbd.ttf "Trebuchet Bold"
ww_register_font trebucbi.ttf "Trebuchet Bold Italic"
ww_register_font trebucit.ttf "Trebuchet Italic"
ww_register_font trebuc.ttf "Trebuchet"
ww_register_font Verdanab.ttf "Verdana Bold"
ww_register_font Verdanai.ttf "Verdana Italian"
ww_register_font Verdana.ttf "Verdana"
ww_register_font Verdanaz.ttf "Verdana Bold Italic"
}

#---------------------------------------------------------------------------------------

ww_download_fakechinese()
{
ww_download 28023041b22b6368bcfae076de68109b81e77976 'wenquanyi.tar.gz' 'http://downloads.sourceforge.net/wqy/wqy-microhei-0.2.0-beta.tar.gz' '' 
}

ww_check_fakechinese()
{
false
}

ww_install_fakechinese()
{
ww_install wenquanyi

ww_register_font_replacement "Microsoft JhengHei" "WenQuanYi Micro Hei"
ww_register_font_replacement "Microsoft YaHei" "WenQuanYi Micro Hei"
ww_register_font_replacement "SimHei" "WenQuanYi Micro Hei"
ww_register_font_replacement "DFKai-SB" "WenQuanYi Micro Hei"
ww_register_font_replacement "FangSong" "WenQuanYi Micro Hei"
ww_register_font_replacement "KaiTi" "WenQuanYi Micro Hei"
ww_register_font_replacement "PMingLiU" "WenQuanYi Micro Hei"
ww_register_font_replacement "MingLiU" "WenQuanYi Micro Hei"
ww_register_font_replacement "NSimSun" "WenQuanYi Micro Hei"
ww_register_font_replacement "SimKai" "WenQuanYi Micro Hei"
ww_register_font_replacement "SimSun" "WenQuanYi Micro Hei"
}

#---------------------------------------------------------------------------------------

ww_download_fakejapanese()
{
ww_download 4f636d5c7c1bc16b96ea723adb16838cfb6df059 'takao.zip' 'http://launchpad.net/takao-fonts/trunk/003.02.01/+download/takao-fonts-ttf-003.02.01.zip' '' 
}

ww_check_fakejapanese()
{
false
}

ww_install_fakejapanese()
{
ww_install takao

ww_register_font_replacement "MS Gothic" "TakaoGothic"
ww_register_font_replacement "MS UI Gothic" "TakaoGothic"
ww_register_font_replacement "MS PGothic" "TakaoPGothic"
ww_register_font_replacement "MS Mincho" "TakaoMincho"
ww_register_font_replacement "MS PMincho" "TakaoPMincho"
}

#---------------------------------------------------------------------------------------

ww_download_fakejapanese_ipamona()
{
ww_download 57dd13ab58c0005d3ee2932539e4987ab0242bc7 'ipamona.tar.gz' 'http://www.geocities.jp/ipa_mona/opfc-ModuleHP-1.1.1_withIPAMonaFonts-1.0.8.tar.gz' '' 
}

ww_check_fakejapanese_ipamona()
{
false
}

ww_install_fakejapanese_ipamona()
{
ww_install ipamona

jpname_msgothic="$(echo "xff2dxff33 x30b4x30b7x30c3x30af" | iconv -f utf8 -t cp932)"
jpname_mspgothic="$(echo "xff2dxff33 xff30x30b4x30b7x30c3x30af" | iconv -f utf8 -t cp932)"
jpname_msmincho="$(echo "xff2dxff33 x660ex671d" | iconv -f utf8 -t cp932)"
jpname_mspmincho="$(echo "xff2dxff33 xff30x660ex671d" | iconv -f utf8 -t cp932)"

ww_register_font_replacement "MS UI Gothic" "IPAMonaUIGothic"
ww_register_font_replacement "MS Gothic" "IPAMonaGothic"
ww_register_font_replacement "MS PGothic" "IPAMonaPGothic"
ww_register_font_replacement "MS Mincho" "IPAMonaMincho"
ww_register_font_replacement "MS PMincho" "IPAMonaPMincho"
ww_register_font_replacement "$jpname_msgothic" "IPAMonaGothic"
ww_register_font_replacement "$jpname_mspgothic" "IPAMonaPGothic"
ww_register_font_replacement "$jpname_msmincho" "IPAMonaMincho"
ww_register_font_replacement "$jpname_mspmincho" "IPAMonaPMincho"
}

#---------------------------------------------------------------------------------------

ww_download_fakekorean()
{
ww_download afdee34f700007de6ea87b43c92a88b7385ba65b 'baekmuk.tar.gz' 'http://http.debian.net/debian/pool/main/f/fonts-baekmuk/fonts-baekmuk_2.2.orig.tar.gz' '' 
}

ww_check_fakekorean()
{
false
}

ww_install_fakekorean()
{
ww_install baekmuk

ww_register_font_replacement "Gulim" "Baekmuk Gulim"
ww_register_font_replacement "GulimChe" "Baekmuk Gulim"
ww_register_font_replacement "Batang" "Baekmuk Batang"
ww_register_font_replacement "BatangChe" "Baekmuk Batang"
ww_register_font_replacement "Dotum" "Baekmuk Dotum"
ww_register_font_replacement "DotumChe" "Baekmuk Dotum"
}

#---------------------------------------------------------------------------------------

ww_download_ffdshow()
{
ww_download 8534c31489e51df70ee9583438d6211e6f0696d0 'ffdshow.exe' 'http://downloads.sourceforge.net/ffdshow-tryout/ffdshow_beta7_rev3154_20091209.exe' '' 
}

ww_check_ffdshow()
{
ww_native "$WW_PROGRAM_FILES/ffdshow/ff_liba52.dll"
}

ww_install_ffdshow()
{
ww_cd_repo_wine ffdshow.exe $WW_UNATTENDED_SLASH_SILENT
}

#---------------------------------------------------------------------------------------

ww_download_flash()
{
ww_download 40df72ab2c22bcd4442aa35eb586000776129982 'flashplayer.ax.zip' 'http://download.macromedia.com/pub/flashplayer/installers/archive/fp_14.0.0.176_archive.zip' '' 
ww_download 62e5bc2e88b50091847408b9d473ee4a6c185167 'flashplayer.exe' 'http://download.macromedia.com/pub/flashplayer/updaters/14/flashplayer_14_sa.exe' '' 
ww_download b94860ca0eff3e1420c24f9647a5f9f5e610ce34 'flashplayer.zip' 'http://download.macromedia.com/pub/flashplayer/installers/archive/fp_14.0.0.179_archive.zip' '' 
}

ww_check_flash()
{
ww_native "$WW_SYSTEM32/Macromed/Flash/FlashUtil32_14_0_0_179_Plugin.exe" && ww_native "$WW_SYSTEM32/Macromed/Flash/FlashUtil32_14_0_0_176_ActiveX.exe" && ww_native "$WW_SYSTEM32/Macromed/Flash/flashplayer_14_sa.exe"
}

ww_install_flash()
{
ww_unzip "$WW_TEMP" "$WW_CACHE"/flashplayer.ax.zip fp_14.0.0.176_archive/14_0_r0_176/flashplayer14_0r0_176_winax.exe
ww_cd "$WW_TEMP"/fp_14.0.0.176_archive/14_0_r0_176
ww_wine flashplayer14_0r0_176_winax.exe /install

ww_unzip "$WW_TEMP" "$WW_CACHE"/flashplayer.zip fp_14.0.0.179_archive/14_0_r0_179/flashplayer14_0r0_179_win.exe
ww_cd "$WW_TEMP"/fp_14.0.0.179_archive/14_0_r0_179
ww_wine flashplayer14_0r0_179_win.exe /install

ww_cp "$WW_CACHE/flashplayer.exe" "$WW_SYSTEM32/Macromed/Flash/flashplayer_14_sa.exe"
}

#---------------------------------------------------------------------------------------

ww_download_fontsmooth_bgr()
{
:
}

ww_check_fontsmooth_bgr()
{
false
}

ww_install_fontsmooth_bgr()
{
ww_set_fontsmooth bgr
}

#---------------------------------------------------------------------------------------

ww_download_fontsmooth_disable()
{
:
}

ww_check_fontsmooth_disable()
{
false
}

ww_install_fontsmooth_disable()
{
ww_set_fontsmooth disable
}

#---------------------------------------------------------------------------------------

ww_download_fontsmooth_gray()
{
:
}

ww_check_fontsmooth_gray()
{
false
}

ww_install_fontsmooth_gray()
{
ww_set_fontsmooth gray
}

#---------------------------------------------------------------------------------------

ww_download_fontsmooth_rgb()
{
:
}

ww_check_fontsmooth_rgb()
{
false
}

ww_install_fontsmooth_rgb()
{
ww_set_fontsmooth rgb
}

#---------------------------------------------------------------------------------------

ww_download_forcemono()
{
:
}

ww_check_forcemono()
{
false
}

ww_install_forcemono()
{
ww_override native mscoree
ww_override disabled mscorsvw.exe
}

#---------------------------------------------------------------------------------------

ww_download_gdiplus()
{
ww_download c3516bc5c9e69fee6d9ac4f981f5b95977a8a2fa 'win7sp1.exe' 'http://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/windows6.1-KB976932-X86.exe' '' 
}

ww_check_gdiplus()
{
ww_native "$WW_SYSTEM32/gdiplus.dll"
}

ww_install_gdiplus()
{
ww_win7sp1_helper x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.17514_none_72d18a4386696c80/gdiplus.dll
ww_cp "$WW_TEMP/x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.17514_none_72d18a4386696c80/gdiplus.dll" "$WW_SYSTEM32/gdiplus.dll"

ww_override native gdiplus
}

#---------------------------------------------------------------------------------------

ww_download_gdiplus_winxp()
{
ww_download 6113cd89d77525958295ccbd73b5fb8b89abd0aa 'gdiplus_winxp.exe' 'http://download.cnet.com/NET-Framework-1-0-GDIPLUS-DLL-Security-Update/3000-10250_4-10732223.html' 'data-dl-url='\''\(.*0sp2-KB830348-X86-Enu.*\)'\''' 
}

ww_check_gdiplus_winxp()
{
ww_native "$WW_SYSTEM32/gdiplus.dll"
}

ww_install_gdiplus_winxp()
{
ww_cabextract -d "$WW_TEMP" -F FL_gdiplus_dll_____X86.3643236F_FC70_11D3_A536_0090278A1BB8 "$WW_CACHE"/gdiplus_winxp.exe
ww_cp "$WW_TEMP/FL_gdiplus_dll_____X86.3643236F_FC70_11D3_A536_0090278A1BB8" "$WW_SYSTEM32/gdiplus.dll"

ww_override native gdiplus
}

#---------------------------------------------------------------------------------------

ww_download_gfw()
{
ww_download 6f9e0ba052c68c8b51bb0e3ce6024d0e1c7b20b2 'gfw.exe' 'http://download.microsoft.com/download/5/5/8/55846E20-4A46-4EF8-B272-7F988BC9090A/gfwlivesetupmin.exe' '' 
ww_download fadea6d94a014b039839fecc6e6a11c20afa4fa8 'win2ksp4.exe' 'ftp://ftp.vcitynet.com/win32/win2k/W2KSP4_EN.EXE' '' 'http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 'https://web.archive.org/web/20160129053851/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 
}

ww_check_gfw()
{
ww_native "$WW_SYSTEM32/xlive.dll"
}

ww_install_gfw()
{
ww_cd_repo_wine gfw.exe /nodotnet $WW_UNATTENDED_SLASH_Q

ww_install msasn1
}

#---------------------------------------------------------------------------------------

ww_download_glidewrapper()
{
ww_download 7a9d60a18b660473742b476465e9aea7bd5ab6f8 'glidewrapper.exe' 'http://www.zeckensack.de/glide/archive/GlideWrapper084c.exe' '' 
}

ww_check_glidewrapper()
{
ww_native "$WW_WINDOWS/glide3x.dll"
}

ww_install_glidewrapper()
{
cat > "$WW_TEMP"/disable-browser.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\WineBrowser]
"Browsers"=""

_EOF_
ww_regedit "$WW_TEMP_WIN"\\disable-browser.reg

ww_cd_repo_wine glidewrapper.exe /S

wine reg delete "HKEY_CURRENT_USER\Software\Wine\WineBrowser" /v Browsers /f || true
}

#---------------------------------------------------------------------------------------

ww_download_glsl_disabled()
{
:
}

ww_check_glsl_disabled()
{
false
}

ww_install_glsl_disabled()
{
ww_set_wined3d_var UseGLSL disabled
}

#---------------------------------------------------------------------------------------

ww_download_glsl_enabled()
{
:
}

ww_check_glsl_enabled()
{
false
}

ww_install_glsl_enabled()
{
ww_set_wined3d_var UseGLSL enabled
}

#---------------------------------------------------------------------------------------

ww_download_glut()
{
ww_download fb4731885c05b3cf2c79e85aabe8fc9949616ef4 'glut.zip' 'http://press.liacs.nl/researchdownloads/glut.win32/glut-3.7.6-bin.zip' '' 
}

ww_check_glut()
{
ww_exists "$WW_C/glut-3.7.6-bin/glut32.lib"
}

ww_install_glut()
{
ww_unzip "$WW_TEMP" "$WW_CACHE"/glut.zip
ww_try mv "$WW_TEMP/glut-3.7.6-bin" "$WW_C"
ww_cp "$WW_C"/glut-3.7.6-bin/glut32.dll "$WW_SYSTEM32"
ww_warn "If you want to compile glut programs, add $WW_C/glut-3.7.6-bin to LIB and INCLUDE"
}

#---------------------------------------------------------------------------------------

ww_download_gmdls()
{
ww_download ea2345f602741343e97a5ece5d1d2c3cc44296c3 'directx81.exe' 'https://web.archive.org/web/20070403193305/http://download.microsoft.com/download/whistler/Update/8.1/W982KMeXP/EN-US/DX81Redist.exe' '' 'ftp://78.154.145.99/pub/windows/microsoft/dx/DX81Redist.exe' '' 'ftp://192.167.225.5/QuikTransfer/LabRX/DA%20SISTEMARE/80GB/old%20desk/NIIMAQ313/temp/3.1.3/DirectX%208.1/DX81Redist.exe' '' 'http://download.microsoft.com/download/whistler/Update/8.1/W982KMeXP/EN-US/DX81Redist.exe' '' 
}

ww_check_gmdls()
{
ww_native "$WW_SYSTEM32/drivers/gm.dls"
}

ww_install_gmdls()
{
ww_unzip "$WW_TEMP" "$WW_CACHE"/directx81.exe "*/*/DirectX.cab"
ww_cabextract -d "$WW_TEMP" -F gm16.dls "$WW_TEMP"/*/*/DirectX.cab
ww_try mv "$WW_TEMP"/gm16.dls "$WW_SYSTEM32"/drivers/gm.dls
}

#---------------------------------------------------------------------------------------

ww_download_grabfullscreen_n()
{
:
}

ww_check_grabfullscreen_n()
{
false
}

ww_install_grabfullscreen_n()
{
ww_set_grabfullscreen n
}

#---------------------------------------------------------------------------------------

ww_download_grabfullscreen_y()
{
:
}

ww_check_grabfullscreen_y()
{
false
}

ww_install_grabfullscreen_y()
{
ww_set_grabfullscreen y
}

#---------------------------------------------------------------------------------------

ww_download_gsm_0()
{
:
}

ww_check_gsm_0()
{
false
}

ww_install_gsm_0()
{
winetricks_set_wined3d_var MaxShaderModelGS 0
}

#---------------------------------------------------------------------------------------

ww_download_gsm_1()
{
:
}

ww_check_gsm_1()
{
false
}

ww_install_gsm_1()
{
winetricks_set_wined3d_var MaxShaderModelGS 1
}

#---------------------------------------------------------------------------------------

ww_download_gsm_2()
{
:
}

ww_check_gsm_2()
{
false
}

ww_install_gsm_2()
{
winetricks_set_wined3d_var MaxShaderModelGS 2
}

#---------------------------------------------------------------------------------------

ww_download_gsm_3()
{
:
}

ww_check_gsm_3()
{
false
}

ww_install_gsm_3()
{
winetricks_set_wined3d_var MaxShaderModelGS 3
}

#---------------------------------------------------------------------------------------

ww_download_heapcheck()
{
:
}

ww_check_heapcheck()
{
false
}

ww_install_heapcheck()
{
cat > "$WW_TEMP"/heapcheck.reg <<_EOF_
REGEDIT4

[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager]
"GlobalFlag"=dword:00200030

_EOF_
ww_regedit "$WW_TEMP_WIN"\\heapcheck.reg
}

#---------------------------------------------------------------------------------------

ww_download_hid()
{
ww_download fadea6d94a014b039839fecc6e6a11c20afa4fa8 'win2ksp4.exe' 'ftp://ftp.vcitynet.com/win32/win2k/W2KSP4_EN.EXE' '' 'http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 'https://web.archive.org/web/20160129053851/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 
}

ww_check_hid()
{
ww_native "$WW_SYSTEM32/hid.dll"
}

ww_install_hid()
{
ww_win2ksp4_helper i386/hid.dl_
ww_cabextract -d "$WW_SYSTEM32" "$WW_TEMP"/i386/hid.dl_

ww_override native hid
}

#---------------------------------------------------------------------------------------

ww_download_hidewineexports_disable()
{
:
}

ww_check_hidewineexports_disable()
{
false
}

ww_install_hidewineexports_disable()
{
set_hidewineexports disable
}

#---------------------------------------------------------------------------------------

ww_download_hidewineexports_enable()
{
:
}

ww_check_hidewineexports_enable()
{
false
}

ww_install_hidewineexports_enable()
{
set_hidewineexports enable
}

#---------------------------------------------------------------------------------------

ww_download_hosts()
{
:
}

ww_check_hosts()
{
false
}

ww_install_hosts()
{
mkdir -p "$WW_WINDOWS"/system32/drivers/etc
touch "$WW_WINDOWS"/system32/drivers/etc/hosts
touch "$WW_WINDOWS"/system32/drivers/etc/services
}

#---------------------------------------------------------------------------------------

ww_download_icodecs()
{
ww_download b3981b13fbc45823131f69d125992d6330212f27 'ahk.zip' 'http://www.autohotkey.com/download/AutoHotkey104805.zip' '' 
ww_download 2c5d64f472abe3f601ce352dcca75b4f02996f8a 'icodecs.exe' 'http://www.cucusoft.com/codecdownload/codinstl.exe' '' 
}

ww_check_icodecs()
{
ww_native "$WW_SYSTEM32/ir50_32.dll"
}

ww_install_icodecs()
{
ww_cd_repo
ww_ahk "
    SetTitleMatchMode, 2
    run icodecs.exe
    winwait, Welcome
    sleep 1000
    controlclick, Button1  ; Next
    winwait, Software License Agreement
    sleep 1000
    controlclick, Button2  ; Yes
    winwait, Setup Complete
    sleep 1000
    controlclick, Button4  ; Finish
    winwaitclose
"

ww_regsvr ir50_32.dll
}

#---------------------------------------------------------------------------------------

ww_download_ie6()
{
ww_download 8e483db28ff01a7cabd39147ab6c59753ea1f533 'ie60.exe' 'http://download.oldapps.com/Internet_Explorer/ie60.exe' '' 
ww_download 4fc3bf0dc96b5cf5ab26430fac1c33c5c50bd142 'msls31.exe' 'https://web.archive.org/web/20160710055851/http://download.microsoft.com/download/WindowsInstaller/Install/2.0/NT45/EN-US/InstMsiW.exe' '' 
ww_download 6f5db296ebf58e81c49bc667049a3f88a3f1ec3d 'pngfilt.exe' 'https://web.archive.org/web/20061224003406/http://download.microsoft.com/download/5/0/c/50c42d0e-07a8-4a2b-befb-1a403bd0df96/IE5.01sp4-KB871260-Windows2000sp4-x86-ENU.exe' '' 
}

ww_check_ie6()
{
ww_native "$WW_PROGRAM_FILES/Internet Explorer/iedetect.dll"
}

ww_install_ie6()
{
ww_install msls31

ww_cd "$WW_TEMP"
wine "$WW_CACHE"/ie60.exe

if [ ! -f "$WW_SYSTEM32"/plugin.ocx ]
then
    ww_override builtin iexplore.exe
    ww_wine iexplore -unregserver
fi

ww_override native,builtin iexplore.exe inetcpl.cpl itircl itss jscript mlang mshtml msimtf shdoclc shdocvw shlwapi

mv "$WW_PROGRAM_FILES"/"Internet Explorer"/iexplore.exe "$WW_PROGRAM_FILES"/"Internet Explorer"/iexplore.exe.bak
for dll in itircl itss jscript mlang mshtml msimtf shdoclc shdocvw shlwapi
do
    test -f "$WW_SYSTEM32"/$dll.dll &&
    mv "$WW_SYSTEM32"/$dll.dll "$WW_SYSTEM32"/$dll.dll.bak
done

ww_set_winver win2k

rm -f "$WW_SYSTEM32"/browseui.dll "$WW_SYSTEM32"/inseng.dll

rm -f "$WW_SYSTEM32"/inetcpl.cpl

ww_cabextract -F inseng.dll "$WW_TEMP/IE 6.0 Full/ACTSETUP.CAB"
mv inseng.dll "$WW_SYSTEM32"
ww_override native inseng

cd "$WW_TEMP/IE 6.0 Full"
wine IE6SETUP.EXE /q:a /r:n /c:"ie6wzd /S:""#e"" /q:a /r:n"

status=$?
case $status in
    0|194) ;;
    *) ww_die ie6 installation failed
esac

cd "$WW_SYSTEM32"
for i in actxprxy.dll browseui.dll browsewm.dll cdfview.dll ddraw.dll \
  dispex.dll dsound.dll iedkcs32.dll iepeers.dll iesetup.dll imgutil.dll \
  inetcomm.dll inetcpl.cpl inseng.dll isetup.dll jscript.dll laprxy.dll \
  mlang.dll mshtml.dll mshtmled.dll msi.dll msident.dll \
  msoeacct.dll msrating.dll mstime.dll msxml3.dll occache.dll \
  ole32.dll oleaut32.dll olepro32.dll pngfilt.dll quartz.dll \
  rpcrt4.dll rsabase.dll rsaenh.dll scrobj.dll scrrun.dll \
  shdocvw.dll shell32.dll vbscript.dll webcheck.dll \
  wshcon.dll wshext.dll asctrls.ocx hhctrl.ocx mscomct2.ocx \
  plugin.ocx proctexe.ocx tdc.ocx webcheck.dll wshom.ocx
do
    wine regsvr32 /i $i > /dev/null 2>&1
done

ww_unset_winver

ww_install pngfilt
}

#---------------------------------------------------------------------------------------

ww_download_ie7()
{
ww_download d39b89c360fbaa9706b5181ae4718100687a5326 'ie7.exe' 'http://download.microsoft.com/download/3/8/8/38889DC1-848C-4BF2-8335-86C573AD86D9/IE7-WindowsXP-x86-enu.exe' '' 
ww_download ac8f50dd54d011f3bb1dd79240dae9378748449f 'winetest.cat' 'https://github.com/Winetricks/winetricks/raw/master/files/winetest.cat' '' 
}

ww_check_ie7()
{
ww_exists "$WW_WINDOWS/ie7.log"
}

ww_install_ie7()
{
if grep -q -i "wine placeholder" "$WW_PROGRAM_FILES/Internet Explorer/iexplore.exe"
then
    ww_override builtin iexplore.exe
    ww_wine iexplore -unregserver
fi

ww_override native,builtin itircl itss jscript mshtml msimtf shdoclc shdocvw shlwapi urlmon wininet xmllite

ww_override native iexplore.exe

ww_override builtin updspapi

if [ -f "$WW_PROGRAM_FILES/Internet Explorer/iexplore.exe" ]
then
    mv "$WW_PROGRAM_FILES/Internet Explorer/iexplore.exe" "$WW_PROGRAM_FILES/Internet Explorer/iexplore.exe.bak"
fi
for dll in itircl itss jscript mshtml msimtf shdoclc shdocvw shlwapi urlmon
do
    test -f "$WW_SYSTEM32"/$dll.dll &&
    mv "$WW_SYSTEM32"/$dll.dll "$WW_SYSTEM32"/$dll.dll.bak
done

mkdir -p "$WW_SYSTEM32"/catroot/\{f750e6c3-38ee-11d1-85e5-00c04fc295ee\}
ww_cp "$WW_CACHE"/winetest.cat "$WW_SYSTEM32"/catroot/\{f750e6c3-38ee-11d1-85e5-00c04fc295ee\}/oem0.cat

if test -w /
then
    rm -f "$WINEPREFIX/dosdevices/z:.bak_wt"
    mv "$WINEPREFIX/dosdevices/z:" "$WINEPREFIX/dosdevices/z:.bak_wt"
fi

ww_cd_repo

wine ie7.exe $WW_UNATTENDED_SLASH_QUIET

status=$?
case $status in
    0) ;;
    105) echo "exit status $status - normal, user selected 'restart now'" ;;
    194) echo "exit status $status - normal, user selected 'restart later'" ;;
    *) ww_die "exit status $status - ie7 installation failed" ;;
esac

if test -w /
then
    mv "$WINEPREFIX/dosdevices/z:.bak_wt" "$WINEPREFIX/dosdevices/z:"
fi

ww_cd "$WW_SYSTEM32"
for i in actxprxy.dll browseui.dll browsewm.dll cdfview.dll ddraw.dll \
  dispex.dll dsound.dll iedkcs32.dll iepeers.dll iesetup.dll \
  imgutil.dll inetcomm.dll inseng.dll isetup.dll jscript.dll laprxy.dll \
  mlang.dll mshtml.dll mshtmled.dll msi.dll msident.dll \
  msoeacct.dll msrating.dll mstime.dll msxml3.dll occache.dll \
  ole32.dll oleaut32.dll olepro32.dll pngfilt.dll quartz.dll \
  rpcrt4.dll rsabase.dll rsaenh.dll scrobj.dll scrrun.dll \
  shdocvw.dll shell32.dll urlmon.dll vbscript.dll webcheck.dll \
  wshcon.dll wshext.dll asctrls.ocx hhctrl.ocx mscomct2.ocx \
  plugin.ocx proctexe.ocx tdc.ocx webcheck.dll wshom.ocx
do
    wine regsvr32 /i $i > /dev/null 2>&1
done

ww_warn "To start ie7, use the file '${WW_PROGRAM_FILES}/Internet Explorer/iexplore.exe'"
}

#---------------------------------------------------------------------------------------

ww_download_ie8()
{
ww_download e489483e5001f95da04e1ebf3c664173baef3e26 'ie8.exe' 'http://download.microsoft.com/download/C/C/0/CC0BD555-33DD-411E-936B-73AC6F95AE11/IE8-WindowsXP-x86-ENU.exe' '' 
ww_download 4fc3bf0dc96b5cf5ab26430fac1c33c5c50bd142 'msls31.exe' 'https://web.archive.org/web/20160710055851/http://download.microsoft.com/download/WindowsInstaller/Install/2.0/NT45/EN-US/InstMsiW.exe' '' 
ww_download ac8f50dd54d011f3bb1dd79240dae9378748449f 'winetest.cat' 'https://github.com/Winetricks/winetricks/raw/master/files/winetest.cat' '' 
}

ww_check_ie8()
{
ww_exists "$WW_WINDOWS/ie8_main.log"
}

ww_install_ie8()
{
if grep -q -i "wine placeholder" "$WW_PROGRAM_FILES/Internet Explorer/iexplore.exe"
then
    ww_override builtin iexplore.exe
    ww_wine iexplore -unregserver
fi

ww_install msls31

ww_override native,builtin itircl itss jscript msctf mshtml shdoclc shdocvw shlwapi urlmon wininet xmllite

ww_override native iexplore.exe

ww_override builtin updspapi

if [ -f "$WW_PROGRAM_FILES/Internet Explorer/iexplore.exe" ]
then
    mv "$WW_PROGRAM_FILES/Internet Explorer/iexplore.exe" "$WW_PROGRAM_FILES/Internet Explorer/iexplore.exe.bak"
fi
for dll in browseui.dll inseng.dll itircl itss jscript msctf mshtml shdoclc shdocvw shlwapi urlmon
do
    test -f "$WW_SYSTEM32"/$dll.dll &&
    mv "$WW_SYSTEM32"/$dll.dll "$WW_SYSTEM32"/$dll.dll.bak
done

mkdir -p "$WW_SYSTEM32"/catroot/\{f750e6c3-38ee-11d1-85e5-00c04fc295ee\}
ww_cp "$WW_CACHE"/winetest.cat "$WW_SYSTEM32"/catroot/\{f750e6c3-38ee-11d1-85e5-00c04fc295ee\}/oem0.cat

rm -f "$WINEPREFIX/dosdevices/z:.bak_wt"
mv "$WINEPREFIX/dosdevices/z:" "$WINEPREFIX/dosdevices/z:.bak_wt"

ww_cp "$WW_CACHE"/ie8.exe "$WW_TEMP"
cd "$WW_TEMP"
wine ie8.exe $WW_UNATTENDED_SLASH_QUIET /forcerestart

mv "$WINEPREFIX/dosdevices/z:.bak_wt" "$WINEPREFIX/dosdevices/z:"

cd "$WW_SYSTEM32"
for i in actxprxy.dll browseui.dll browsewm.dll cdfview.dll ddraw.dll \
  dispex.dll dsound.dll iedkcs32.dll iepeers.dll iesetup.dll \
  imgutil.dll inetcomm.dll isetup.dll jscript.dll laprxy.dll \
  mlang.dll msctf.dll mshtml.dll mshtmled.dll msi.dll msimtf.dll msident.dll \
  msoeacct.dll msrating.dll mstime.dll msxml3.dll occache.dll \
  ole32.dll oleaut32.dll olepro32.dll pngfilt.dll quartz.dll \
  rpcrt4.dll rsabase.dll rsaenh.dll scrobj.dll scrrun.dll \
  shdocvw.dll shell32.dll urlmon.dll vbscript.dll webcheck.dll \
  wshcon.dll wshext.dll asctrls.ocx hhctrl.ocx mscomct2.ocx \
  plugin.ocx proctexe.ocx tdc.ocx uxtheme.dll webcheck.dll wshom.ocx
do
    wine regsvr32 /i $i > /dev/null 2>&1
done

if ww_workaround_wine_bug 25648 "Setting TabProcGrowth=0 to avoid hang"
then
    cat > "$WW_TEMP"/set-tabprocgrowth.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main]
"TabProcGrowth"=dword:00000000

_EOF_
    ww_regedit "$WW_TEMP_WIN"\\set-tabprocgrowth.reg
fi

ww_warn "To start ie8, use the file '${WW_PROGRAM_FILES}/Internet Explorer/iexplore.exe'"
}

#---------------------------------------------------------------------------------------

ww_download_ie8_kb2936068()
{
ww_download e489483e5001f95da04e1ebf3c664173baef3e26 'ie8.exe' 'http://download.microsoft.com/download/C/C/0/CC0BD555-33DD-411E-936B-73AC6F95AE11/IE8-WindowsXP-x86-ENU.exe' '' 
ww_download 1bdeb741085b8f1ef6efc83f8615121373107347 'ie8_kb2936068.exe' 'https://download.microsoft.com/download/3/8/C/38CE0ABB-01FD-4C0A-A569-BC5E82C34A17/IE8-WindowsXP-KB2936068-x86-ENU.exe' '' 
ww_download 4fc3bf0dc96b5cf5ab26430fac1c33c5c50bd142 'msls31.exe' 'https://web.archive.org/web/20160710055851/http://download.microsoft.com/download/WindowsInstaller/Install/2.0/NT45/EN-US/InstMsiW.exe' '' 
ww_download ac8f50dd54d011f3bb1dd79240dae9378748449f 'winetest.cat' 'https://github.com/Winetricks/winetricks/raw/master/files/winetest.cat' '' 
}

ww_check_ie8_kb2936068()
{
ww_exists "$WW_WINDOWS/KB2936068-IE8.log"
}

ww_install_ie8_kb2936068()
{
ww_install ie8
ww_cd_repo
wine ie8_kb2936068.exe $WW_UNATTENDED_SLASH_QUIET /forcerestart
status=$?
case $status in
    0|194) ;;
    *) ww_die "ie8_kb2936068 installation failed"
esac
}

#---------------------------------------------------------------------------------------

ww_download_ipamona()
{
ww_download 57dd13ab58c0005d3ee2932539e4987ab0242bc7 'ipamona.tar.gz' 'http://www.geocities.jp/ipa_mona/opfc-ModuleHP-1.1.1_withIPAMonaFonts-1.0.8.tar.gz' '' 
}

ww_check_ipamona()
{
ww_exists "$WW_FONTS/ipag-mona.ttf"
}

ww_install_ipamona()
{
ww_cd "$WW_TEMP"
gunzip -dc "$WW_CACHE/ipamona.tar.gz" | tar -xf -
ww_try mv *IPAMonaFonts*/fonts/*.ttf "$WW_FONTS"

ww_register_font ipagui-mona.ttf "IPAMonaUIGothic"
ww_register_font ipag-mona.ttf "IPAMonaGothic"
ww_register_font ipagp-mona.ttf "IPAMonaPGothic"
ww_register_font ipam-mona.ttf "IPAMonaMincho"
ww_register_font ipamp-mona.ttf "IPAMonaPMincho"
}

#---------------------------------------------------------------------------------------

ww_download_jet40()
{
ww_download 8cd25342030857969ede2d8fcc34f3f7bcc2d6d4 'jet40.exe' 'http://download.microsoft.com/download/4/3/9/4393c9ac-e69e-458d-9f6d-2fe191c51469/jet40sp8_9xnt.exe' '' 
ww_download f68594d1f578c3b47bf0639c46c11c5da161feee 'mdac27.exe' 'https://web.archive.org/web/20080731135848/http://download.microsoft.com/download/3/b/f/3bf74b01-16ba-472d-9a8c-42b2b4fa0d76/mdac_typ.exe' '' 
ww_download b15c6a834b7029e2dfed22127cf905b06857e6f5 'wsh57.exe' 'http://download.microsoft.com/download/4/4/d/44de8a9e-630d-4c10-9f17-b9b34d3f6417/scripten.exe' '' 
}

ww_check_jet40()
{
ww_native "$WW_COMMON_FILES/Microsoft Shared/dao/dao360.dll"
}

ww_install_jet40()
{
ww_cd_repo_wine jet40.exe $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_l3codecx()
{
ww_dx_feb2010_download
}

ww_check_l3codecx()
{
ww_native "$WW_SYSTEM32"/l3codeca.acm
}

ww_install_l3codecx()
{
ww_cabextract -d "$WW_TEMP" -L -F dxnt.cab "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F 'l3codecx.ax' "$WW_TEMP/dxnt.cab"

ww_regsvr l3codecx.ax
}

#---------------------------------------------------------------------------------------

ww_download_liberation()
{
ww_download 097882c92e3260742a3dc3bf033792120d8635a3 'liberation.tar.gz' 'https://fedorahosted.org/releases/l/i/liberation-fonts/liberation-fonts-1.04.tar.gz' '' 
}

ww_check_liberation()
{
ww_exists "$WW_FONTS/LiberationMono-BoldItalic.ttf"
}

ww_install_liberation()
{
ww_cd "$WW_TEMP"
gunzip -dc "$WW_CACHE"/liberation.tar.gz | tar -xf -
mv liberation-fonts-1.04/*.ttf "$WW_FONTS"

ww_register_font LiberationMono-BoldItalic.ttf "LiberationMono-BoldItalic"
ww_register_font LiberationMono-Bold.ttf "LiberationMono-Bold"
ww_register_font LiberationMono-Italic.ttf "LiberationMono-Italic"
ww_register_font LiberationMono-Regular.ttf "LiberationMono-Regular"
ww_register_font LiberationSans-BoldItalic.ttf "LiberationSans-BoldItalic"
ww_register_font LiberationSans-Bold.ttf "LiberationSans-Bold"
ww_register_font LiberationSans-Italic.ttf "LiberationSans-Italic"
ww_register_font LiberationSans-Regular.ttf "LiberationSans-Regular"
ww_register_font LiberationSerif-BoldItalic.ttf "LiberationSerif-BoldItalic"
ww_register_font LiberationSerif-Bold.ttf "LiberationSerif-Bold"
ww_register_font LiberationSerif-Italic.ttf "LiberationSerif-Italic"
ww_register_font LiberationSerif-Regular.ttf "LiberationSerif-Regular"
}

#---------------------------------------------------------------------------------------

ww_download_lucida()
{
ww_download 64c47ad92265f6f10b0fd909a703d4fd1b05b2d5 'lucida.exe' 'ftp://ftp.fu-berlin.de/pc/security/ms-patches/winnt/usa/NT40TSE/hotfixes-postSP3/Euro-fix/eurofixi.exe' '' 
}

ww_check_lucida()
{
ww_exists "$WW_FONTS/lucon.ttf"
}

ww_install_lucida()
{
ww_cabextract -d "$WW_FONTS" -L -F 'lucon.ttf' "$WW_CACHE"/lucida.exe
ww_register_font lucon.ttf "Lucida Console"
}

#---------------------------------------------------------------------------------------

ww_download_mdac27()
{
ww_download f68594d1f578c3b47bf0639c46c11c5da161feee 'mdac27.exe' 'https://web.archive.org/web/20080731135848/http://download.microsoft.com/download/3/b/f/3bf74b01-16ba-472d-9a8c-42b2b4fa0d76/mdac_typ.exe' '' 
}

ww_check_mdac27()
{
ww_native "$WW_COMMON_FILES/System/ADO/msado26.tlb"
}

ww_install_mdac27()
{
ww_install native_mdac
ww_set_winver nt40
ww_cd_repo_wine mdac27.exe /q /C:"setup $WW_UNATTENDED_SLASH_QNT"
ww_unset_winver
}

#---------------------------------------------------------------------------------------

ww_download_mdac28()
{
ww_download 4fbc272c79da59e38818924d8575accb0af776fb 'mdac28.exe' 'http://download.microsoft.com/download/4/a/a/4aafff19-9d21-4d35-ae81-02c48dcbbbff/MDAC_TYP.EXE' '' 
}

ww_check_mdac28()
{
ww_native "$WW_COMMON_FILES/System/ADO/msado27.tlb"
}

ww_install_mdac28()
{
ww_install native_mdac
ww_set_winver nt40
ww_cd_repo_wine mdac28.exe /q /C:"setup $WW_UNATTENDED_SLASH_QNT"
ww_unset_winver
}

#---------------------------------------------------------------------------------------

ww_download_mdx()
{
ww_dx_feb2010_download
}

ww_check_mdx()
{
ww_native "$WW_WINDOWS/assembly/GAC/microsoft.directx/1.0.2902.0__31bf3856ad364e35/microsoft.directx.dll"
}

ww_install_mdx()
{
ww_cd "$WW_TEMP"

ww_cabextract -F "*MDX*" "$WW_DX_FEB_PATH"
ww_cabextract -F "*.cab" *Archive.cab

ww_cabextract -d "$WW_WINDOWS/Microsoft.NET/DirectX for Managed Code/1.0.2902.0" -F "microsoft.directx*" *MDX1_x86.cab
for file in mdx_*.cab
do
    ver="${file%%_x86.cab}"
    ver="${ver##mdx_}"
    ww_cabextract -d "$WW_WINDOWS/Microsoft.NET/DirectX for Managed Code/$ver" -F "microsoft.directx*" "$file"
done
ww_cabextract -d "$WW_WINDOWS/Microsoft.NET/DirectX for Managed Code/1.0.2911.0" -F "microsoft.directx.direct3dx*" *MDX1_x86.cab
ww_cd "$WW_WINDOWS/Microsoft.NET/DirectX for Managed Code"
for ver in *
do
    cd "$ver"
    for asm in *.dll
    do
        name="${asm%%.dll}"
        ww_try mkdir -p "$WW_WINDOWS/assembly/GAC/$name/${ver}__31bf3856ad364e35"
        ww_cp "$asm" "$WW_WINDOWS/assembly/GAC/$name/${ver}__31bf3856ad364e35"
    done
    cd -
done

cat > "$WW_TEMP"/asmfolders.reg <<_EOF_
REGEDIT4

[HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework\AssemblyFolders\DX_1.0.2902.0]
@="C:\\\\windows\\\\Microsoft.NET\\\\DirectX for Managed Code\\\\1.0.2902.0\\\\"

[HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework\AssemblyFolders\DX_1.0.2903.0]
@="C:\\\\windows\\\\Microsoft.NET\\\\DirectX for Managed Code\\\\1.0.2903.0\\\\"

[HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework\AssemblyFolders\DX_1.0.2904.0]
@="C:\\\\windows\\\\Microsoft.NET\\\\DirectX for Managed Code\\\\1.0.2904.0\\\\"

[HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework\AssemblyFolders\DX_1.0.2905.0]
@="C:\\\\windows\\\\Microsoft.NET\\\\DirectX for Managed Code\\\\1.0.2905.0\\\\"

[HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework\AssemblyFolders\DX_1.0.2906.0]
@="C:\\\\windows\\\\Microsoft.NET\\\\DirectX for Managed Code\\\\1.0.2906.0\\\\"

[HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework\AssemblyFolders\DX_1.0.2907.0]
@="C:\\\\windows\\\\Microsoft.NET\\\\DirectX for Managed Code\\\\1.0.2907.0\\\\"

[HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework\AssemblyFolders\DX_1.0.2908.0]
@="C:\\\\windows\\\\Microsoft.NET\\\\DirectX for Managed Code\\\\1.0.2908.0\\\\"

[HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework\AssemblyFolders\DX_1.0.2909.0]
@="C:\\\\windows\\\\Microsoft.NET\\\\DirectX for Managed Code\\\\1.0.2909.0\\\\"

[HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework\AssemblyFolders\DX_1.0.2910.0]
@="C:\\\\windows\\\\Microsoft.NET\\\\DirectX for Managed Code\\\\1.0.2910.0\\\\"

[HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework\AssemblyFolders\DX_1.0.2911.0]
@="C:\\\\windows\\\\Microsoft.NET\\\\DirectX for Managed Code\\\\1.0.2911.0\\\\"
_EOF_
ww_regedit "$WW_TEMP_WIN"\\asmfolders.reg

}

#---------------------------------------------------------------------------------------

ww_download_mf()
{
ww_download c3516bc5c9e69fee6d9ac4f981f5b95977a8a2fa 'win7sp1.exe' 'http://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/windows6.1-KB976932-X86.exe' '' 
}

ww_check_mf()
{
ww_native "$WW_SYSTEM32/mf.dll"
}

ww_install_mf()
{
ww_win7sp1_helper x86_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_9e6699276b03c38e/mf.dll
ww_cp "$WW_TEMP/x86_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_9e6699276b03c38e/mf.dll" "$WW_SYSTEM32/mf.dll"

ww_override native,builtin mf
}

#---------------------------------------------------------------------------------------

ww_download_mfc40()
{
ww_download 53c570e2c811674d6e4fa46cff5a3a04cd0ffc24 'mfc40.cab' 'https://web.archive.org/web/20070316220826/http://activex.microsoft.com/controls/vc/mfc40.cab' '' 
}

ww_check_mfc40()
{
ww_native "$WW_SYSTEM32/mfc40.dll"
}

ww_install_mfc40()
{
ww_cabextract -d "$WW_TEMP" "$WW_CACHE"/mfc40.cab
ww_cabextract -d "$WW_SYSTEM32" -F *40.dll "$WW_TEMP"/mfc40.exe
}

#---------------------------------------------------------------------------------------

ww_download_mfc42()
{
ww_download a8c4dd33e281c166488846a10edf97ff0ce37044 'vcrun6.exe' 'http://download.microsoft.com/download/vc60pro/Update/2/W9XNT4/EN-US/VC6RedistSetup_deu.exe' '' 
}

ww_check_mfc42()
{
ww_native "$WW_SYSTEM32/mfc42u.dll"
}

ww_install_mfc42()
{
ww_vcrun6_helper

ww_cabextract "$WW_TEMP"/vcredist.exe -d "$WW_SYSTEM32" -F "mfc42*.dll"
}

#---------------------------------------------------------------------------------------

ww_download_msacm32()
{
ww_download c81472f7eeea2eca421e116cd4c03e2300ebfde4 'xpsp3.exe' 'https://web.archive.org/web/20150811102120/http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://mail.digipro.rs/Public/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://soporte.uson.mx/UTILES/04_SERVICE_PACKS/Windows/XP/SP3/ingles/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://ftp.sae24.ru/tools/System/M%24win_SP/xp_sp3/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 
}

ww_check_msacm32()
{
ww_native "$WW_SYSTEM32/msacm32.dll"
}

ww_install_msacm32()
{
ww_xpsp3_helper i386/msacm32.dl_
ww_cabextract -d "$WW_SYSTEM32" "$WW_TEMP"/i386/msacm32.dl_
ww_override native,builtin msacm32
}

#---------------------------------------------------------------------------------------

ww_download_msasn1()
{
ww_download fadea6d94a014b039839fecc6e6a11c20afa4fa8 'win2ksp4.exe' 'ftp://ftp.vcitynet.com/win32/win2k/W2KSP4_EN.EXE' '' 'http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 'https://web.archive.org/web/20160129053851/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 
}

ww_check_msasn1()
{
ww_native "$WW_SYSTEM32/msasn1.dll"
}

ww_install_msasn1()
{
ww_win2ksp4_helper i386/msasn1.dl_
ww_cabextract -d "$WW_SYSTEM32" "$WW_TEMP"/i386/msasn1.dl_
}

#---------------------------------------------------------------------------------------

ww_download_msctf()
{
ww_download c81472f7eeea2eca421e116cd4c03e2300ebfde4 'xpsp3.exe' 'https://web.archive.org/web/20150811102120/http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://mail.digipro.rs/Public/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://soporte.uson.mx/UTILES/04_SERVICE_PACKS/Windows/XP/SP3/ingles/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://ftp.sae24.ru/tools/System/M%24win_SP/xp_sp3/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 
}

ww_check_msctf()
{
ww_native "$WW_SYSTEM32/msctf.dll"
}

ww_install_msctf()
{
ww_xpsp3_helper i386/msctf.dl_
ww_cabextract -d "$WW_SYSTEM32" "$WW_TEMP"/i386/msctf.dl_
ww_override native,builtin msctf
}

#---------------------------------------------------------------------------------------

ww_download_msdxmocx()
{
ww_download 99691df6ac455233230faac7514bdea781ba0ce3 'msdxmocx.exe' 'ftp://www.define.fi/Pub/Fixes/Microsoft/Windows%2095/mpfull.exe' '' 
}

ww_check_msdxmocx()
{
ww_native "$WW_SYSTEM32/msdxm.ocx"
}

ww_install_msdxmocx()
{
ww_cabextract -d "$WW_SYSTEM32" "$WW_CACHE/msdxmocx.exe"
ww_regsvr msdxm.ocx
}

#---------------------------------------------------------------------------------------

ww_download_msflxgrd()
{
ww_download 3d6c04e923781d4ce0d3ab62189b8de352ab25d5 'msflxgrd.cab' 'ftp://dns24289.dizinc.com/TEMP/vb6%20sp6%20install/MSFlxGrd.CAB' '' 
}

ww_check_msflxgrd()
{
ww_native "$WW_SYSTEM32/MSFLXGRD.OCX"
}

ww_install_msflxgrd()
{
ww_cabextract -d "$WW_TEMP" "$WW_CACHE"/msflxgrd.cab
ww_cp "$WW_TEMP"/[Mm][Ss][Ff][Ll][Xx][Gg][Rr][Dd].[Oo][Cc][Xx] "$WW_SYSTEM32"
ww_regsvr MSFLXGRD.OCX
}

#---------------------------------------------------------------------------------------

ww_download_msftedit()
{
ww_download c3516bc5c9e69fee6d9ac4f981f5b95977a8a2fa 'win7sp1.exe' 'http://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/windows6.1-KB976932-X86.exe' '' 
}

ww_check_msftedit()
{
ww_native "$WW_SYSTEM32/msftedit.dll"
}

ww_install_msftedit()
{
ww_win7sp1_helper x86_microsoft-windows-msftedit_31bf3856ad364e35_6.1.7601.17514_none_d7d862f19573a5ff/msftedit.dll
ww_cp "$WW_TEMP/x86_microsoft-windows-msftedit_31bf3856ad364e35_6.1.7601.17514_none_d7d862f19573a5ff/msftedit.dll" "$WW_SYSTEM32/msftedit.dll"

ww_override native,builtin mstfedit
}

#---------------------------------------------------------------------------------------

ww_download_mshflxgd()
{
ww_download 5f9c7a81022949bfe39b50f2bbd799c448bb7377 'mshflxgd.cab' 'ftp://dns24289.dizinc.com/TEMP/vb6%20sp6%20install/MSHFlxGd.CAB' '' 
}

ww_check_mshflxgd()
{
ww_native "$WW_SYSTEM32/MSHFLXGD.OCX"
}

ww_install_mshflxgd()
{
ww_cabextract -d "$WW_TEMP" "$WW_CACHE"/mshflxgd.cab
ww_cp "$WW_TEMP"/[Mm][Ss][Hh][Ff][Ll][Xx][Gg][Dd].[Oo][Cc][Xx] "$WW_SYSTEM32"
ww_regsvr MSHFLXGD.OCX
}

#---------------------------------------------------------------------------------------

ww_download_msls31()
{
ww_download 4fc3bf0dc96b5cf5ab26430fac1c33c5c50bd142 'msls31.exe' 'https://web.archive.org/web/20160710055851/http://download.microsoft.com/download/WindowsInstaller/Install/2.0/NT45/EN-US/InstMsiW.exe' '' 
}

ww_check_msls31()
{
ww_native "$WW_SYSTEM32/msls31.dll"
}

ww_install_msls31()
{
ww_cabextract -d "$WW_TEMP" "$WW_CACHE"/msls31.exe
ww_cp "$WW_TEMP"/msls31.dll "$WW_SYSTEM32"
}

#---------------------------------------------------------------------------------------

ww_download_msmask()
{
ww_download bdd2bb3a32d18926a048f302aff18b1e6d250d9d 'msmask.cab' 'ftp://dns24289.dizinc.com/TEMP/vb6%20sp6%20install/MSMask32.CAB' '' 
}

ww_check_msmask()
{
ww_native "$WW_SYSTEM32/msmask32.ocx"
}

ww_install_msmask()
{
ww_cabextract -d "$WW_TEMP" "$WW_CACHE"/msmask.cab
ww_cp "$WW_TEMP"/[Mm][Ss][Mm][Aa][Ss][Kk]32.[Oo][Cc][Xx] "$WW_SYSTEM32"/msmask32.ocx
ww_regsvr msmask32.ocx
}

#---------------------------------------------------------------------------------------

ww_download_mspatcha()
{
ww_download fadea6d94a014b039839fecc6e6a11c20afa4fa8 'win2ksp4.exe' 'ftp://ftp.vcitynet.com/win32/win2k/W2KSP4_EN.EXE' '' 'http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 'https://web.archive.org/web/20160129053851/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 
}

ww_check_mspatcha()
{
ww_native "$WW_SYSTEM32/mspatcha.dll"
}

ww_install_mspatcha()
{
ww_win2ksp4_helper i386/mspatcha.dl_
ww_cabextract -d "$WW_SYSTEM32" "$WW_TEMP"/i386/mspatcha.dl_

ww_override native,builtin mspatcha
}

#---------------------------------------------------------------------------------------

ww_download_msscript()
{
ww_download fd9f2f23357ab11ae70682d6864f7e9f188adf2a 'msscript.exe' 'https://web.archive.org/web/20160327122736/http://download.microsoft.com/download/d/2/a/d2a7430c-6d5b-48e9-96c4-3c751be7bffe/sct10en.exe' '' 'ftp://94.226.105.180/Public/Test/c_drive/OidView/sct10en.exe' '' 
}

ww_check_msscript()
{
ww_native "$WW_SYSTEM32/msscript.ocx"
}

ww_install_msscript()
{
ww_cabextract -d "$WW_TEMP" "$WW_CACHE"/msscript.exe
ww_cp "$WW_TEMP"/msscript.ocx "$WW_SYSTEM32"
ww_regsvr msscript.ocx
}

#---------------------------------------------------------------------------------------

ww_download_msvcirt()
{
ww_download a8c4dd33e281c166488846a10edf97ff0ce37044 'vcrun6.exe' 'http://download.microsoft.com/download/vc60pro/Update/2/W9XNT4/EN-US/VC6RedistSetup_deu.exe' '' 
}

ww_check_msvcirt()
{
ww_native "$WW_SYSTEM32/msvcirt.dll"
}

ww_install_msvcirt()
{
ww_vcrun6_helper
ww_cabextract "$WW_TEMP"/vcredist.exe -d "$WW_SYSTEM32" -F msvcirt.dll
}

#---------------------------------------------------------------------------------------

ww_download_msxml3()
{
ww_download d4c2178dfb807e1a0267fce0fd06b8d51106d913 'msxml3.msi' 'ftp://85.66.4.250/E_meghajto/ZOLI_C_SAVE/Documents%20and%20Settings/Docsis/Local%20Settings/Temp/NERO14767/Data/Redist/msxml3.msi' '' 
}

ww_check_msxml3()
{
ww_native "$WW_SYSTEM32/msxml3.dll"
}

ww_install_msxml3()
{
rm "$WW_SYSTEM32"/msxml3.dll
ww_override native msxml3
ww_cd_repo_wine msiexec /i msxml3.msi $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_msxml4()
{
ww_download aa70c5c1a7a069af824947bcda1d9893a895318b 'msxml4.msi' 'http://download.microsoft.com/download/A/2/D/A2D8587D-0027-4217-9DAD-38AFDB0A177E/msxml.msi' '' 
}

ww_check_msxml4()
{
ww_native "$WW_SYSTEM32/msxml4.dll"
}

ww_install_msxml4()
{
ww_override native,builtin msxml4
ww_cd_repo_wine msiexec /i msxml4.msi $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_msxml6()
{
ww_download 5125220e985b33c946bbf9f60e2b222c7570bfa2 'msxml6.msi' 'http://download.microsoft.com/download/e/a/f/eafb8ee7-667d-4e30-bb39-4694b5b3006f/msxml6_x86.msi' '' 
}

ww_check_msxml6()
{
ww_native "$WW_SYSTEM32/msxml6.dll"
}

ww_install_msxml6()
{
ww_override native,builtin msxml6
rm -f "$WW_SYSTEM32/msxml6.dll"
ww_wine msiexec /i "$WW_CACHE"/msxml6.msi $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_multisampling_disabled()
{
:
}

ww_check_multisampling_disabled()
{
false
}

ww_install_multisampling_disabled()
{
ww_set_wined3d_var Multisampling disabled
}

#---------------------------------------------------------------------------------------

ww_download_multisampling_enabled()
{
:
}

ww_check_multisampling_enabled()
{
false
}

ww_install_multisampling_enabled()
{
ww_set_wined3d_var Multisampling enabled
}

#---------------------------------------------------------------------------------------

ww_download_mwo_disable()
{
:
}

ww_check_mwo_disable()
{
false
}

ww_install_mwo_disable()
{
ww_set_mwo disable
}

#---------------------------------------------------------------------------------------

ww_download_mwo_enabled()
{
:
}

ww_check_mwo_enabled()
{
false
}

ww_install_mwo_enabled()
{
ww_set_mwo enabled
}

#---------------------------------------------------------------------------------------

ww_download_mwo_force()
{
:
}

ww_check_mwo_force()
{
false
}

ww_install_mwo_force()
{
ww_set_mwo force
}

#---------------------------------------------------------------------------------------

ww_download_native_mdac()
{
:
}

ww_check_native_mdac()
{
false
}

ww_install_native_mdac()
{
ww_override native,builtin odbc32 odbccp32 oledb32
}

#---------------------------------------------------------------------------------------

ww_download_native_oleaut32()
{
:
}

ww_check_native_oleaut32()
{
false
}

ww_install_native_oleaut32()
{
ww_override native,builtin oleaut32
}

#---------------------------------------------------------------------------------------

ww_download_nocrashdialog()
{
:
}

ww_check_nocrashdialog()
{
false
}

ww_install_nocrashdialog()
{
info "Disabling graphical crash dialog"
cat > "$WW_TEMP"/crashdialog.reg <<_EOF_
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\WineDbg]
"ShowCrashDialog"=dword:00000000

_EOF_
ww_regedit "$WW_TEMP_WIN\\crashdialog.reg"
}

#---------------------------------------------------------------------------------------

ww_download_npm_repack()
{
:
}

ww_check_npm_repack()
{
false
}

ww_install_npm_repack()
{
ww_set_wined3d_var NonPower2Mode repack
}

#---------------------------------------------------------------------------------------

ww_download_nuget()
{
ww_download 58da3d74db353aad03588cbb5cea8234166d8b99 'dotnet40.exe' 'http://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe' '' 
ww_download dc506536b72c4a523244f9128d1ba6a094655a71 'nuget.exe' 'https://nuget.org/nuget.exe' '' 
}

ww_check_nuget()
{
ww_native "$WW_SYSTEM32/nuget.exe"
}

ww_install_nuget()
{
ww_install dotnet40

ww_cp "$WW_CACHE"/nuget.exe "$WW_SYSTEM32"
ww_warn "To run nuget, use the file \"$WW_SYSTEM32/nuget.exe\"."
}

#---------------------------------------------------------------------------------------

ww_download_ogg()
{
ww_download 386cf7cd29ffcbf8705eff8c8233de448ecf33ab 'ogg.exe' 'http://downloads.xiph.org/releases/oggdsf/opencodecs_0.85.17777.exe' '' 
}

ww_check_ogg()
{
ww_native "$WW_PROGRAM_FILES/Xiph.Org/Open Codecs/AxPlayer.dll"
}

ww_install_ogg()
{
ww_cd_repo_wine ogg.exe $WW_UNATTENDED_SLASH_S
}

#---------------------------------------------------------------------------------------

ww_download_opensymbol()
{
ww_download d3e2dd921c6694d24865600e40eceaf2a635d1c6 'opensymbol.deb' 'http://security.debian.org/debian-security/pool/updates/main/libr/libreoffice/fonts-opensymbol_102.6+LibO4.3.3-2+deb8u3_all.deb' '' 'https://web.archive.org/web/20160414161149/http://security.debian.org/debian-security/pool/updates/main/libr/libreoffice/fonts-opensymbol_102.6+LibO4.3.3-2+deb8u3_all.deb' '' 
}

ww_check_opensymbol()
{
ww_exists "$WW_FONTS/opens___.ttf"
}

ww_install_opensymbol()
{
cd "$WW_TEMP"
ww_try ar x "$WW_CACHE/opensymbol.deb" data.tar.xz
ww_try tar Jvxf data.tar.xz ./usr/share/fonts/truetype/openoffice/opens___.ttf
ww_try mv "$WW_TEMP/usr/share/fonts/truetype/openoffice/opens___.ttf" "$WW_FONTS"
ww_register_font opens___.ttf "OpenSymbol"
}

#---------------------------------------------------------------------------------------

ww_download_orm_backbuffer()
{
:
}

ww_check_orm_backbuffer()
{
false
}

ww_install_orm_backbuffer()
{
ww_set_wined3d_var OffscreenRenderingMode backbuffer
}

#---------------------------------------------------------------------------------------

ww_download_orm_fbo()
{
:
}

ww_check_orm_fbo()
{
false
}

ww_install_orm_fbo()
{
ww_set_wined3d_var OffscreenRenderingMode fbo
}

#---------------------------------------------------------------------------------------

ww_download_pdh()
{
ww_download f42448660def8cd7f42b34aa7bc7264745f4425e 'pdh.exe' 'http://download.microsoft.com/download/platformsdk/Redist/5.0.2195.2668/NT4/EN-US/pdhinst.exe' '' 
}

ww_check_pdh()
{
ww_native "$WW_SYSTEM32/pdh.dll"
}

ww_install_pdh()
{
ww_cabextract -d "$WW_TEMP" "$WW_CACHE"/pdh.exe
ww_unzip "$WW_TEMP" "$WW_TEMP"/pdh.exe
ww_cp "$WW_TEMP"/x86/Pdh.Dll "$WW_SYSTEM32"/pdh.dll
}

#---------------------------------------------------------------------------------------

ww_download_physx()
{
ww_download 81e2d38e2356e807ad80cdf150ed5acfff839c8b 'physx.msi' 'http://uk.download.nvidia.com/Windows/9.14.0702/PhysX-9.14.0702-SystemSoftware.msi' '' 
}

ww_check_physx()
{
ww_native "$WW_PROGRAM_FILES/NVIDIA Corporation/PhysX/Engine/v2.8.3/PhysXCore.dll"
}

ww_install_physx()
{
ww_cd_repo_wine msiexec /i physx.msi $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_pngfilt()
{
ww_download 6f5db296ebf58e81c49bc667049a3f88a3f1ec3d 'pngfilt.exe' 'https://web.archive.org/web/20061224003406/http://download.microsoft.com/download/5/0/c/50c42d0e-07a8-4a2b-befb-1a403bd0df96/IE5.01sp4-KB871260-Windows2000sp4-x86-ENU.exe' '' 
}

ww_check_pngfilt()
{
ww_native "$WW_SYSTEM32/pngfilt.dll"
}

ww_install_pngfilt()
{
ww_cabextract -d "$WW_SYSTEM32" -L -F pngfilt.dll "$WW_CACHE"/pngfilt.exe
ww_regsvr pngfilt.dll
}

#---------------------------------------------------------------------------------------

ww_download_postinstall_script()
{
ww_download 3a6b38137f59f1f61a456a55c6c0edd77f2d8324 linux32.special 'https://raw.githubusercontent.com/LLIAKAJL/WineWizard-Utils/master/linux32.special' ''
}

ww_check_postinstall_script()
{
false
}

ww_install_postinstall_script()
{
echo "Special script started..."
eval "$(cat "$WW_CACHE"/linux32.special)"
ww_special_script_execute $WW_APP_ID post
echo "Special script finished"
}

#---------------------------------------------------------------------------------------

ww_download_preinstall_script()
{
ww_download 3a6b38137f59f1f61a456a55c6c0edd77f2d8324 linux32.special 'https://raw.githubusercontent.com/LLIAKAJL/WineWizard-Utils/master/linux32.special' ''
}

ww_check_preinstall_script()
{
false
}

ww_install_preinstall_script()
{
echo "Special script started..."
eval "$(cat "$WW_CACHE"/linux32.special)"
ww_special_script_execute $WW_APP_ID pre
echo "Special script finished"
}

#---------------------------------------------------------------------------------------

ww_download_psm_0()
{
:
}

ww_check_psm_0()
{
false
}

ww_install_psm_0()
{
ww_set_wined3d_var MaxShaderModelPS 0
}

#---------------------------------------------------------------------------------------

ww_download_psm_1()
{
:
}

ww_check_psm_1()
{
false
}

ww_install_psm_1()
{
ww_set_wined3d_var MaxShaderModelPS 1
}

#---------------------------------------------------------------------------------------

ww_download_psm_2()
{
:
}

ww_check_psm_2()
{
false
}

ww_install_psm_2()
{
ww_set_wined3d_var MaxShaderModelPS 2
}

#---------------------------------------------------------------------------------------

ww_download_psm_3()
{
:
}

ww_check_psm_3()
{
false
}

ww_install_psm_3()
{
ww_set_wined3d_var MaxShaderModelPS 3
}

#---------------------------------------------------------------------------------------

ww_download_python26()
{
ww_download b3981b13fbc45823131f69d125992d6330212f27 'ahk.zip' 'http://www.autohotkey.com/download/AutoHotkey104805.zip' '' 
ww_download eca58f29b810d8e3e7951277ebb3e35ac35794a3 'python26.exe' 'http://downloads.sourceforge.net/project/pywin32/pywin32/Build%20214/pywin32-214.win32-py2.6.exe' '' 
ww_download 2d1503b0e8b7e4c72a276d4d9027cf4856b208b8 'python26.msi' 'http://www.python.org/ftp/python/2.6.2/python-2.6.2.msi' '' 
}

ww_check_python26()
{
ww_native "$WW_C/Python26/python.exe"
}

ww_install_python26()
{
if [ "$WW_WINE_VERSION" = "wine-1.4.1" ]
then
    ww_die "This installer is broken under $WW_WINE_VERSION. Please set another Wine. See https://code.google.com/p/winetricks/issues/detail?id=347 for more info."
fi

ww_cd_repo_wine msiexec /i python26.msi ALLUSERS=1 $WW_UNATTENDED_SLASH_Q

ww_ahk "
    SetTitleMatchMode, 2
    run python26.exe
    WinWait, Setup, Wizard will install pywin32
    ControlClick Button2
    WinWait, Setup, Python 2.6 is required
    ControlClick Button3
    WinWait, Setup, Click Next to begin
    ControlClick Button3
    WinWait, Setup, finished
    ControlClick Button4
    WinWaitClose
"
}

#---------------------------------------------------------------------------------------

ww_download_qdvd()
{
ww_dx_feb2010_download
}

ww_check_qdvd()
{
ww_native "$WW_SYSTEM32/qdvd.dll"
}

ww_install_qdvd()
{
ww_cabextract -d "$WW_TEMP" -L -F dxnt.cab "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F qdvd.dll "$WW_TEMP/dxnt.cab"

ww_regsvr qdvd.dll

ww_override native qdvd
}

#---------------------------------------------------------------------------------------

ww_download_quartz()
{
ww_dx_feb2010_download
}

ww_check_quartz()
{
ww_native "$WW_SYSTEM32/quartz.dll"
}

ww_install_quartz()
{
ww_cabextract -d "$WW_TEMP" -L -F dxnt.cab "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_SYSTEM32" -L -F quartz.dll "$WW_TEMP/dxnt.cab"

ww_regsvr quartz.dll

ww_override native quartz
}

#---------------------------------------------------------------------------------------

ww_download_quicktime72()
{
ww_download bb89981f10cf21de57b9453e53cf81b9194271a9 'quicktime72.exe' 'http://appldnld.apple.com.edgesuite.net/content.info.apple.com/QuickTime/061-2915.20070710.pO94c/QuickTimeInstaller.exe' '' 
}

ww_check_quicktime72()
{
ww_exists "$WW_WINDOWS/Installer/{95A890AA-B3B1-44B6-9C18-A8F7AB3EE7FC}/QTPlayer.ico"
}

ww_install_quicktime72()
{
ww_cd_repo_wine quicktime72.exe ALLUSERS=1 DESKTOP_SHORTCUTS=0 QTTaskRunFlags=0 QTINFO.BISQTPRO=1 SCHEDULE_ASUW=0 REBOOT_REQUIRED=No $WW_UNATTENDED_SLASH_QN > /dev/null 2>&1

if ww_workaround_wine_bug 11681
then
    ww_warn "In Quicktime preferences, check Advanced / Safe Mode (gdi), or movies won't play."
    :
fi
}

#---------------------------------------------------------------------------------------

ww_download_quicktime76()
{
ww_download 1eec8904f041d9e0ad3459788bdb690e45dbc38e 'quicktime76.exe' 'http://appldnld.apple.com/QuickTime/041-0025.20101207.Ptrqt/QuickTimeInstaller.exe' '' 
}

ww_check_quicktime76()
{
ww_exists "$WW_WINDOWS/Installer/{57752979-A1C9-4C02-856B-FBB27AC4E02C}/QTPlayer.ico"
}

ww_install_quicktime76()
{
ww_cd_repo_wine quicktime76.exe ALLUSERS=1 DESKTOP_SHORTCUTS=0 QTTaskRunFlags=0 QTINFO.BISQTPRO=1 SCHEDULE_ASUW=0 REBOOT_REQUIRED=No $WW_UNATTENDED_SLASH_QN > /dev/null 2>&1

if ww_workaround_wine_bug 11681
then
    ww_warn "In Quicktime preferences, check Advanced / Safe Mode (gdi), or movies won't play."
    :
fi
}

#---------------------------------------------------------------------------------------

ww_download_riched20()
{
ww_download 4fc3bf0dc96b5cf5ab26430fac1c33c5c50bd142 'msls31.exe' 'https://web.archive.org/web/20160710055851/http://download.microsoft.com/download/WindowsInstaller/Install/2.0/NT45/EN-US/InstMsiW.exe' '' 
ww_download fadea6d94a014b039839fecc6e6a11c20afa4fa8 'win2ksp4.exe' 'ftp://ftp.vcitynet.com/win32/win2k/W2KSP4_EN.EXE' '' 'http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 'https://web.archive.org/web/20160129053851/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 
}

ww_check_riched20()
{
ww_native "$WW_SYSTEM32/riched20.dll"
}

ww_install_riched20()
{
ww_win2ksp4_helper i386/riched20.dl_
ww_cabextract -d "$WW_SYSTEM32" "$WW_TEMP"/i386/riched20.dl_
ww_override native,builtin riched20

ww_install msls31
}

#---------------------------------------------------------------------------------------

ww_download_riched30()
{
ww_download e739c40d747e7c27aacdb07b50925b1635ee7366 'instmsia.exe' 'http://download.microsoft.com/download/WindowsInstaller/Install/2.0/W9XMe/EN-US/InstMsiA.exe' '' 
}

ww_check_riched30()
{
ww_native "$WW_SYSTEM32/riched20.dll" && ww_native "$WW_SYSTEM32/msls31.dll"
}

ww_install_riched30()
{
ww_cabextract -d "$WW_TEMP" "$WW_CACHE"/instmsia.exe
ww_cp "$WW_TEMP"/riched20.dll "$WW_SYSTEM32"
ww_cp "$WW_TEMP"/msls31.dll "$WW_SYSTEM32"
ww_override native,builtin riched20
}

#---------------------------------------------------------------------------------------

ww_download_richtx32()
{
ww_download da404b566df3ad74fe687c39404a36c3e7cadc07 'richtx32.cab' 'ftp://111.122.210.98/linux/winetricks/richtx32/richtx32.cab' '' 
}

ww_check_richtx32()
{
ww_native "$WW_SYSTEM32/RichTx32.Ocx"
}

ww_install_richtx32()
{
ww_cabextract "$WW_CACHE"/richtx32.cab -d "$WW_SYSTEM32" -F RichTx32.ocx
ww_regsvr RichTx32.ocx
}

#---------------------------------------------------------------------------------------

ww_download_rtlm_auto()
{
:
}

ww_check_rtlm_auto()
{
false
}

ww_install_rtlm_auto()
{
ww_set_wined3d_var RenderTargetLockMode auto
}

#---------------------------------------------------------------------------------------

ww_download_rtlm_disabled()
{
:
}

ww_check_rtlm_disabled()
{
false
}

ww_install_rtlm_disabled()
{
ww_set_wined3d_var RenderTargetLockMode disabled
}

#---------------------------------------------------------------------------------------

ww_download_rtlm_readdraw()
{
:
}

ww_check_rtlm_readdraw()
{
false
}

ww_install_rtlm_readdraw()
{
ww_set_wined3d_var RenderTargetLockMode readdraw
}

#---------------------------------------------------------------------------------------

ww_download_rtlm_readtex()
{
:
}

ww_check_rtlm_readtex()
{
false
}

ww_install_rtlm_readtex()
{
ww_set_wined3d_var RenderTargetLockMode readtex
}

#---------------------------------------------------------------------------------------

ww_download_rtlm_texdraw()
{
:
}

ww_check_rtlm_texdraw()
{
false
}

ww_install_rtlm_texdraw()
{
ww_set_wined3d_var RenderTargetLockMode texdraw
}

#---------------------------------------------------------------------------------------

ww_download_rtlm_textex()
{
:
}

ww_check_rtlm_textex()
{
false
}

ww_install_rtlm_textex()
{
ww_set_wined3d_var RenderTargetLockMode textex
}

#---------------------------------------------------------------------------------------

ww_download_sdl()
{
ww_download d22c71d1c2bdf283548187c4b0bd7ef9d0c1fb23 'sdl.zip' 'http://www.libsdl.org/release/SDL-1.2.14-win32.zip' '' 
}

ww_check_sdl()
{
ww_native "$WW_SYSTEM32/SDL.dll"
}

ww_install_sdl()
{
ww_unzip "$WW_SYSTEM32" "$WW_CACHE"/sdl.zip SDL.dll
}

#---------------------------------------------------------------------------------------

ww_download_secur32()
{
ww_download bf930a4d2982165a0793465bb255d494ba5b4cf7 'secur32.exe' 'ftp://111.122.210.98/linux/winetricks/secur32/Windows2000-KB959426-x86-ENU.EXE' '' 
}

ww_check_secur32()
{
ww_native "$WW_SYSTEM32/secur32.dll"
}

ww_install_secur32()
{
ww_cabextract "$WW_CACHE"/secur32.exe -d "$WW_SYSTEM32" -F secur32.dll
ww_override native,builtin secur32
}

#---------------------------------------------------------------------------------------

ww_download_setupapi()
{
ww_download c81472f7eeea2eca421e116cd4c03e2300ebfde4 'xpsp3.exe' 'https://web.archive.org/web/20150811102120/http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://mail.digipro.rs/Public/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://soporte.uson.mx/UTILES/04_SERVICE_PACKS/Windows/XP/SP3/ingles/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://ftp.sae24.ru/tools/System/M%24win_SP/xp_sp3/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 
}

ww_check_setupapi()
{
ww_native "$WW_SYSTEM32/setupapi.dll"
}

ww_install_setupapi()
{
ww_xpsp3_helper i386/setupapi.dl_
ww_cabextract -d "$WW_SYSTEM32" "$WW_TEMP"/i386/setupapi.dl_

ww_override native,builtin setupapi
}

#---------------------------------------------------------------------------------------

ww_download_shockwave()
{
ww_download 4f955f42984ae69d2f6078d3a3fe9fadc4a25e34 'shockwave.msi' 'http://fpdownload.macromedia.com/get/shockwave/default/english/win95nt/latest/sw_lic_full_installer.msi' '' 
}

ww_check_shockwave()
{
ww_exists "$WW_SYSTEM32/Adobe/Shockwave 12/shockwave_Projector_Loader.dcr"
}

ww_install_shockwave()
{
ww_cd_repo_wine msiexec /i shockwave.msi $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_sound_alsa()
{
:
}

ww_check_sound_alsa()
{
false
}

ww_install_sound_alsa()
{
ww_set_sound alsa
}

#---------------------------------------------------------------------------------------

ww_download_sound_coreaudio()
{
:
}

ww_check_sound_coreaudio()
{
false
}

ww_install_sound_coreaudio()
{
ww_set_sound coreaudio
}

#---------------------------------------------------------------------------------------

ww_download_sound_disabled()
{
:
}

ww_check_sound_disabled()
{
false
}

ww_install_sound_disabled()
{
ww_set_sound disabled
}

#---------------------------------------------------------------------------------------

ww_download_sound_oss()
{
:
}

ww_check_sound_oss()
{
false
}

ww_install_sound_oss()
{
ww_set_sound oss
}

#---------------------------------------------------------------------------------------

ww_download_sound_pulse()
{
:
}

ww_check_sound_pulse()
{
false
}

ww_install_sound_pulse()
{
ww_set_sound pulse
}

#---------------------------------------------------------------------------------------

ww_download_speechsdk()
{
ww_download f69efaee8eb47f8c7863693e8b8265a3c12c4f51 'speechsdk.exe' 'http://download.microsoft.com/download/B/4/3/B4314928-7B71-4336-9DE7-6FA4CF00B7B3/SpeechSDK51.exe' '' 
}

ww_check_speechsdk()
{
ww_native "$WW_PROGRAM_FILES/Microsoft Speech SDK 5.1/Bin/SAPI51SampleApp.exe"
}

ww_install_speechsdk()
{
ww_unzip "$WW_TEMP" "$WW_CACHE"/speechsdk.exe

ww_set_winver win2k

ww_cd "$WW_TEMP"
ww_wine msiexec /i "Microsoft Speech SDK 5.1.msi" $WW_UNATTENDED_SLASH_Q

ww_unset_winver
}

#---------------------------------------------------------------------------------------

ww_download_strictdrawordering_disabled()
{
:
}

ww_check_strictdrawordering_disabled()
{
false
}

ww_install_strictdrawordering_disabled()
{
ww_set_wined3d_var StrictDrawOrdering disabled
}

#---------------------------------------------------------------------------------------

ww_download_strictdrawordering_enabled()
{
:
}

ww_check_strictdrawordering_enabled()
{
false
}

ww_install_strictdrawordering_enabled()
{
ww_set_wined3d_var StrictDrawOrdering enabled
}

#---------------------------------------------------------------------------------------

ww_download_tabctl32()
{
ww_download beca51d05924a5466ab80eb0f8d0cdf8bc1ac697 'tabctl32.cab' 'https://web.archive.org/web/20110818064708/http://activex.microsoft.com/controls/vb6/TABCTL32.CAB' '' 
}

ww_check_tabctl32()
{
ww_native "$WW_SYSTEM32/tabctl32.ocx"
}

ww_install_tabctl32()
{
ww_cabextract -d "$WW_TEMP" "$WW_CACHE"/tabctl32.cab
ww_cp "$WW_TEMP"/[Tt][Aa][Bb][Cc][Tt][Ll][3][2].[Oo][Cc][Xx] "$WW_SYSTEM32"
ww_regsvr tabctl32.ocx
}

#---------------------------------------------------------------------------------------

ww_download_tahoma()
{
ww_download 888ce7b7ab5fd41f9802f3a65fd0622eb651a068 'tahoma.exe' 'http://download.microsoft.com/download/office97pro/fonts/1/w95/en-us/tahoma32.exe' '' 'https://web.archive.org/web/20160401090253/http://download.microsoft.com/download/office97pro/fonts/1/w95/en-us/tahoma32.exe' '' 
}

ww_check_tahoma()
{
ww_exists "$WW_FONTS/tahoma.ttf"
}

ww_install_tahoma()
{
ww_cabextract -d "$WW_TEMP" "$WW_CACHE"/tahoma.exe
ww_cp "$WW_TEMP"/Tahoma.TTF "$WW_FONTS"/tahoma.ttf
ww_cp "$WW_TEMP"/Tahomabd.TTF "$WW_FONTS"/tahomabd.ttf

ww_register_font tahoma.ttf "Tahoma"
ww_register_font tahomabd.ttf "Tahoma Bold"

chmod +w "$WW_FONTS"/tahoma*.ttf
}

#---------------------------------------------------------------------------------------

ww_download_takao()
{
ww_download 4f636d5c7c1bc16b96ea723adb16838cfb6df059 'takao.zip' 'http://launchpad.net/takao-fonts/trunk/003.02.01/+download/takao-fonts-ttf-003.02.01.zip' '' 
}

ww_check_takao()
{
ww_exists "$WW_FONTS/TakaoGothic.ttf"
}

ww_install_takao()
{
ww_cp "$WW_CACHE"/takao.zip "$WW_TEMP"
ww_unzip "$WW_TEMP" "$WW_TEMP"/takao.zip
ww_cp "$WW_TEMP"/takao-fonts-ttf-003.02.01/*.ttf "$WW_FONTS"

ww_register_font TakaoGothic.ttf "TakaoGothic"
ww_register_font TakaoPGothic.ttf "TakaoPGothic"
ww_register_font TakaoMincho.ttf "TakaoMincho"
ww_register_font TakaoPMincho.ttf "TakaoPMincho"
ww_register_font TakaoExGothic.ttf "TakaoExGothic"
ww_register_font TakaoExMincho.ttf "TakaoExMincho"
}

#---------------------------------------------------------------------------------------

ww_download_uff()
{
ww_download efbab0d5d8cb5cff091307d2360dcb1bfe1ae6e1 'uff.zip' 'http://font.ubuntu.com/download/ubuntu-font-family-0.70.1.zip' '' 
}

ww_check_uff()
{
ww_exists "$WW_FONTS/Ubuntu-R.ttf"
}

ww_install_uff()
{
ww_cd "$WW_TEMP"
ww_unzip . "$WW_CACHE"/uff.zip
mv ubuntu-font-family-0.70.1/*.ttf "$WW_FONTS"

ww_register_font Ubuntu-R.ttf "Ubuntu"
ww_register_font Ubuntu-I.ttf "Ubuntu Italic"
ww_register_font Ubuntu-B.ttf "Ubuntu Bold"
ww_register_font Ubuntu-BI.ttf "Ubuntu Bold Italic"
}

#---------------------------------------------------------------------------------------

ww_download_unifont()
{
ww_download bb8a3960dc0a96aa305de28312ea8a0ab64123d2 'unifont.zip' 'http://unifoundry.com/unifont-5.1.20080907.zip' '' 
}

ww_check_unifont()
{
ww_exists "$WW_FONTS/unifont.ttf"
}

ww_install_unifont()
{
cp -f "$WW_CACHE"/unifont.zip "$WW_TEMP"
ww_unzip "$WW_TEMP" "$WW_TEMP"/unifont.zip
ww_cp "$WW_TEMP"/unifont-5.1.20080907.ttf "$WW_FONTS/unifont.ttf"

ww_register_font unifont.ttf "Unifont"
ww_register_font_replacement "Arial Unicode MS" "Unifont"
}

#---------------------------------------------------------------------------------------

ww_download_updspapi()
{
ww_download c81472f7eeea2eca421e116cd4c03e2300ebfde4 'xpsp3.exe' 'https://web.archive.org/web/20150811102120/http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://mail.digipro.rs/Public/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://soporte.uson.mx/UTILES/04_SERVICE_PACKS/Windows/XP/SP3/ingles/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'ftp://ftp.sae24.ru/tools/System/M%24win_SP/xp_sp3/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 'http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe' '' 
}

ww_check_updspapi()
{
ww_native "$WW_SYSTEM32/updspapi.dll"
}

ww_install_updspapi()
{
ww_xpsp3_helper i386/update/updspapi.dll
ww_cp "$WW_TEMP"/i386/update/updspapi.dll "$WW_SYSTEM32"

ww_override native,builtin updspapi
}

#---------------------------------------------------------------------------------------

ww_download_usp10()
{
ww_download e739c40d747e7c27aacdb07b50925b1635ee7366 'instmsia.exe' 'http://download.microsoft.com/download/WindowsInstaller/Install/2.0/W9XMe/EN-US/InstMsiA.exe' '' 
}

ww_check_usp10()
{
ww_native "$WW_SYSTEM32/usp10.dll"
}

ww_install_usp10()
{
ww_cabextract -d "$WW_TEMP" "$WW_CACHE"/instmsia.exe
ww_cp "$WW_TEMP"/usp10.dll "$WW_SYSTEM32"
ww_override native,builtin usp10
}

#---------------------------------------------------------------------------------------

ww_download_vb2run()
{
ww_download ac0568b73ee375408778e9b505df995f79ab907e 'vb2run.exe' 'http://www.conradshome.com/win31/archive/softlib/vbrun200.exe' '' 
}

ww_check_vb2run()
{
ww_native "$WW_SYSTEM32/VBRUN200.DLL"
}

ww_install_vb2run()
{
ww_unzip "$WW_TEMP" "$WW_CACHE"/vb2run.exe
ww_cp "$WW_TEMP/VBRUN200.DLL" "$WW_SYSTEM32"
}

#---------------------------------------------------------------------------------------

ww_download_vb3run()
{
ww_download 518fcfefde9bf680695cadd06512efadc5ac2aa7 'vb3run.exe' 'http://download.microsoft.com/download/vb30/utility/1/w9xnt4/en-us/vb3run.exe' '' 
}

ww_check_vb3run()
{
ww_native "$WW_SYSTEM32/Vbrun300.dll"
}

ww_install_vb3run()
{
ww_unzip "$WW_TEMP" "$WW_CACHE"/vb3run.exe
ww_cp "$WW_TEMP/Vbrun300.dll" "$WW_SYSTEM32"
}

#---------------------------------------------------------------------------------------

ww_download_vb4run()
{
ww_download 83e968063272e97bfffd628a73bf0ff5f8e1023b 'vb4run.exe' 'http://download.microsoft.com/download/vb40ent/sample27/1/w9xnt4/en-us/vb4run.exe' '' 
}

ww_check_vb4run()
{
ww_native "$WW_SYSTEM32/Vb40032.dll"
}

ww_install_vb4run()
{
ww_unzip "$WW_TEMP" "$WW_CACHE"/vb4run.exe
ww_cp "$WW_TEMP/Vb40032.dll" "$WW_SYSTEM32"
ww_cp "$WW_TEMP/Vb40016.dll" "$WW_SYSTEM32"
}

#---------------------------------------------------------------------------------------

ww_download_vb5run()
{
ww_download 28bfaf09b8ac32cf5ffa81252f3e2fadcb3a8f27 'vb5run.exe' 'http://download.microsoft.com/download/vb50pro/utility/1/win98/en-us/msvbvm50.exe' '' 
}

ww_check_vb5run()
{
ww_native "$WW_SYSTEM32/msvbvm50.dll"
}

ww_install_vb5run()
{
ww_cd_repo_wine vb5run.exe $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_vb6run()
{
ww_download 73ef177008005675134d2f02c6f580515ab0d842 'vb6run.exe' 'http://download.microsoft.com/download/5/a/d/5ad868a0-8ecd-4bb0-a882-fe53eb7ef348/VB6.0-KB290887-X86.exe' '' 
}

ww_check_vb6run()
{
ww_native "$WW_SYSTEM32/MSVBVM60.DLL"
}

ww_install_vb6run()
{
ww_wine "$WW_CACHE"/vb6run.exe "/T:$WW_TEMP_WIN" /c $WW_UNATTENDED_SLASH_Q
ww_exists "$WW_TEMP"/vbrun60sp6.exe || ww_die vbrun60sp6.exe not found

rm -f "$WW_SYSTEM32"/comcat.dll
rm -f "$WW_SYSTEM32"/oleaut32.dll
rm -f "$WW_SYSTEM32"/olepro32.dll
rm -f "$WW_SYSTEM32"/stdole2.tlb

ww_cd "$WW_TEMP"
wine vbrun60sp6.exe $WW_UNATTENDED_SLASH_Q

status=$?
case $status in
    0|43) ;;
    *) ww_die vb6run installation failed
esac
}

#---------------------------------------------------------------------------------------

ww_download_vcrun2003()
{
ww_download 9ffdd079dace2723e1849dd93bb23ed7b9c3b06b 'mfc71.zip' 'http://www.dll-files.com/dllindex/dll-files.shtml?mfc71' 'href="\(.*f35a584e947a5b401feb0fe01db4a0d7.*\)">' 
ww_download 9119ded781b67b3ff7825218113c697ef683212b 'msvcp71.zip' 'http://www.dll-files.com/dllindex/dll-files.shtml?msvcp71' 'href="\(.*561fa2abb31dfa8fab762145f81667c2.*\)">' 
ww_download 6db2a3fd269fa264ffc66dc491bb1dc223bbc70e 'msvcr71.zip' 'http://www.dll-files.com/dllindex/dll-files.shtml?msvcr71' 'href="\(.*86f1895ae8c5e8b17d99ece768a70732.*\)">' 
}

ww_check_vcrun2003()
{
ww_native "$WW_SYSTEM32/msvcp71.dll"
}

ww_install_vcrun2003()
{
ww_unzip "$WW_TEMP" "$WW_CACHE"/mfc71.zip
ww_unzip "$WW_TEMP" "$WW_CACHE"/msvcp71.zip
ww_unzip "$WW_TEMP" "$WW_CACHE"/msvcr71.zip
ww_cp "$WW_TEMP"/MSVCP71.DLL "$WW_SYSTEM32"/msvcp71.dll
ww_cp "$WW_TEMP"/msvcr71.dll "$WW_SYSTEM32"
ww_cp "$WW_TEMP"/mfc71.dll "$WW_SYSTEM32"
}

#---------------------------------------------------------------------------------------

ww_download_vcrun2005()
{
ww_download b8fab0bb7f62a24ddfe77b19cd9a1451abd7b847 'vcrun2005.exe' 'http://download.microsoft.com/download/8/B/4/8B42259F-5D70-43F4-AC2E-4B208FD8D66A/vcredist_x86.EXE' '' 
}

ww_check_vcrun2005()
{
ww_native "$WW_WINDOWS/winsxs/x86_Microsoft.VC80.MFC_1fc8b3b9a1e18e3b_8.0.50727.6195_x-ww_150c9e8b/mfc80.dll" || ww_native "$WW_WINDOWS/winsxs/x86_microsoft.vc80.mfc_1fc8b3b9a1e18e3b_8.0.50727.6195_none_deadbeef/mfc80.dll"
}

ww_install_vcrun2005()
{
ww_override native,builtin atl80 msvcm80 msvcp80 msvcr80 vcomp
ww_cd_repo_wine vcrun2005.exe $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_vcrun2008()
{
ww_download 470640aa4bb7db8e69196b5edb0010933569e98d 'vcrun2008.exe' 'http://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe' '' 
}

ww_check_vcrun2008()
{
ww_native "$WW_PROGRAM_FILES/Common Files/Microsoft Shared/VC/msdia90.dll"
}

ww_install_vcrun2008()
{
ww_override native,builtin atl90 msvcm90 msvcp90 msvcr90 vcomp90
ww_cd_repo_wine vcrun2008.exe $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_vcrun2010()
{
ww_download 372d9c1670343d3fb252209ba210d4dc4d67d358 'vcrun2010.exe' 'http://download.microsoft.com/download/5/B/C/5BC5DBB3-652D-4DCE-B14A-475AB85EEF6E/vcredist_x86.exe' '' 
}

ww_check_vcrun2010()
{
ww_native "$WW_SYSTEM32/mfc100.dll"
}

ww_install_vcrun2010()
{
ww_override native,builtin msvcp100 msvcr100 vcomp100 atl100
ww_cd_repo_wine vcrun2010.exe $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_vcrun2012()
{
ww_download 96b377a27ac5445328cbaae210fc4f0aaa750d3f 'vcrun2012.exe' 'http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x86.exe' '' 
}

ww_check_vcrun2012()
{
ww_native "$WW_SYSTEM32/mfc110.dll"
}

ww_install_vcrun2012()
{
ww_override native,builtin atl110 msvcp110 msvcr110 vcomp110
ww_cd_repo_wine vcrun2012.exe $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_vcrun2013()
{
ww_download df7f0a73bfa077e483e51bfb97f5e2eceedfb6a3 'vcrun2013.exe' 'http://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe' '' 
}

ww_check_vcrun2013()
{
ww_native "$WW_SYSTEM32/mfc120.dll"
}

ww_install_vcrun2013()
{
ww_override native,builtin atl120 msvcp120 msvcr120 vcomp120
ww_cd_repo_wine vcrun2013.exe $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_vcrun2015()
{
ww_download bfb74e498c44d3a103ca3aa2831763fb417134d1 'vcrun2015.exe' 'https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe' '' 
}

ww_check_vcrun2015()
{
ww_native "$WW_SYSTEM32/mfc140.dll"
}

ww_install_vcrun2015()
{
ww_override native,builtin api-ms-win-crt-conio-l1-1-0 api-ms-win-crt-heap-l1-1-0 api-ms-win-crt-locale-l1-1-0 api-ms-win-crt-math-l1-1-0.dll api-ms-win-crt-runtime-l1-1-0 api-ms-win-crt-stdio-l1-1-0 atl140 msvcp140 msvcr140 ucrtbase vcomp140 vcruntime140

ww_cd_repo_wine vcrun2015.exe $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_vcrun6()
{
ww_download a8c4dd33e281c166488846a10edf97ff0ce37044 'vcrun6.exe' 'http://download.microsoft.com/download/vc60pro/Update/2/W9XNT4/EN-US/VC6RedistSetup_deu.exe' '' 
}

ww_check_vcrun6()
{
ww_native "$WW_SYSTEM32/mfc42.dll"
}

ww_install_vcrun6()
{
ww_vcrun6_helper

rm -f "$WW_SYSTEM32"/comcat.dll
rm -f "$WW_SYSTEM32"/msvcrt.dll
rm -f "$WW_SYSTEM32"/oleaut32.dll
rm -f "$WW_SYSTEM32"/olepro32.dll
rm -f "$WW_SYSTEM32"/stdole2.tlb
wine "$WW_TEMP"/vcredist.exe

status=$?
case $status in
    0|43) ;;
    *) ww_die vcrun6 installation failed
esac

ww_cabextract "$WW_TEMP"/vcredist.exe -d "$WW_SYSTEM32" -F "mfc42*.dll"
}

#---------------------------------------------------------------------------------------

ww_download_vcrun6sp6()
{
ww_download 2292437a8967349261c810ae8b456592eeb76620 'vcrun6sp6.exe' 'http://download.microsoft.com/download/1/9/f/19fe4660-5792-4683-99e0-8d48c22eed74/Vs6sp6.exe' '' 
}

ww_check_vcrun6sp6()
{
ww_native "$WW_SYSTEM32/mfc42.dll"
}

ww_install_vcrun6sp6()
{
ww_cabextract "$WW_CACHE"/vcrun6sp6.exe -d "$WW_TEMP" -F vcredist.exe

ww_try rm -f "$WW_SYSTEM32"/comcat.dll
ww_try rm -f "$WW_SYSTEM32"/msvcrt.dll
ww_try rm -f "$WW_SYSTEM32"/oleaut32.dll
ww_try rm -f "$WW_SYSTEM32"/olepro32.dll
ww_try rm -f "$WW_SYSTEM32"/stdole2.tlb

ww_cd "$WW_TEMP"
wine vcredist.exe

status=$?
case $status in
    0|43) ;;
    *) ww_die vcrun6sp6 installation failed
esac

ww_cabextract vcredist.exe -d "$WW_SYSTEM32" -F mfc42u.dll
}

#---------------------------------------------------------------------------------------

ww_download_videomemorysize()
{
:
}

ww_check_videomemorysize()
{
false
}

ww_install_videomemorysize()
{
ww_set_videomemorysize "$WW_VMEMORY_SIZE"
}

#---------------------------------------------------------------------------------------

ww_download_vjrun20()
{
ww_download a3625c59d7a2995fb60877b5f5324892a1693b2a 'dotnet20.exe' 'http://download.lenovo.com/ibmdl/pub/pc/pccbbs/thinkvantage_en/dotnetfx.exe' '' 
ww_download 80a098e36b90d159da915aebfbfbacf35f302bd8 'vjrun20.exe' 'http://download.microsoft.com/download/9/2/3/92338cd0-759f-4815-8981-24b437be74ef/vjredist.exe' '' 
}

ww_check_vjrun20()
{
ww_native "$WW_WINDOWS/Microsoft.NET/Framework/VJSharp/VJSharpSxS10.dll"
}

ww_install_vjrun20()
{
ww_install dotnet20
ww_cd_repo_wine vjrun20.exe /q /C:"install $WW_UNATTENDED_SLASH_QNT"
}

#---------------------------------------------------------------------------------------

ww_download_vsm_0()
{
:
}

ww_check_vsm_0()
{
false
}

ww_install_vsm_0()
{
ww_set_wined3d_var MaxShaderModelVS 0
}

#---------------------------------------------------------------------------------------

ww_download_vsm_1()
{
:
}

ww_check_vsm_1()
{
false
}

ww_install_vsm_1()
{
ww_set_wined3d_var MaxShaderModelVS 1
}

#---------------------------------------------------------------------------------------

ww_download_vsm_2()
{
:
}

ww_check_vsm_2()
{
false
}

ww_install_vsm_2()
{
ww_set_wined3d_var MaxShaderModelVS 2
}

#---------------------------------------------------------------------------------------

ww_download_vsm_3()
{
:
}

ww_check_vsm_3()
{
false
}

ww_install_vsm_3()
{
ww_set_wined3d_var MaxShaderModelVS 3
}

#---------------------------------------------------------------------------------------

ww_download_wenquanyi()
{
ww_download 28023041b22b6368bcfae076de68109b81e77976 'wenquanyi.tar.gz' 'http://downloads.sourceforge.net/wqy/wqy-microhei-0.2.0-beta.tar.gz' '' 
}

ww_check_wenquanyi()
{
ww_exists "$WW_FONTS/wqy-microhei.ttc"
}

ww_install_wenquanyi()
{
ww_cd "$WW_TEMP"
gunzip -dc "$WW_CACHE/wenquanyi.tar.gz" | tar -xf -
ww_try mv wqy-microhei/wqy-microhei.ttc "$WW_FONTS"
ww_register_font wqy-microhei.ttc "WenQuanYi Micro Hei"
}

#---------------------------------------------------------------------------------------

ww_download_windowmanagerdecorated_n()
{
:
}

ww_check_windowmanagerdecorated_n()
{
false
}

ww_install_windowmanagerdecorated_n()
{
ww_set_windowmanagerdecorated n
}

#---------------------------------------------------------------------------------------

ww_download_windowmanagerdecorated_y()
{
:
}

ww_check_windowmanagerdecorated_y()
{
false
}

ww_install_windowmanagerdecorated_y()
{
ww_set_windowmanagerdecorated y
}

#---------------------------------------------------------------------------------------

ww_download_windowmanagermanaged_n()
{
:
}

ww_check_windowmanagermanaged_n()
{
false
}

ww_install_windowmanagermanaged_n()
{
ww_set_windowmanagermanaged n
}

#---------------------------------------------------------------------------------------

ww_download_windowmanagermanaged_y()
{
:
}

ww_check_windowmanagermanaged_y()
{
false
}

ww_install_windowmanagermanaged_y()
{
ww_set_windowmanagermanaged y
}

#---------------------------------------------------------------------------------------

ww_download_windowscodecs()
{
ww_download 53c18652ac2f8a51303deb48a1b7abbdb1db427f 'windowscodecs.exe' 'http://download.microsoft.com/download/f/f/1/ff178bb1-da91-48ed-89e5-478a99387d4f/wic_x86_enu.exe' '' 
}

ww_check_windowscodecs()
{
ww_native "$WW_SYSTEM32/WindowsCodecs.dll"
}

ww_install_windowscodecs()
{
ww_try rm -f "$WW_SYSTEM32"/windowscodecs.dll "$WW_SYSTEM32"/windowscodecsext.dll "$WW_SYSTEM32"/photometadatahandler.dll

ww_override native windowscodecs windowscodecsext

if test -x /usr/bin/taskset && ww_workaround_wine_bug 32859 "Working around possibly broken libX11"
then
    TASKSET="taskset -c 0"
else
    TASKSET=""
fi

ww_cd_repo
ww_try $TASKSET wine windowscodecs.exe /passive
}

#---------------------------------------------------------------------------------------

ww_download_winhttp()
{
ww_download fadea6d94a014b039839fecc6e6a11c20afa4fa8 'win2ksp4.exe' 'ftp://ftp.vcitynet.com/win32/win2k/W2KSP4_EN.EXE' '' 'http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 'https://web.archive.org/web/20160129053851/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 
}

ww_check_winhttp()
{
ww_native "$WW_SYSTEM32/winhttp.dll"
}

ww_install_winhttp()
{
ww_win2ksp4_helper i386/new/winhttp.dl_
ww_cabextract -d "$WW_SYSTEM32" "$WW_TEMP"/i386/new/winhttp.dl_
ww_override native,builtin winhttp
}

#---------------------------------------------------------------------------------------

ww_download_wininet()
{
ww_download fadea6d94a014b039839fecc6e6a11c20afa4fa8 'win2ksp4.exe' 'ftp://ftp.vcitynet.com/win32/win2k/W2KSP4_EN.EXE' '' 'http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 'https://web.archive.org/web/20160129053851/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE' '' 
}

ww_check_wininet()
{
ww_native "$WW_SYSTEM32/wininet.dll"
}

ww_install_wininet()
{
ww_win2ksp4_helper i386/wininet.dl_
ww_cabextract -d "$WW_SYSTEM32" "$WW_TEMP"/i386/wininet.dl_
ww_override native,builtin wininet
}

#---------------------------------------------------------------------------------------

ww_download_winver_nt40()
{
:
}

ww_check_winver_nt40()
{
false
}

ww_install_winver_nt40()
{
set_winver nt40
}

#---------------------------------------------------------------------------------------

ww_download_winver_vista()
{
:
}

ww_check_winver_vista()
{
false
}

ww_install_winver_vista()
{
set_winver vista
}

#---------------------------------------------------------------------------------------

ww_download_winver_win2k()
{
:
}

ww_check_winver_win2k()
{
false
}

ww_install_winver_win2k()
{
ww_set_winver win2k
}

#---------------------------------------------------------------------------------------

ww_download_winver_win2k3()
{
:
}

ww_check_winver_win2k3()
{
false
}

ww_install_winver_win2k3()
{
ww_set_winver win2k3
}

#---------------------------------------------------------------------------------------

ww_download_winver_win7()
{
:
}

ww_check_winver_win7()
{
false
}

ww_install_winver_win7()
{
ww_set_winver win7
}

#---------------------------------------------------------------------------------------

ww_download_winver_win98()
{
:
}

ww_check_winver_win98()
{
false
}

ww_install_winver_win98()
{
ww_set_winver win98
}

#---------------------------------------------------------------------------------------

ww_download_winver_winxp()
{
:
}

ww_check_winver_winxp()
{
false
}

ww_install_winver_winxp()
{
ww_set_winver winxp
}

#---------------------------------------------------------------------------------------

ww_download_wmi()
{
ww_download 62752e9c1b879688c26f205eebf07d3783906c3e 'wmi.exe' 'http://download.microsoft.com/download/platformsdk/wmi9x/1.5/W9X/EN-US/wmi9x.exe' '' 
}

ww_check_wmi()
{
ww_native "$WW_SYSTEM32/wbem/wbemcore.dll"
}

ww_install_wmi()
{
ww_set_winver win98
ww_override native,builtin wbemprox wmiutils
ww_cd_repo_wine wmi.exe $WW_UNATTENDED_SLASH_S
ww_unset_winver
}

#---------------------------------------------------------------------------------------

ww_download_wmp10()
{
ww_download 8b76bdcbea0057eb12b7966edab4b942ddacc253 'wm9codecs.exe' 'http://birds.camden.rutgers.edu/WM9Codecs9x.exe' '' 
ww_download 69862273a5d9d97b4a2e5a3bd93898d259e86657 'wmp10.exe' 'http://download.microsoft.com/download/1/2/a/12a31f29-2fa9-4f50-b95d-e45ef7013f87/MP10Setup.exe' '' 
ww_download b15c6a834b7029e2dfed22127cf905b06857e6f5 'wsh57.exe' 'http://download.microsoft.com/download/4/4/d/44de8a9e-630d-4c10-9f17-b9b34d3f6417/scripten.exe' '' 
}

ww_check_wmp10()
{
ww_native "$WW_SYSTEM32/l3codecp.acm"
}

ww_install_wmp10()
{
ww_install wsh57

ww_cd_repo_wine wmp10.exe $WW_UNATTENDED_SLASH_Q

ww_regedit /D "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Cdr4_2K"
ww_regedit /D "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Cdralw2k"

ww_wm9codecs

ww_unset_winver
}

#---------------------------------------------------------------------------------------

ww_download_wmp9()
{
ww_download 8b76bdcbea0057eb12b7966edab4b942ddacc253 'wm9codecs.exe' 'http://birds.camden.rutgers.edu/WM9Codecs9x.exe' '' 
ww_download 580536d10657fa3868de2869a3902d31a0de791b 'wmp9.exe' 'http://download.microsoft.com/download/1/b/c/1bc0b1a3-c839-4b36-8f3c-19847ba09299/MPSetup.exe' '' 
ww_download b15c6a834b7029e2dfed22127cf905b06857e6f5 'wsh57.exe' 'http://download.microsoft.com/download/4/4/d/44de8a9e-630d-4c10-9f17-b9b34d3f6417/scripten.exe' '' 
}

ww_check_wmp9()
{
ww_native "$WW_SYSTEM32"/l3codeca.acm
}

ww_install_wmp9()
{
ww_install wsh57

ww_set_winver win2k

rm -f "$WW_SYSTEM32"/wmvcore.dll "$WW_SYSTEM32"/wmp.dll
ww_override native wmp

ww_override_app wmp9.exe native pidgen

ww_cd_repo_wine wmp9.exe $WW_UNATTENDED_SLASH_Q

ww_wm9codecs

ww_unset_winver
}

#---------------------------------------------------------------------------------------

ww_download_wmv9vcm()
{
ww_download 0ace94c09bfab15410db3a15ffa42370891266de 'wmv9vcm.exe' 'https://download.microsoft.com/download/2/8/D/28DA9C3E-6DA2-456F-BD33-1F937EB6E0FF/WindowsServer2003-WindowsMedia-KB2845142-x86-ENU.exe' '' 
}

ww_check_wmv9vcm()
{
ww_native "$WW_SYSTEM32/wmv9vcm.dll"
}

ww_install_wmv9vcm()
{
ww_cabextract -d "$WW_TEMP" "$WW_CACHE/wmv9vcm.exe"

ww_cp "$WW_TEMP"/wm64/wmv9vcm.dll "$WW_SYSTEM32"

cat > "$WW_TEMP"/tmp.reg <<_EOF_
REGEDIT4
[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Drivers32]
"vidc.WMV3"="wmv9vcm.dll"

_EOF_
ww_regedit "$WW_TEMP_WIN"\\tmp.reg
}

#---------------------------------------------------------------------------------------

ww_download_wsh56js()
{
ww_download add5f74c5bd4da6cfae47f8306de213ec6ed52c8 'wsh56js.exe' 'http://download.microsoft.com/download/b/c/3/bc3a0c36-fada-497d-a3de-8b0139766f3b/Windows2000-KB917344-56-x86-enu.exe' '' 
}

ww_check_wsh56js()
{
ww_exists ww_native "$WW_WINDOWS/inf/jscren.inf"
}

ww_install_wsh56js()
{
ww_override native,builtin jscript
ww_try rm "$WW_SYSTEM32/jscript.dll"
ww_cd_repo_wine wsh56js.exe $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_wsh56vb()
{
ww_download 48f14a93db33caff271da0c93f334971f9d7cb22 'wsh56vb.exe' 'https://web.archive.org/web/20141107073935/http://download.microsoft.com/download/IE60/Patch/Q318089/W9XNT4Me/EN-US/vbs56men.exe' '' 
}

ww_check_wsh56vb()
{
ww_native "$WW_SYSTEM32/vbscript.dll"
}

ww_install_wsh56vb()
{
ww_override native,builtin vbscript
ww_try rm "$WW_SYSTEM32/vbscript.dll"
ww_cd_repo_wine wsh56vb.exe $WW_UNATTENDED_SLASH_Q
}

#---------------------------------------------------------------------------------------

ww_download_wsh57()
{
ww_download b15c6a834b7029e2dfed22127cf905b06857e6f5 'wsh57.exe' 'http://download.microsoft.com/download/4/4/d/44de8a9e-630d-4c10-9f17-b9b34d3f6417/scripten.exe' '' 
}

ww_check_wsh57()
{
ww_native "$WW_SYSTEM32/scrrun.dll"
}

ww_install_wsh57()
{
ww_cabextract -d "$WW_SYSTEM32" "$WW_CACHE"/wsh57.exe
ww_override native,builtin jscript scrrun vbscript cscript.exe wscript.exe
ww_regsvr dispex.dll jscript.dll scrobj.dll scrrun.dll vbscript.dll wshcon.dll wshext.dll
}

#---------------------------------------------------------------------------------------

ww_download_xact()
{
ww_dx_feb2010_download
}

ww_check_xact()
{
ww_native "$WW_SYSTEM32/xactengine2_0.dll"
}

ww_install_xact()
{
ww_cabextract -d "$WW_TEMP" -L -F '*_xact_*x86*' "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_TEMP" -L -F '*_x3daudio_*x86*' "$WW_DX_FEB_PATH"
ww_cabextract -d "$WW_TEMP" -L -F '*_xaudio_*x86*' "$WW_DX_FEB_PATH"
for x in "$WW_TEMP"/*.cab
do
  ww_cabextract -d "$WW_SYSTEM32" -L -F 'xactengine*.dll' "$x"
  ww_cabextract -d "$WW_SYSTEM32" -L -F 'xaudio*.dll' "$x"
  ww_cabextract -d "$WW_SYSTEM32" -L -F 'x3daudio*.dll' "$x"
  ww_cabextract -d "$WW_SYSTEM32" -L -F 'xapofx*.dll' "$x"
done

for x in "$WW_SYSTEM32"/xactengine*
do
  ww_regsvr `basename "$x"`
done

for x in 0 1 2 3 4 5 6 7
do
  ww_regsvr `basename "$WW_SYSTEM32/xaudio2_${x}"`
done
}

#---------------------------------------------------------------------------------------

ww_download_xact_jun2010()
{
ww_dx_jun2010_download
}

ww_check_xact_jun2010()
{
ww_native "$WW_SYSTEM32/xactengine2_0.dll"
}

ww_install_xact_jun2010()
{
ww_cabextract -d "$WW_TEMP" -L -F '*_xact_*x86*' "$WW_DX_JUN_PATH"
ww_cabextract -d "$WW_TEMP" -L -F '*_x3daudio_*x86*' "$WW_DX_JUN_PATH"
ww_cabextract -d "$WW_TEMP" -L -F '*_xaudio_*x86*' "$WW_DX_JUN_PATH"
for x in "$WW_TEMP"/*.cab
do
  ww_cabextract -d "$WW_SYSTEM32" -L -F 'xactengine*.dll' "$x"
  ww_cabextract -d "$WW_SYSTEM32" -L -F 'xaudio*.dll' "$x"
  ww_cabextract -d "$WW_SYSTEM32" -L -F 'x3daudio*.dll' "$x"
  ww_cabextract -d "$WW_SYSTEM32" -L -F 'xapofx*.dll' "$x"
done

for x in "$WW_SYSTEM32"/xactengine*
do
  ww_regsvr `basename "$x"`
done

for x in 0 1 2 3 4 5 6 7
do
  ww_regsvr `basename "$WW_SYSTEM32/xaudio2_${x}"`
done
}

#---------------------------------------------------------------------------------------

ww_download_xinput()
{
ww_dx_feb2010_download
}

ww_check_xinput()
{
ww_native "$WW_SYSTEM32/xinput1_1.dll"
}

ww_install_xinput()
{
ww_cabextract -d "$WW_TEMP" -L -F '*_xinput_*x86*' "$WW_DX_FEB_PATH"
for x in "$WW_TEMP"/*.cab
do
    ww_cabextract -d "$WW_SYSTEM32" -L -F 'xinput*.dll' "$x"
done

ww_override native xinput1_1
ww_override native xinput1_2
ww_override native xinput1_3
ww_override native xinput9_1_0
}

#---------------------------------------------------------------------------------------

ww_download_xna31()
{
ww_download b3981b13fbc45823131f69d125992d6330212f27 'ahk.zip' 'http://www.autohotkey.com/download/AutoHotkey104805.zip' '' 
ww_download a3625c59d7a2995fb60877b5f5324892a1693b2a 'dotnet20.exe' 'http://download.lenovo.com/ibmdl/pub/pc/pccbbs/thinkvantage_en/dotnetfx.exe' '' 
ww_download 22d776d4d204863105a5db99e8b8888be23c61a7 'dotnet20sp2.exe' 'http://download.microsoft.com/download/c/6/e/c6e88215-0178-4c6c-b5f3-158ff77b1f38/NetFx20SP2_x86.exe' '' 
ww_download bdd33b677c9576a63ff2a6f65e12c0563cc116e6 'xna31.msi' 'http://download.microsoft.com/download/5/9/1/5912526C-B950-4662-99B6-119A83E60E5C/xnafx31_redist.msi' '' 
}

ww_check_xna31()
{
ww_native "$WW_WINDOWS/assembly/GAC_32/Microsoft.Xna.Framework.Game/3.1.0.0__6d5c3888ef60e27d/Microsoft.Xna.Framework.Game.dll"
}

ww_install_xna31()
{
ww_install dotnet20sp2
ww_cd_repo_wine msiexec $WW_UNATTENDED_SLASH_QUIET /i xna31.msi
}

#---------------------------------------------------------------------------------------

ww_download_xna40()
{
ww_download 58da3d74db353aad03588cbb5cea8234166d8b99 'dotnet40.exe' 'http://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe' '' 
ww_download 49efdc29f65fc8263c196338552c7009fc96c5de 'xna40.msi' 'http://download.microsoft.com/download/A/C/2/AC2C903B-E6E8-42C2-9FD7-BEBAC362A930/xnafx40_redist.msi' '' 
}

ww_check_xna40()
{
ww_native "$WW_PROGRAM_FILES/Common Files/Microsoft Shared/XNA/Framework/v4.0/XnaNative.dll"
}

ww_install_xna40()
{
if ww_workaround_wine_bug 30718
then
    ww_warn "xna40 may not install properly in wine yet"
fi

export COMPlus_OnlyUseLatestCLR=1
ww_install dotnet40

ww_cd_repo_wine msiexec $WW_UNATTENDED_SLASH_QUIET /i xna40.msi
}

#---------------------------------------------------------------------------------------

ww_download_xvid()
{
ww_download a8c4dd33e281c166488846a10edf97ff0ce37044 'vcrun6.exe' 'http://download.microsoft.com/download/vc60pro/Update/2/W9XNT4/EN-US/VC6RedistSetup_deu.exe' '' 
ww_download 0a11498a96f75ad019c4c7d06161504140337dc0 'xvid.exe' 'http://www.koepi.info/Xvid-1.3.2-20110601.exe' '' 
}

ww_check_xvid()
{
ww_exists "$WW_PROGRAM_FILES/Xvid/xvid.ico"
}

ww_install_xvid()
{
ww_install vcrun6
ww_cd_repo_wine xvid.exe --mode unattended --decode_divx 1 --decode_3ivx 1 --decode_other 1
}

#---------------------------------------------------------------------------------------
#                                         MAIN                                          
#---------------------------------------------------------------------------------------

WW_WINE_VERSION=$WW_BW
ww_init
ww_install_wine
ww_create_prefix
for f in $WW_BP
do
    ww_install $f
done
ww_setup
if [ $WW_BW != $WW_AW ]
then
    WW_WINE_VERSION=$WW_AW
    ww_init
    ww_install_wine
else
    ww_init
fi
for f in $WW_AP
do
    ww_install $f
done
ww_done

